/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\bmpsdl.o c:\dropbox\2015\nim\packer\example\nimcache\bmpsdl.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct TY171204 TY171204;
typedef struct surface132715 surface132715;
typedef struct TY172151 TY172151;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct pixelformat132709 pixelformat132709;
typedef struct rect132277 rect132277;
typedef struct blitmapptrHEX3Aobjecttype132757 blitmapptrHEX3Aobjecttype132757;
typedef struct TGenericSeq TGenericSeq;
typedef struct palette132707 palette132707;
typedef struct TY153691 TY153691;
typedef struct color132705 color132705;
struct  TY172151  {
NI HEX3Astate;
FILE* Fhdl171009;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NU32, TY143131) (int bpp, NU32 rmask, NU32 gmask, NU32 bmask, NU32 amask);
typedef N_CDECL_PTR(surface132715*, TY142292) (surface132715* src, NU32 pixelformat, NU32 flags);
struct rect132277 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  surface132715  {
NU32 Flags;
pixelformat132709* Format;
NI32 W;
NI32 H;
NI32 Pitch;
void* Pixels;
void* Userdata;
NI32 Locked;
void* Lockdata;
rect132277 Cliprect;
blitmapptrHEX3Aobjecttype132757* Map;
int Refcount;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef NU8 TY171186[4];
typedef NU8 TY171384[2];
typedef NU8 TY132739[2];
struct  pixelformat132709  {
NU32 Format;
palette132707* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY132739 Padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int Refcount;
pixelformat132709* Next;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (TY171204* s0, void* ClEnv);
void* ClEnv;
} TY171012;
typedef N_CLOSURE_PTR(void, TMP667) (TY171204* s0);
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI i0, void* ClEnv);
void* ClEnv;
} TY171029;
typedef N_CLOSURE_PTR(void, TMP669) (NI i0);
typedef N_CLOSURE_PTR(void, TMP670) (TY171204* s0);
typedef N_CDECL_PTR(void, TY142126) (surface132715* surface);
struct  blitmapptrHEX3Aobjecttype132757  {
char dummy;
};
struct  palette132707  {
int Ncolors;
color132705* Colors;
NU32 Version;
int Refcount;
};
struct color132705 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
struct TY171204 {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct TY153691 {
  TGenericSeq Sup;
  NI8 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, add_171194)(TY171204** x_171202, NU8* y_171208, NI y_171208Len0);
N_NIMCALL(void, writebmp32_171007)(FILE* fhdl, surface132715* isurf);
N_NIMCALL(void, TMP662)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NU32, bi_171275)(NU32 i0);
static N_INLINE(void, bigendian32_170090)(void* outp, void* inp);
N_NIMCALL(void, swapendian32_170025)(void* outp, void* inp);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, add_171108)(TY171204** s0, NI i0);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_CLOSURE(void, wu8_171011)(TY171204* s0, void* ClEnv);
N_NIMCALL(NI, writebytes_13032)(FILE* f, NI8* a, NI aLen0, NI start, NI len);
N_CLOSURE(void, wi_171028)(NI i0, void* ClEnv);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, writebuffer_13046)(FILE* f, void* buffer, NI len);
static N_INLINE(void, destroy_143601)(surface132715* surface);
TNimType NTI172151; /* object */
extern TNimType NTI148033; /* range -1..0(int) */
extern TNimType NTI12404; /* File */
TNimType NTI172181; /* ref object */
extern TY143131 Dl_143130;
extern TFrame* frameptr_16242;
extern TY142292 Dl_142291;
extern TNimType NTI171204; /* seq[uint8] */
extern TY142126 Dl_142125;
N_NIMCALL(void, TMP662)(void* p, NI op) {
	TY172151* a;
	a = (TY172151*)p;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(void, bigendian32_170090)(void* outp, void* inp) {
	nimfr("bigEndian32", "endians.nim")
	nimln(58, "endians.nim");
	swapendian32_170025(outp, inp);
	popFrame();
}

N_NIMCALL(NU32, bi_171275)(NU32 i0) {
	NU32 result;
	NU32 p;
	NU32 q;
	nimfr("bi", "bmpsdl.nim")
	result = 0;
	nimln(21, "bmpsdl.nim");
	p = ((NU32) 0);
	nimln(22, "bmpsdl.nim");
	q = i0;
	nimln(23, "bmpsdl.nim");
	bigendian32_170090(((void*) ((&p))), ((void*) ((&q))));
	nimln(24, "bmpsdl.nim");
	nimln(24, "bmpsdl.nim");
	result = p;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, add_171108)(TY171204** s0, NI i0) {
	TY171204* LOC1;
	TY171186 LOC2;
	nimfr("add", "bmpsdl.nim")
	nimln(16, "bmpsdl.nim");
	nimln(16, "bmpsdl.nim");
	LOC1 = 0;
	LOC1 = (TY171204*) newSeq((&NTI171204), 4);
	nimln(16, "bmpsdl.nim");
	LOC2[0] = ((NU8) ((NI)(i0 & 255)));
	nimln(17, "bmpsdl.nim");
	nimln(17, "bmpsdl.nim");
	LOC2[1] = ((NU8) ((NI)((NI)((NU32)(i0) >> (NU32)(8)) & 255)));
	nimln(18, "bmpsdl.nim");
	nimln(18, "bmpsdl.nim");
	LOC2[2] = ((NU8) ((NI)((NI)((NU32)(i0) >> (NU32)(16)) & 255)));
	nimln(19, "bmpsdl.nim");
	nimln(19, "bmpsdl.nim");
	LOC2[3] = ((NU8) ((NI)((NI)((NU32)(i0) >> (NU32)(24)) & 255)));
	LOC1->data[0] = LOC2[0];
	LOC1->data[1] = LOC2[1];
	LOC1->data[2] = LOC2[2];
	LOC1->data[3] = LOC2[3];
	add_171194(s0, LOC1->data, LOC1->Sup.len);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_CLOSURE(void, wu8_171011)(TY171204* s0, void* ClEnv) {
	TY172151* HEX3Aenvp_172163;
	NI LOC1;
	nimfr("wu8", "bmpsdl.nim")
	HEX3Aenvp_172163 = (TY172151*) ClEnv;
	nimln(7, "bmpsdl.nim");
	nimln(7, "bmpsdl.nim");
	nimln(7, "bmpsdl.nim");
	LOC1 = 0;
	LOC1 = writebytes_13032((*HEX3Aenvp_172163).Fhdl171009, ((TY153691*) (s0))->data, ((TY153691*) (s0))->Sup.len, 0, s0->Sup.len);
	popFrame();
}

N_CLOSURE(void, wi_171028)(NI i0, void* ClEnv) {
	TY172151* HEX3Aenvp_172169;
	TY171204* LOC1;
	TY171186 LOC2;
	NI LOC3;
	nimfr("wi", "bmpsdl.nim")
	HEX3Aenvp_172169 = (TY172151*) ClEnv;
	nimln(9, "bmpsdl.nim");
	nimln(9, "bmpsdl.nim");
	nimln(9, "bmpsdl.nim");
	LOC1 = 0;
	LOC1 = (TY171204*) newSeq((&NTI171204), 4);
	nimln(10, "bmpsdl.nim");
	LOC2[0] = ((NU8) ((NI)(i0 & 255)));
	nimln(11, "bmpsdl.nim");
	nimln(11, "bmpsdl.nim");
	LOC2[1] = ((NU8) ((NI)((NI)((NU32)(i0) >> (NU32)(8)) & 255)));
	nimln(12, "bmpsdl.nim");
	nimln(12, "bmpsdl.nim");
	LOC2[2] = ((NU8) ((NI)((NI)((NU32)(i0) >> (NU32)(16)) & 255)));
	nimln(13, "bmpsdl.nim");
	nimln(13, "bmpsdl.nim");
	LOC2[3] = ((NU8) ((NI)((NI)((NU32)(i0) >> (NU32)(24)) & 255)));
	LOC1->data[0] = LOC2[0];
	LOC1->data[1] = LOC2[1];
	LOC1->data[2] = LOC2[2];
	LOC1->data[3] = LOC2[3];
	LOC3 = 0;
	LOC3 = writebytes_13032((*HEX3Aenvp_172169).Fhdl171009, ((TY153691*) (LOC1))->data, ((TY153691*) (LOC1))->Sup.len, 0, 4);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, destroy_143601)(surface132715* surface) {
	nimfr("destroy", "sdl2.nim")
	nimln(1484, "sdl2.nim");
	Dl_142125(surface);
	popFrame();
}

N_NIMCALL(void, writebmp32_171007)(FILE* fhdl, surface132715* isurf) {
	TY172151* HEX3Aenv_172180;
	NU32 pxformate;
	NU32 LOC1;
	NU32 LOC2;
	NU32 LOC3;
	NU32 LOC4;
	surface132715* surf;
	NI32* pxdata;
	NI32 pxdlen;
	NI32 TMP663;
	TY171204* dib;
	TY171204* LOC5;
	TY171204* LOC6;
	TY171384 LOC7;
	TY171204* LOC8;
	TY171204* LOC9;
	TY171204* LOC10;
	TY171204* LOC11;
	TY171204* LOC12;
	TY171204* LOC13;
	TY171204* LOC14;
	TY171204* LOC15;
	TY171204* LOC16;
	TY171204* LOC17;
	TY171204* bmp;
	TY171204* LOC18;
	NI TMP665;
	NI TMP666;
	TY171204* LOC19;
	TY171204* LOC20;
	TY171204* LOC21;
	TY171012 LOC22;
	TY171029 LOC23;
	NI TMP668;
	TY171012 LOC24;
	nimfr("writeBMP32", "bmpsdl.nim")
	HEX3Aenv_172180 = 0;
	nimln(172, "system.nim");
	HEX3Aenv_172180 = (TY172151*) newObj((&NTI172181), sizeof(TY172151));
	nimln(6, "bmpsdl.nim");
	(*HEX3Aenv_172180).Fhdl171009 = fhdl;
	nimln(26, "bmpsdl.nim");
	nimln(27, "bmpsdl.nim");
	LOC1 = 0;
	LOC1 = bi_171275(((NU32) 65280));
	nimln(27, "bmpsdl.nim");
	LOC2 = 0;
	LOC2 = bi_171275(((NU32) 16711680));
	nimln(27, "bmpsdl.nim");
	LOC3 = 0;
	LOC3 = bi_171275(((NU32) -16777216));
	nimln(27, "bmpsdl.nim");
	LOC4 = 0;
	LOC4 = bi_171275(((NU32) 255));
	pxformate = Dl_143130(((int) 32), LOC1, LOC2, LOC3, LOC4);
	nimln(28, "bmpsdl.nim");
	surf = Dl_142291(isurf, pxformate, ((NU32) 0));
	pxdata = 0;
	nimln(35, "bmpsdl.nim");
	pxdata = ((NI32*) ((*surf).Pixels));
	nimln(36, "bmpsdl.nim");
	nimln(36, "bmpsdl.nim");
	TMP663 = mulInt((*surf).Pitch, (*surf).H);
	pxdlen = (NI32)(TMP663);
	nimln(40, "bmpsdl.nim");
	dib = (TY171204*) newSeq((&NTI171204), 0);
	nimln(42, "bmpsdl.nim");
	add_171108((&dib), ((NI) ((*surf).W)));
	nimln(43, "bmpsdl.nim");
	add_171108((&dib), ((NI) ((*surf).H)));
	nimln(44, "bmpsdl.nim");
	LOC5 = 0;
	LOC5 = (TY171204*) newSeq((&NTI171204), 2);
	LOC5->data[0] = ((NU8) 1);
	LOC5->data[1] = ((NU8) 0);
	add_171194((&dib), LOC5->data, LOC5->Sup.len);
	nimln(45, "bmpsdl.nim");
	nimln(45, "bmpsdl.nim");
	LOC6 = 0;
	LOC6 = (TY171204*) newSeq((&NTI171204), 2);
	LOC7[0] = (*(*surf).Format).Bitsperpixel;
	LOC7[1] = ((NU8) 0);
	LOC6->data[0] = LOC7[0];
	LOC6->data[1] = LOC7[1];
	add_171194((&dib), LOC6->data, LOC6->Sup.len);
	nimln(46, "bmpsdl.nim");
	LOC8 = 0;
	LOC8 = (TY171204*) newSeq((&NTI171204), 4);
	LOC8->data[0] = ((NU8) 3);
	LOC8->data[1] = ((NU8) 0);
	LOC8->data[2] = ((NU8) 0);
	LOC8->data[3] = ((NU8) 0);
	add_171194((&dib), LOC8->data, LOC8->Sup.len);
	nimln(47, "bmpsdl.nim");
	add_171108((&dib), ((NI) (pxdlen)));
	nimln(48, "bmpsdl.nim");
	LOC9 = 0;
	LOC9 = (TY171204*) newSeq((&NTI171204), 4);
	LOC9->data[0] = ((NU8) 19);
	LOC9->data[1] = ((NU8) 11);
	LOC9->data[2] = ((NU8) 0);
	LOC9->data[3] = ((NU8) 0);
	add_171194((&dib), LOC9->data, LOC9->Sup.len);
	nimln(49, "bmpsdl.nim");
	LOC10 = 0;
	LOC10 = (TY171204*) newSeq((&NTI171204), 4);
	LOC10->data[0] = ((NU8) 19);
	LOC10->data[1] = ((NU8) 11);
	LOC10->data[2] = ((NU8) 0);
	LOC10->data[3] = ((NU8) 0);
	add_171194((&dib), LOC10->data, LOC10->Sup.len);
	nimln(50, "bmpsdl.nim");
	LOC11 = 0;
	LOC11 = (TY171204*) newSeq((&NTI171204), 4);
	LOC11->data[0] = ((NU8) 0);
	LOC11->data[1] = ((NU8) 0);
	LOC11->data[2] = ((NU8) 0);
	LOC11->data[3] = ((NU8) 0);
	add_171194((&dib), LOC11->data, LOC11->Sup.len);
	nimln(51, "bmpsdl.nim");
	LOC12 = 0;
	LOC12 = (TY171204*) newSeq((&NTI171204), 4);
	LOC12->data[0] = ((NU8) 0);
	LOC12->data[1] = ((NU8) 0);
	LOC12->data[2] = ((NU8) 0);
	LOC12->data[3] = ((NU8) 0);
	add_171194((&dib), LOC12->data, LOC12->Sup.len);
	nimln(52, "bmpsdl.nim");
	add_171108((&dib), ((NI) ((*(*surf).Format).Rmask)));
	nimln(53, "bmpsdl.nim");
	add_171108((&dib), ((NI) ((*(*surf).Format).Gmask)));
	nimln(54, "bmpsdl.nim");
	add_171108((&dib), ((NI) ((*(*surf).Format).Bmask)));
	nimln(55, "bmpsdl.nim");
	add_171108((&dib), ((NI) ((*(*surf).Format).Amask)));
	nimln(56, "bmpsdl.nim");
	LOC13 = 0;
	LOC13 = (TY171204*) newSeq((&NTI171204), 4);
	LOC13->data[0] = ((NU8) 32);
	LOC13->data[1] = ((NU8) 110);
	LOC13->data[2] = ((NU8) 105);
	LOC13->data[3] = ((NU8) 87);
	add_171194((&dib), LOC13->data, LOC13->Sup.len);
	nimln(57, "bmpsdl.nim");
	LOC14 = 0;
	LOC14 = (TY171204*) newSeq((&NTI171204), 36);
	LOC14->data[0] = ((NU8) 36);
	LOC14->data[1] = ((NU8) 0);
	LOC14->data[2] = ((NU8) 0);
	LOC14->data[3] = ((NU8) 0);
	LOC14->data[4] = ((NU8) 0);
	LOC14->data[5] = ((NU8) 0);
	LOC14->data[6] = ((NU8) 0);
	LOC14->data[7] = ((NU8) 0);
	LOC14->data[8] = ((NU8) 0);
	LOC14->data[9] = ((NU8) 0);
	LOC14->data[10] = ((NU8) 0);
	LOC14->data[11] = ((NU8) 0);
	LOC14->data[12] = ((NU8) 0);
	LOC14->data[13] = ((NU8) 0);
	LOC14->data[14] = ((NU8) 0);
	LOC14->data[15] = ((NU8) 0);
	LOC14->data[16] = ((NU8) 0);
	LOC14->data[17] = ((NU8) 0);
	LOC14->data[18] = ((NU8) 0);
	LOC14->data[19] = ((NU8) 0);
	LOC14->data[20] = ((NU8) 0);
	LOC14->data[21] = ((NU8) 0);
	LOC14->data[22] = ((NU8) 0);
	LOC14->data[23] = ((NU8) 0);
	LOC14->data[24] = ((NU8) 0);
	LOC14->data[25] = ((NU8) 0);
	LOC14->data[26] = ((NU8) 0);
	LOC14->data[27] = ((NU8) 0);
	LOC14->data[28] = ((NU8) 0);
	LOC14->data[29] = ((NU8) 0);
	LOC14->data[30] = ((NU8) 0);
	LOC14->data[31] = ((NU8) 0);
	LOC14->data[32] = ((NU8) 0);
	LOC14->data[33] = ((NU8) 0);
	LOC14->data[34] = ((NU8) 0);
	LOC14->data[35] = ((NU8) 0);
	add_171194((&dib), LOC14->data, LOC14->Sup.len);
	nimln(67, "bmpsdl.nim");
	LOC15 = 0;
	LOC15 = (TY171204*) newSeq((&NTI171204), 4);
	LOC15->data[0] = ((NU8) 0);
	LOC15->data[1] = ((NU8) 0);
	LOC15->data[2] = ((NU8) 0);
	LOC15->data[3] = ((NU8) 0);
	add_171194((&dib), LOC15->data, LOC15->Sup.len);
	nimln(68, "bmpsdl.nim");
	LOC16 = 0;
	LOC16 = (TY171204*) newSeq((&NTI171204), 4);
	LOC16->data[0] = ((NU8) 0);
	LOC16->data[1] = ((NU8) 0);
	LOC16->data[2] = ((NU8) 0);
	LOC16->data[3] = ((NU8) 0);
	add_171194((&dib), LOC16->data, LOC16->Sup.len);
	nimln(69, "bmpsdl.nim");
	LOC17 = 0;
	LOC17 = (TY171204*) newSeq((&NTI171204), 4);
	LOC17->data[0] = ((NU8) 0);
	LOC17->data[1] = ((NU8) 0);
	LOC17->data[2] = ((NU8) 0);
	LOC17->data[3] = ((NU8) 0);
	add_171194((&dib), LOC17->data, LOC17->Sup.len);
	nimln(72, "bmpsdl.nim");
	bmp = (TY171204*) newSeq((&NTI171204), 0);
	nimln(73, "bmpsdl.nim");
	LOC18 = 0;
	LOC18 = (TY171204*) newSeq((&NTI171204), 2);
	LOC18->data[0] = ((NU8) 66);
	LOC18->data[1] = ((NU8) 77);
	add_171194((&bmp), LOC18->data, LOC18->Sup.len);
	nimln(74, "bmpsdl.nim");
	nimln(74, "bmpsdl.nim");
	nimln(74, "bmpsdl.nim");
	nimln(74, "bmpsdl.nim");
	TMP665 = addInt(14, dib->Sup.len);
	TMP666 = addInt((NI32)(TMP665), ((NI) (pxdlen)));
	add_171108((&bmp), (NI32)(TMP666));
	nimln(75, "bmpsdl.nim");
	LOC19 = 0;
	LOC19 = (TY171204*) newSeq((&NTI171204), 2);
	LOC19->data[0] = ((NU8) 0);
	LOC19->data[1] = ((NU8) 0);
	add_171194((&bmp), LOC19->data, LOC19->Sup.len);
	nimln(76, "bmpsdl.nim");
	LOC20 = 0;
	LOC20 = (TY171204*) newSeq((&NTI171204), 2);
	LOC20->data[0] = ((NU8) 0);
	LOC20->data[1] = ((NU8) 0);
	add_171194((&bmp), LOC20->data, LOC20->Sup.len);
	nimln(77, "bmpsdl.nim");
	LOC21 = 0;
	LOC21 = (TY171204*) newSeq((&NTI171204), 4);
	LOC21->data[0] = ((NU8) 122);
	LOC21->data[1] = ((NU8) 0);
	LOC21->data[2] = ((NU8) 0);
	LOC21->data[3] = ((NU8) 0);
	add_171194((&bmp), LOC21->data, LOC21->Sup.len);
	nimln(79, "bmpsdl.nim");
	memset((void*)(&LOC22), 0, sizeof(LOC22));
	LOC22.ClPrc = wu8_171011; LOC22.ClEnv = HEX3Aenv_172180;
	LOC22.ClEnv? LOC22.ClPrc(bmp, LOC22.ClEnv):((TMP667)(LOC22.ClPrc))(bmp);
	nimln(80, "bmpsdl.nim");
	memset((void*)(&LOC23), 0, sizeof(LOC23));
	LOC23.ClPrc = wi_171028; LOC23.ClEnv = HEX3Aenv_172180;
	nimln(80, "bmpsdl.nim");
	nimln(80, "bmpsdl.nim");
	TMP668 = addInt(dib->Sup.len, 4);
	LOC23.ClEnv? LOC23.ClPrc((NI32)(TMP668), LOC23.ClEnv):((TMP669)(LOC23.ClPrc))((NI32)(TMP668));
	nimln(81, "bmpsdl.nim");
	memset((void*)(&LOC24), 0, sizeof(LOC24));
	LOC24.ClPrc = wu8_171011; LOC24.ClEnv = HEX3Aenv_172180;
	LOC24.ClEnv? LOC24.ClPrc(dib, LOC24.ClEnv):((TMP670)(LOC24.ClPrc))(dib);
	{
		NI32 i0_172107;
		NI32 HEX3Atmp_172146;
		NI32 res_172149;
		i0_172107 = 0;
		HEX3Atmp_172146 = 0;
		nimln(83, "bmpsdl.nim");
		nimln(83, "bmpsdl.nim");
		HEX3Atmp_172146 = subInt((*surf).H, 1);
		nimln(1576, "system.nim");
		res_172149 = ((NI32) 0);
		{
			nimln(1577, "system.nim");
			while (1) {
				void* pt0;
				NI32 i1;
				NI32 TMP671;
				NI pt1;
				NI32 TMP672;
				nimln(1577, "system.nim");
				if (!(res_172149 <= HEX3Atmp_172146)) goto LA27;
				nimln(1576, "system.nim");
				i0_172107 = res_172149;
				nimln(84, "bmpsdl.nim");
				pt0 = (*surf).Pixels;
				nimln(85, "bmpsdl.nim");
				nimln(85, "bmpsdl.nim");
				nimln(85, "bmpsdl.nim");
				TMP671 = subInt(subInt((*surf).H, 1), i0_172107);
				i1 = (NI32)(TMP671);
				nimln(86, "bmpsdl.nim");
				nimln(86, "bmpsdl.nim");
				TMP672 = mulInt((*surf).Pitch, i1);
				pt1 = ((NI) ((NI32)(TMP672)));
				nimln(87, "bmpsdl.nim");
				{
					NI TMP673;
					NI TMP674;
					NI LOC32;
					nimln(87, "bmpsdl.nim");
					nimln(87, "bmpsdl.nim");
					nimln(87, "bmpsdl.nim");
					TMP673 = addInt(pt1, ((NI) (subInt((*surf).Pitch, 1))));
					if (!((NI32)(TMP673) < ((NI) (pxdlen)))) goto LA30;
					nimln(88, "bmpsdl.nim");
					nimln(88, "bmpsdl.nim");
					nimln(88, "bmpsdl.nim");
					TMP674 = addInt(((NI) (pt0)), pt1);
					LOC32 = 0;
					LOC32 = writebuffer_13046((*HEX3Aenv_172180).Fhdl171009, ((void*) ((NI32)(TMP674))), ((NI) ((*surf).Pitch)));
				}
				LA30: ;
				nimln(1579, "system.nim");
				res_172149 = addInt(res_172149, 1);
			} LA27: ;
		}
	}
	nimln(89, "bmpsdl.nim");
	destroy_143601(surf);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_bmpsdlInit)(void) {
	nimfr("bmpsdl", "bmpsdl.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_bmpsdlDatInit)(void) {
static TNimNode* TMP661[2];
static TNimNode TMP655[3];
NTI172151.size = sizeof(TY172151);
NTI172151.kind = 18;
NTI172151.base = 0;
NTI172151.flags = 3;
TMP661[0] = &TMP655[1];
TMP655[1].kind = 1;
TMP655[1].offset = offsetof(TY172151, HEX3Astate);
TMP655[1].typ = (&NTI148033);
TMP655[1].name = ":state";
TMP661[1] = &TMP655[2];
TMP655[2].kind = 1;
TMP655[2].offset = offsetof(TY172151, Fhdl171009);
TMP655[2].typ = (&NTI12404);
TMP655[2].name = "fhdl171009";
TMP655[0].len = 2; TMP655[0].kind = 2; TMP655[0].sons = &TMP661[0];
NTI172151.node = &TMP655[0];
NTI172181.size = sizeof(TY172151*);
NTI172181.kind = 22;
NTI172181.base = (&NTI172151);
NTI172181.flags = 2;
NTI172181.marker = TMP662;
}

