/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -O3 -fno-strict-aliasing  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\example1.o c:\dropbox\2015\nim\packer\example\nimcache\example1.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdio.h>

#include <string.h>

#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct jsonnodeobj119042 jsonnodeobj119042;
typedef struct assetgroupHEX3Aobjecttype160022 assetgroupHEX3Aobjecttype160022;
typedef struct rect160007 rect160007;
typedef struct TY160020 TY160020;
typedef struct dataentry160005 dataentry160005;
typedef struct TY176050 TY176050;
typedef struct assetHEX3Aobjecttype160027 assetHEX3Aobjecttype160027;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY160031 TY160031;
typedef struct tcell44733 tcell44733;
typedef struct tcellseq44749 tcellseq44749;
typedef struct tgcheap46816 tgcheap46816;
typedef struct tcellset44745 tcellset44745;
typedef struct tpagedesc44741 tpagedesc44741;
typedef struct tmemregion27010 tmemregion27010;
typedef struct tsmallchunk26240 tsmallchunk26240;
typedef struct tllchunk27004 tllchunk27004;
typedef struct tbigchunk26242 tbigchunk26242;
typedef struct tintset26217 tintset26217;
typedef struct ttrunk26213 ttrunk26213;
typedef struct tavlnode27008 tavlnode27008;
typedef struct tgcstat46814 tgcstat46814;
typedef struct TY176329 TY176329;
typedef struct assetrectview160642 assetrectview160642;
typedef struct TY161494 TY161494;
typedef struct TY161832 TY161832;
typedef struct packmanifestHEX3Aobjecttype163045 packmanifestHEX3Aobjecttype163045;
typedef struct TY178163 TY178163;
typedef struct rendererptrHEX3Aobjecttype143572 rendererptrHEX3Aobjecttype143572;
typedef struct surface143709 surface143709;
typedef struct windowptrHEX3Aobjecttype143571 windowptrHEX3Aobjecttype143571;
typedef struct event143161 event143161;
typedef struct TY178166 TY178166;
typedef struct TY178169 TY178169;
typedef struct TY178178 TY178178;
typedef struct rect143271 rect143271;
typedef struct pixelformat143703 pixelformat143703;
typedef struct blitmapptrHEX3Aobjecttype143751 blitmapptrHEX3Aobjecttype143751;
typedef struct cropresultHEX3Aobjecttype160033 cropresultHEX3Aobjecttype160033;
typedef struct TY119057 TY119057;
typedef struct TY119058 TY119058;
typedef struct TY119062 TY119062;
typedef struct tbasechunk26238 tbasechunk26238;
typedef struct tfreecell26230 tfreecell26230;
typedef struct palette143701 palette143701;
typedef struct color143699 color143699;
typedef N_CDECL_PTR(int, TY157221) (int flags);
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  dataentry160005  {
NimStringDesc* K;
NI V;
};
struct  rect160007  {
NI X;
NI Y;
NI W;
NI H;
TY160020* D;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef rect160007 TY176128[1];
typedef dataentry160005 TY176111[1];
struct  tcell44733  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44749  {
NI Len;
NI Cap;
tcell44733** D;
};
struct  tcellset44745  {
NI Counter;
NI Max;
tpagedesc44741* Head;
tpagedesc44741** Data;
};
typedef tsmallchunk26240* TY27022[512];
typedef ttrunk26213* ttrunkbuckets26215[256];
struct  tintset26217  {
ttrunkbuckets26215 Data;
};
struct  tmemregion27010  {
NI Minlargeobj;
NI Maxlargeobj;
TY27022 Freesmallchunks;
tllchunk27004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26242* Freechunkslist;
tintset26217 Chunkstarts;
tavlnode27008* Root;
tavlnode27008* Deleted;
tavlnode27008* Last;
tavlnode27008* Freeavlnodes;
};
struct  tgcstat46814  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap46816  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44749 Zct;
tcellseq44749 Decstack;
tcellset44745 Cycleroots;
tcellseq44749 Tempstack;
NI Recgclock;
tmemregion27010 Region;
tgcstat46814 Stat;
};
struct  assetHEX3Aobjecttype160027  {
assetHEX3Aobjecttype160027* P;
NI I;
assetgroupHEX3Aobjecttype160022* G;
TY160031* R;
};
struct  assetrectview160642  {
assetHEX3Aobjecttype160027* A;
NI I;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (rect160007* r, void* ClEnv);
void* ClEnv;
} assetrectfilter160640;
typedef N_CLOSURE_PTR(NIM_BOOL, TMP172) (rect160007* r, void* ClEnv);
typedef NI TY161833[4];
typedef rect160007 TY176971[4];
typedef NI TY177004[2];
typedef assetHEX3Aobjecttype160027* TY177299[2];
struct  packmanifestHEX3Aobjecttype163045  {
TY176050* Pack;
TY176050* Remainder;
};
struct  TY178163  {
NI HEX3Astate;
rendererptrHEX3Aobjecttype143572* Renr177734;
NU32 Alpha177730;
NI Demo178059;
surface143709* Surftiles32177725;
surface143709* Surftiles16177726;
surface143709* Surftiles8177727;
surface143709* Surftiles162177728;
};
typedef N_CDECL_PTR(NI32, TY152673) (int flags);
typedef N_CDECL_PTR(windowptrHEX3Aobjecttype143571*, TY153578) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef NU8 TY143346[52];
struct  event143161  {
NI32 Kind;
TY143346 Padding;
};
typedef N_CDECL_PTR(rendererptrHEX3Aobjecttype143572*, TY152749) (windowptrHEX3Aobjecttype143571* window, int index, int flags);
struct  TY178166  {
NI HEX3Astate;
TY178163* HEX3Aup178203;
};
struct  TY178169  {
NI HEX3Astate;
TY178166* HEX3Aup178200;
};
typedef N_CDECL_PTR(NI32, TY154017) (event143161* event);
typedef N_CDECL_PTR(NU32, TY153658) (void);
struct  TY178178  {
NI HEX3Astate;
TY178169* HEX3Aup178195;
};
struct  assetgroupHEX3Aobjecttype160022  {
rect160007 Rect;
NimStringDesc* Name;
NI Counter;
NI Id;
};
typedef N_CDECL_PTR(NI32, TY152433) (rendererptrHEX3Aobjecttype143572* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, TY153061) (rendererptrHEX3Aobjecttype143572* renderer);
typedef N_CDECL_PTR(void, TY153126) (surface143709* surface);
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (assetgroupHEX3Aobjecttype160022* g, NI count, NI basex, NI basey, NI randomx, NI randomy, void* ClEnv);
void* ClEnv;
} TY177736;
typedef N_CLOSURE_PTR(void, TMP219) (assetgroupHEX3Aobjecttype160022* g, NI count, NI basex, NI basey, NI randomx, NI randomy);
typedef N_CLOSURE_PTR(void, TMP220) (assetgroupHEX3Aobjecttype160022* g, NI count, NI basex, NI basey, NI randomx, NI randomy);
typedef N_CLOSURE_PTR(void, TMP221) (assetgroupHEX3Aobjecttype160022* g, NI count, NI basex, NI basey, NI randomx, NI randomy);
typedef assetHEX3Aobjecttype160027* TY177913[1];
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (assetgroupHEX3Aobjecttype160022* g, void* ClEnv);
void* ClEnv;
} TY177870;
typedef N_CLOSURE_PTR(void, TMP224) (assetgroupHEX3Aobjecttype160022* g);
struct rect143271 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  surface143709  {
NU32 Flags;
pixelformat143703* Format;
NI32 W;
NI32 H;
NI32 Pitch;
void* Pixels;
void* Userdata;
NI32 Locked;
void* Lockdata;
rect143271 Cliprect;
blitmapptrHEX3Aobjecttype143751* Map;
int Refcount;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (surface143709* isurf, NI tw, NI th, void* ClEnv);
void* ClEnv;
} TY177941;
typedef N_CLOSURE_PTR(void, TMP228) (surface143709* isurf, NI tw, NI th);
typedef N_CLOSURE_PTR(void, TMP229) (surface143709* isurf, NI tw, NI th);
typedef N_CLOSURE_PTR(void, TMP230) (surface143709* isurf, NI tw, NI th);
typedef N_CLOSURE_PTR(void, TMP231) (surface143709* isurf, NI tw, NI th);
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} TY178061;
typedef N_CLOSURE_PTR(void, TMP232) (void);
typedef N_CDECL_PTR(void, TY153078) (rendererptrHEX3Aobjecttype143572* renderer);
typedef N_CDECL_PTR(void, TY153673) (NU32 ms);
typedef N_CDECL_PTR(void, TY153637) (windowptrHEX3Aobjecttype143571* window);
struct TY119058 {
NimStringDesc* Field0;
jsonnodeobj119042* Field1;
};
struct  jsonnodeobj119042  {
NU8 Kind;
union {
struct {NimStringDesc* Str;
} S1;
struct {NI64 Num;
} S2;
struct {NF Fnum;
} S3;
struct {NIM_BOOL Bval;
} S4;
struct {TY119057* Fields;
} S6;
struct {TY119062* Elems;
} S7;
} kindU;
};
typedef NI TY26220[16];
struct  tpagedesc44741  {
tpagedesc44741* Next;
NI Key;
TY26220 Bits;
};
struct  tbasechunk26238  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26240  {
  tbasechunk26238 Sup;
tsmallchunk26240* Next;
tsmallchunk26240* Prev;
tfreecell26230* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27004  {
NI Size;
NI Acc;
tllchunk27004* Next;
};
struct  tbigchunk26242  {
  tbasechunk26238 Sup;
tbigchunk26242* Next;
tbigchunk26242* Prev;
NI Align;
NF Data;
};
struct  ttrunk26213  {
ttrunk26213* Next;
NI Key;
TY26220 Bits;
};
typedef tavlnode27008* TY27014[2];
struct  tavlnode27008  {
TY27014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  rendererptrHEX3Aobjecttype143572  {
char dummy;
};
struct  windowptrHEX3Aobjecttype143571  {
char dummy;
};
typedef NU8 TY143733[2];
struct  pixelformat143703  {
NU32 Format;
palette143701* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY143733 Padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int Refcount;
pixelformat143703* Next;
};
struct  blitmapptrHEX3Aobjecttype143751  {
char dummy;
};
struct  cropresultHEX3Aobjecttype160033  {
NI Left;
NI Right;
NI Top;
NI Bottom;
};
struct  tfreecell26230  {
tfreecell26230* Next;
NI Zerofield;
};
struct  palette143701  {
int Ncolors;
color143699* Colors;
NU32 Version;
int Refcount;
};
struct color143699 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
struct TY160020 {
  TGenericSeq Sup;
  dataentry160005 data[SEQ_DECL_SIZE];
};
struct TY176050 {
  TGenericSeq Sup;
  assetHEX3Aobjecttype160027* data[SEQ_DECL_SIZE];
};
struct TY160031 {
  TGenericSeq Sup;
  rect160007 data[SEQ_DECL_SIZE];
};
struct TY176329 {
  TGenericSeq Sup;
  assetrectview160642 data[SEQ_DECL_SIZE];
};
struct TY161494 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct TY161832 {
  TGenericSeq Sup;
  TY161833 data[SEQ_DECL_SIZE];
};
struct TY119057 {
  TGenericSeq Sup;
  TY119058 data[SEQ_DECL_SIZE];
};
struct TY119062 {
  TGenericSeq Sup;
  jsonnodeobj119042* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, test_176010)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(jsonnodeobj119042*, parsefile_124165)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, HEX24_123633)(jsonnodeobj119042* node);
N_NIMCALL(assetgroupHEX3Aobjecttype160022*, newassetgroup_176021)(NimStringDesc* name_176026, rect160007* rect_176028);
N_NIMCALL(void, newrect_160904)(NI x, NI y, NI w, NI h, TY160020* d, rect160007* Result);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP148)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(assetHEX3Aobjecttype160027*, newasset_160044)(NI i, assetgroupHEX3Aobjecttype160022* g, TY160031* r);
N_NIMCALL(void, newdata_161150)(NimStringDesc* k, NI v, dataentry160005* Result);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell44733*, usrtocell_48446)(void* usr);
static N_INLINE(void, rtladdzct_50004)(tcell44733* c);
N_NOINLINE(void, addzct_48417)(tcellseq44749* s, tcell44733* c);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_50825)(tcell44733* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48467)(tcell44733* c);
static N_INLINE(void, rtladdcycleroot_49229)(tcell44733* c);
N_NOINLINE(void, incl_45471)(tcellset44745* s, tcell44733* cell);
static N_INLINE(void, decref_50404)(tcell44733* c);
N_NIMCALL(assetHEX3Aobjecttype160027*, copy_160074)(assetHEX3Aobjecttype160027* a);
N_NIMCALL(void, HEX5BHEX5DHEX3D_160972)(TY160020** s, NimStringDesc* k, NI v);
N_NIMCALL(NimStringDesc*, HEX24_176228)(TY176050* x_176234);
N_NIMCALL(NimStringDesc*, HEX24_176322)(TY176329* x_176328);
N_NIMCALL(TY176329*, viewassetrects_160650)(TY176050* ar, assetrectfilter160640 fn);
N_NIMCALL(NIM_BOOL, fn0_176302)(rect160007* r);
N_NIMCALL(TY160020*, HEX5BHEX5D_161069)(TY160020* s, NimStringDesc* k);
N_NIMCALL(void, add_160939)(TY160020** s, NimStringDesc* k, NI v);
N_NIMCALL(NimStringDesc*, HEX24_160264)(TY160020* x_160270);
N_NIMCALL(NimStringDesc*, HEX24_160465)(TY160031* x_160471);
N_NIMCALL(TY160031*, rhoriztiling_161161)(assetgroupHEX3Aobjecttype160022* g, NI tw, NI th, NI iw, NI ih, NI sx, NI sy);
N_NIMCALL(TY160031*, rwidths_161491)(assetgroupHEX3Aobjecttype160022* g, TY161494* widths, NI th, NIM_BOOL posiw, NI ih, NI sx, NI sy);
N_NIMCALL(TY160031*, rverttiling_161358)(assetgroupHEX3Aobjecttype160022* g, NI tw, NI th, NI iw, NI ih, NI sx, NI sy);
N_NIMCALL(TY160031*, rheights_161660)(assetgroupHEX3Aobjecttype160022* g, TY161494* heights, NI tw, NIM_BOOL posih, NI iw, NI sx, NI sy);
N_NIMCALL(TY176050*, assetsofrects_161829)(assetgroupHEX3Aobjecttype160022* g, TY161832* rects);
N_NIMCALL(TY176050*, assetsofrects_161936)(assetgroupHEX3Aobjecttype160022* g, TY161494* rects);
N_NIMCALL(TY176050*, assetsofrects_162040)(assetgroupHEX3Aobjecttype160022* g, TY160031* rects);
N_NIMCALL(void, reduce_162432)(TY160031** r, NI lt, NI tp, NI rt, NI bm);
N_NIMCALL(NimStringDesc*, HEX24_177020)(TY161494* x_177026);
N_NIMCALL(void, minsizeofassets_162141)(TY176050* assets, NI tw, NI th, TY177004* Result);
N_NIMCALL(TY176050*, packtorectstl_162745)(assetgroupHEX3Aobjecttype160022* g, TY176050* assets, TY160031* rects);
N_NIMCALL(TY176050*, packtorectsc_162825)(assetgroupHEX3Aobjecttype160022* g, TY176050* assets, TY160031* rects);
N_NIMCALL(TY176050*, packtorectsgrowc_162909)(assetgroupHEX3Aobjecttype160022* g, TY176050* assets, TY160031* rects);
N_NIMCALL(NIM_BOOL, aabb_177317)(NI x0_177328, NI y0_177330, NI w0_177332, NI h0_177334, NI x1_177336, NI y1_177338, NI w1_177340, NI h1_177342);
N_NIMCALL(NimStringDesc*, nimBoolToStr)(NIM_BOOL x);
N_NIMCALL(assetHEX3Aobjecttype160027*, newtestasset_177580)(assetgroupHEX3Aobjecttype160022* g_177588, NI x_177590, NI y_177592, NI w_177594, NI h_177596);
N_NIMCALL(NI, random_134023)(NI max);
N_NIMCALL(packmanifestHEX3Aobjecttype163045*, packscanline_163054)(assetgroupHEX3Aobjecttype160022* g, TY176050* assets, NI skipstride, NIM_BOOL speedy, NIM_BOOL sort);
N_NIMCALL(void, display_177720)(void);
N_NIMCALL(void, TMP201)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(surface143709*, loadimage_173011)(NimStringDesc* filename);
N_NIMCALL(void, TMP212)(void* p, NI op);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, TMP214)(void* p, NI op);
N_NIMCALL(NIM_BOOL, tobool_143657)(NI32 some);
N_CLOSURE(void, rundemo_178060)(void* ClEnv);
N_NIMCALL(void, TMP216)(void* p, NI op);
N_CLOSURE(void, drawcopy_177735)(assetgroupHEX3Aobjecttype160022* g, NI count, NI basex, NI basey, NI randomx, NI randomy, void* ClEnv);
N_NIMCALL(surface143709*, newsurface_167426)(rect160007* rect);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_81204, TNimType* mt);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_165903)(TY176050* x_165909, TY176050* y_165914);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, drawcolors_167374)(surface143709* surf, TY176050* a0);
N_NIMCALL(void, doclear_177710)(rendererptrHEX3Aobjecttype143572* renr);
N_NIMCALL(void, copy_167519)(rendererptrHEX3Aobjecttype143572* renr, surface143709* src, rect143271* srcrect, rect160007* destrect);
static N_INLINE(void, destroy_154601)(surface143709* surface);
N_CLOSURE(void, drawcrops_177869)(assetgroupHEX3Aobjecttype160022* g, void* ClEnv);
N_NIMCALL(void, reduce_168371)(assetHEX3Aobjecttype160027* asset, surface143709* isurf, NU32 colorkey, NU8 cropt);
N_NIMCALL(void, drawrect_167134)(rendererptrHEX3Aobjecttype143572* renr, rect160007* r);
N_CLOSURE(void, drawimage_177940)(surface143709* isurf, NI tw, NI th, void* ClEnv);
N_NIMCALL(TY176050*, newseq_162259)(NI len_162263);
N_NIMCALL(void, reduce_162569)(TY160031** r, cropresultHEX3Aobjecttype160033* cropr);
N_NIMCALL(cropresultHEX3Aobjecttype160033*, crop_168061)(assetHEX3Aobjecttype160027* asset, surface143709* surf, NU32 colorkey, NU8 cropt);
N_NIMCALL(NIM_BOOL, isempty_168241)(rect160007* rect, surface143709* surf, NU32 colorkey);
N_NIMCALL(void, copy_167759)(surface143709* dest, surface143709* src, TY176050* a0);
N_NIMCALL(NimStringDesc*, HEX24_6201)(NU64 x);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdlInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdlDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdleasyInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdleasyDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, example1Init)(void);
NIM_EXTERNC N_NOINLINE(void, example1DatInit)(void);
STRING_LITERAL(TMP53, "test000.json", 12);
STRING_LITERAL(TMP144, "MyGroup", 7);
STRING_LITERAL(TMP149, "Radius", 6);
STRING_LITERAL(TMP150, "after", 5);
STRING_LITERAL(TMP173, "hello", 5);
STRING_LITERAL(TMP174, "mello", 5);
STRING_LITERAL(TMP175, "...", 3);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[4];
} CNSTSEQ178 = {{4, 4}, {128,
128,
128,
128}};
NIM_CONST TY161494* TMP176 = ((TY161494*)&CNSTSEQ178);
STRING_LITERAL(TMP178, "rects0:", 7);
NIM_CONST struct {
  TGenericSeq Sup;
  TY161833 data[4];
} CNSTSEQ181 = {{4, 4}, {{0,
0,
128,
128}
,
{128,
0,
128,
128}
,
{0,
128,
128,
128}
,
{128,
128,
128,
128}
}};
NIM_CONST TY161832* TMP179 = ((TY161832*)&CNSTSEQ181);
STRING_LITERAL(TMP181, "rects1:", 7);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[16];
} CNSTSEQ184 = {{16, 16}, {0,
0,
128,
128,
128,
0,
128,
128,
0,
128,
128,
128,
128,
128,
128,
128}};
NIM_CONST TY161494* TMP182 = ((TY161494*)&CNSTSEQ184);
STRING_LITERAL(TMP184, "rects2:", 7);
STRING_LITERAL(TMP207, "jerom-fantasy-tileset-32.png", 28);
STRING_LITERAL(TMP208, "jerom-fantasy-tileset-16.png", 28);
STRING_LITERAL(TMP209, "jerom-fantasy-tileset-8.png", 27);
STRING_LITERAL(TMP210, "joecreates-roguelikeitems-1.png", 31);
STRING_LITERAL(TMP217, "missed ", 7);
STRING_LITERAL(TMP218, " rects", 6);
STRING_LITERAL(TMP225, "Input", 5);
STRING_LITERAL(TMP226, "Output", 6);
STRING_LITERAL(TMP233, "frame ms: ", 10);
STRING_LITERAL(TMP234, " avg: ", 6);
extern TY157221 Dl_157220;
extern TNimType NTI160011; /* Asset */
TNimType NTI176050; /* seq[Asset] */
extern TNimType NTI160031; /* seq[Rect] */
extern TNimType NTI160020; /* seq[DataEntry] */
extern tgcheap46816 gch_46844;
extern TNimType NTI160007; /* Rect */
extern TNimType NTI161494; /* seq[int] */
TNimType NTI178163; /* object */
extern TNimType NTI159033; /* range -1..0(int) */
extern TNimType NTI143540; /* RendererPtr */
extern TNimType NTI124; /* uint32 */
extern TNimType NTI108; /* int */
extern TNimType NTI143707; /* SurfacePtr */
TNimType NTI178239; /* ref object */
extern TY152673 Dl_152672;
extern TY153578 Dl_153577;
extern TY152749 Dl_152748;
TNimType NTI178166; /* object */
TNimType NTI178237; /* ref object */
TNimType NTI178169; /* object */
TNimType NTI178235; /* ref object */
extern TY154017 Dl_154016;
extern TY153658 Dl_153657;
TNimType NTI178178; /* object */
TNimType NTI178233; /* ref object */
extern TY152433 Dl_152432;
extern TY153061 Dl_153060;
extern TY153126 Dl_153125;
extern TY153078 Dl_153077;
extern TY153673 Dl_153672;
extern TY153637 Dl_153636;
N_NIMCALL(void, TMP148)(void* p, NI op) {
	TY176050* a;
	NI LOC1;
	a = (TY176050*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(tcell44733*, usrtocell_48446)(void* usr) {
	tcell44733* result;
	result = 0;
	result = ((tcell44733*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44733))))));
	return result;
}

static N_INLINE(void, rtladdzct_50004)(tcell44733* c) {
	addzct_48417((&gch_46844.Zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell44733* c;
	c = usrtocell_48446(p);
	{
		(*c).Refcount -= 8;
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		rtladdzct_50004(c);
	}
	LA3: ;
}

static N_INLINE(NIM_BOOL, canbecycleroot_48467)(tcell44733* c) {
	NIM_BOOL result;
	result = 0;
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	return result;
}

static N_INLINE(void, rtladdcycleroot_49229)(tcell44733* c) {
	{
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		incl_45471((&gch_46844.Cycleroots), c);
	}
	LA3: ;
}

static N_INLINE(void, incref_50825)(tcell44733* c) {
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_48467(c);
		if (!LOC3) goto LA4;
		rtladdcycleroot_49229(c);
	}
	LA4: ;
}

static N_INLINE(void, decref_50404)(tcell44733* c) {
	{
		(*c).Refcount -= 8;
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		rtladdzct_50004(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = 0;
		LOC6 = canbecycleroot_48467(c);
		if (!LOC6) goto LA7;
		rtladdcycleroot_49229(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tcell44733* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = usrtocell_48446(src);
		incref_50825(LOC5);
	}
	LA3: ;
	{
		tcell44733* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = 0;
		LOC10 = usrtocell_48446((*dest));
		decref_50404(LOC10);
	}
	LA8: ;
	(*dest) = src;
}

N_NIMCALL(NIM_BOOL, fn0_176302)(rect160007* r) {
	NIM_BOOL result;
	TY160020* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = HEX5BHEX5D_161069((*r).D, ((NimStringDesc*) &TMP149));
	result = (0 < LOC1->Sup.len);
	return result;
}

N_NIMCALL(void, test_176010)(void) {
	assetgroupHEX3Aobjecttype160022* o;
	rect160007 LOC3;
	TY176050* pg0;
	TY176050* pg1;
	assetHEX3Aobjecttype160027* p0;
	TY160031* LOC4;
	TY176128 LOC5;
	TY160020* LOC6;
	TY176111 LOC7;
	NimStringDesc* LOC8;
	assetHEX3Aobjecttype160027* p1;
	TY160031* LOC9;
	TY176128 LOC10;
	TY160020* LOC11;
	TY176111 LOC12;
	NimStringDesc* LOC13;
	assetHEX3Aobjecttype160027* p2;
	NimStringDesc* LOC14;
	NimStringDesc* LOC15;
	assetrectfilter160640 LOC16;
	TY176329* LOC17;
	NimStringDesc* LOC18;
	TY160020* ts;
	NimStringDesc* LOC19;
	NimStringDesc* LOC20;
	TY160020* LOC21;
	NimStringDesc* LOC22;
	NimStringDesc* LOC23;
	TY160031* LOC24;
	NimStringDesc* LOC25;
	TY160031* LOC26;
	NimStringDesc* LOC27;
	TY160031* LOC28;
	NimStringDesc* LOC29;
	TY160031* LOC30;
	NimStringDesc* LOC31;
	TY160031* LOC32;
	NimStringDesc* LOC33;
	TY160031* LOC34;
	NimStringDesc* LOC35;
	TY160031* LOC36;
	NimStringDesc* LOC37;
	TY160031* LOC38;
	NimStringDesc* LOC39;
	TY176050* LOC40;
	NimStringDesc* LOC41;
	TY176050* LOC42;
	NimStringDesc* LOC43;
	TY160031* LOC44;
	TY176971 LOC45;
	TY176050* LOC46;
	NimStringDesc* LOC47;
	NimStringDesc* LOC48;
	TY161494* LOC49;
	TY177004 LOC50;
	NimStringDesc* LOC51;
	TY160031* LOC52;
	TY176050* LOC53;
	NimStringDesc* LOC54;
	TY160031* LOC55;
	TY176050* LOC56;
	NimStringDesc* LOC57;
	TY176050* m0;
	TY160031* LOC58;
	NimStringDesc* LOC59;
	TY176050* LOC60;
	TY177299 LOC61;
	NimStringDesc* LOC62;
	NIM_BOOL LOC63;
	NimStringDesc* LOC64;
	NIM_BOOL LOC65;
	NimStringDesc* LOC66;
	NIM_BOOL LOC67;
	NimStringDesc* LOC68;
	NIM_BOOL LOC69;
	NimStringDesc* LOC70;
	NIM_BOOL LOC71;
	NimStringDesc* LOC72;
	NIM_BOOL LOC73;
	NimStringDesc* LOC74;
	NIM_BOOL LOC75;
	NimStringDesc* LOC76;
	TY176050* pg2;
	packmanifestHEX3Aobjecttype163045* LOC83;
	NimStringDesc* LOC84;
	{
		NimStringDesc* filename;
		jsonnodeobj119042* jsona;
		NimStringDesc* LOC2;
		filename = copyString(((NimStringDesc*) &TMP53));
		jsona = parsefile_124165(filename);
		LOC2 = 0;
		LOC2 = HEX24_123633(jsona);
		printf("%s\015\012", (LOC2)->data);
	}
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	newrect_160904(0, 0, 256, 256, NIM_NIL, (&LOC3));
	o = newassetgroup_176021(((NimStringDesc*) &TMP144), (&LOC3));
	pg0 = (TY176050*) newSeq((&NTI176050), 0);
	pg1 = (TY176050*) newSeq((&NTI176050), 0);
	LOC4 = 0;
	LOC4 = (TY160031*) newSeq((&NTI160031), 1);
	memset((void*)LOC5, 0, sizeof(LOC5));
	LOC6 = 0;
	LOC6 = (TY160020*) newSeq((&NTI160020), 1);
	memset((void*)LOC7, 0, sizeof(LOC7));
	newdata_161150(((NimStringDesc*) &TMP149), 10, (&LOC7[0]));
	LOC8 = 0;
	LOC8 = LOC6->data[0].K; LOC6->data[0].K = copyStringRC1(LOC7[0].K);
	if (LOC8) nimGCunrefNoCycle(LOC8);
	LOC6->data[0].V = LOC7[0].V;
	newrect_160904(0, 0, 8, 8, LOC6, (&LOC5[0]));
	genericAssign((void*)(&LOC4->data[0]), (void*)(&LOC5[0]), (&NTI160007));
	p0 = newasset_160044(0, o, LOC4);
	pg0 = (TY176050*) incrSeq(&(pg0)->Sup, sizeof(assetHEX3Aobjecttype160027*));
	asgnRef((void**) (&pg0->data[pg0->Sup.len-1]), p0);
	LOC9 = 0;
	LOC9 = (TY160031*) newSeq((&NTI160031), 1);
	memset((void*)LOC10, 0, sizeof(LOC10));
	LOC11 = 0;
	LOC11 = (TY160020*) newSeq((&NTI160020), 1);
	memset((void*)LOC12, 0, sizeof(LOC12));
	newdata_161150(((NimStringDesc*) &TMP149), 60, (&LOC12[0]));
	LOC13 = 0;
	LOC13 = LOC11->data[0].K; LOC11->data[0].K = copyStringRC1(LOC12[0].K);
	if (LOC13) nimGCunrefNoCycle(LOC13);
	LOC11->data[0].V = LOC12[0].V;
	newrect_160904(0, 0, 8, 8, LOC11, (&LOC10[0]));
	genericAssign((void*)(&LOC9->data[0]), (void*)(&LOC10[0]), (&NTI160007));
	p1 = newasset_160044(1, o, LOC9);
	pg1 = (TY176050*) incrSeq(&(pg1)->Sup, sizeof(assetHEX3Aobjecttype160027*));
	asgnRef((void**) (&pg1->data[pg1->Sup.len-1]), p1);
	p2 = copy_160074(p0);
	pg1 = (TY176050*) incrSeq(&(pg1)->Sup, sizeof(assetHEX3Aobjecttype160027*));
	asgnRef((void**) (&pg1->data[pg1->Sup.len-1]), p2);
	HEX5BHEX5DHEX3D_160972((&(*p0).R->data[0].D), ((NimStringDesc*) &TMP150), 2);
	LOC14 = 0;
	LOC14 = HEX24_176228(pg0);
	printf("%s\015\012", (LOC14)->data);
	LOC15 = 0;
	LOC15 = HEX24_176228(pg1);
	printf("%s\015\012", (LOC15)->data);
	memset((void*)(&LOC16), 0, sizeof(LOC16));
	LOC16.ClPrc = ((TMP172) (fn0_176302)); LOC16.ClEnv = NIM_NIL;
	LOC17 = 0;
	LOC17 = viewassetrects_160650(pg1, LOC16);
	LOC18 = 0;
	LOC18 = HEX24_176322(LOC17);
	printf("%s\015\012", (LOC18)->data);
	ts = (TY160020*) newSeq((&NTI160020), 0);
	add_160939((&ts), ((NimStringDesc*) &TMP173), 1);
	add_160939((&ts), ((NimStringDesc*) &TMP174), 2);
	LOC19 = 0;
	LOC19 = HEX24_160264(ts);
	printf("%s\015\012", (LOC19)->data);
	add_160939((&ts), ((NimStringDesc*) &TMP173), 3);
	LOC20 = 0;
	LOC20 = HEX24_160264(ts);
	printf("%s\015\012", (LOC20)->data);
	LOC21 = 0;
	LOC21 = HEX5BHEX5D_161069(ts, ((NimStringDesc*) &TMP173));
	LOC22 = 0;
	LOC22 = HEX24_160264(LOC21);
	printf("%s\015\012", (LOC22)->data);
	HEX5BHEX5DHEX3D_160972((&ts), ((NimStringDesc*) &TMP174), 4);
	LOC23 = 0;
	LOC23 = HEX24_160264(ts);
	printf("%s\015\012", (LOC23)->data);
	LOC24 = 0;
	LOC24 = rhoriztiling_161161(o, 128, 128, 0, 0, 0, 0);
	LOC25 = 0;
	LOC25 = HEX24_160465(LOC24);
	printf("%s\015\012", (LOC25)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP175))->data);
	LOC26 = 0;
	LOC26 = rhoriztiling_161161(o, 128, 128, -128, -128, 128, 128);
	LOC27 = 0;
	LOC27 = HEX24_160465(LOC26);
	printf("%s\015\012", (LOC27)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP175))->data);
	LOC28 = 0;
	LOC28 = rwidths_161491(o, TMP176, 128, NIM_TRUE, 0, 0, 0);
	LOC29 = 0;
	LOC29 = HEX24_160465(LOC28);
	printf("%s\015\012", (LOC29)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP175))->data);
	LOC30 = 0;
	LOC30 = rwidths_161491(o, TMP176, 128, NIM_FALSE, -128, 128, 128);
	LOC31 = 0;
	LOC31 = HEX24_160465(LOC30);
	printf("%s\015\012", (LOC31)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP175))->data);
	LOC32 = 0;
	LOC32 = rverttiling_161358(o, 128, 128, 0, 0, 0, 0);
	LOC33 = 0;
	LOC33 = HEX24_160465(LOC32);
	printf("%s\015\012", (LOC33)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP175))->data);
	LOC34 = 0;
	LOC34 = rverttiling_161358(o, 128, 128, -128, -128, 128, 128);
	LOC35 = 0;
	LOC35 = HEX24_160465(LOC34);
	printf("%s\015\012", (LOC35)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP175))->data);
	LOC36 = 0;
	LOC36 = rheights_161660(o, TMP176, 128, NIM_TRUE, 0, 0, 0);
	LOC37 = 0;
	LOC37 = HEX24_160465(LOC36);
	printf("%s\015\012", (LOC37)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP175))->data);
	LOC38 = 0;
	LOC38 = rheights_161660(o, TMP176, 128, NIM_FALSE, -128, 128, 128);
	LOC39 = 0;
	LOC39 = HEX24_160465(LOC38);
	printf("%s\015\012", (LOC39)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP178))->data);
	LOC40 = 0;
	LOC40 = assetsofrects_161829(o, TMP179);
	LOC41 = 0;
	LOC41 = HEX24_176228(LOC40);
	printf("%s\015\012", (LOC41)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP181))->data);
	LOC42 = 0;
	LOC42 = assetsofrects_161936(o, TMP182);
	LOC43 = 0;
	LOC43 = HEX24_176228(LOC42);
	printf("%s\015\012", (LOC43)->data);
	printf("%s\015\012", (((NimStringDesc*) &TMP184))->data);
	LOC44 = 0;
	LOC44 = (TY160031*) newSeq((&NTI160031), 4);
	memset((void*)LOC45, 0, sizeof(LOC45));
	newrect_160904(0, 0, 128, 128, NIM_NIL, (&LOC45[0]));
	newrect_160904(128, 0, 128, 128, NIM_NIL, (&LOC45[1]));
	newrect_160904(0, 128, 128, 128, NIM_NIL, (&LOC45[2]));
	newrect_160904(128, 128, 128, 128, NIM_NIL, (&LOC45[3]));
	genericAssign((void*)(&LOC44->data[0]), (void*)(&LOC45[0]), (&NTI160007));
	genericAssign((void*)(&LOC44->data[1]), (void*)(&LOC45[1]), (&NTI160007));
	genericAssign((void*)(&LOC44->data[2]), (void*)(&LOC45[2]), (&NTI160007));
	genericAssign((void*)(&LOC44->data[3]), (void*)(&LOC45[3]), (&NTI160007));
	LOC46 = 0;
	LOC46 = assetsofrects_162040(o, LOC44);
	LOC47 = 0;
	LOC47 = HEX24_176228(LOC46);
	printf("%s\015\012", (LOC47)->data);
	reduce_162432((&(*p0).R), 2, 2, 2, 2);
	LOC48 = 0;
	LOC48 = HEX24_160465((*p0).R);
	printf("%s\015\012", (LOC48)->data);
	LOC49 = 0;
	LOC49 = (TY161494*) newSeq((&NTI161494), 2);
	memset((void*)LOC50, 0, sizeof(LOC50));
	minsizeofassets_162141(pg1, 10, 0, LOC50);
	LOC49->data[0] = LOC50[0];
	LOC49->data[1] = LOC50[1];
	LOC51 = 0;
	LOC51 = HEX24_177020(LOC49);
	printf("%s\015\012", (LOC51)->data);
	LOC52 = 0;
	LOC52 = rhoriztiling_161161(o, 16, 16, 0, 0, 0, 0);
	LOC53 = 0;
	LOC53 = packtorectstl_162745(o, pg1, LOC52);
	LOC54 = 0;
	LOC54 = HEX24_176228(LOC53);
	printf("%s\015\012", (LOC54)->data);
	LOC55 = 0;
	LOC55 = rhoriztiling_161161(o, 16, 16, 0, 0, 0, 0);
	LOC56 = 0;
	LOC56 = packtorectsc_162825(o, pg1, LOC55);
	LOC57 = 0;
	LOC57 = HEX24_176228(LOC56);
	printf("%s\015\012", (LOC57)->data);
	LOC58 = 0;
	LOC58 = rhoriztiling_161161(o, 16, 16, 0, 0, 0, 0);
	m0 = packtorectsgrowc_162909(o, pg1, LOC58);
	LOC59 = 0;
	LOC59 = HEX24_176228(m0);
	printf("%s\015\012", (LOC59)->data);
	LOC60 = 0;
	LOC60 = (TY176050*) newSeq((&NTI176050), 2);
	memset((void*)LOC61, 0, sizeof(LOC61));
	LOC61[0] = (*m0->data[0]).P;
	LOC61[1] = (*m0->data[1]).P;
	asgnRef((void**) (&LOC60->data[0]), LOC61[0]);
	asgnRef((void**) (&LOC60->data[1]), LOC61[1]);
	LOC62 = 0;
	LOC62 = HEX24_176228(LOC60);
	printf("%s\015\012", (LOC62)->data);
	LOC63 = 0;
	LOC63 = aabb_177317(0, 0, 8, 8, 0, 0, 1, 1);
	LOC64 = 0;
	LOC64 = nimBoolToStr(LOC63);
	printf("%s\015\012", (LOC64)->data);
	LOC65 = 0;
	LOC65 = aabb_177317(0, 0, 8, 8, 9, 0, 1, 1);
	LOC66 = 0;
	LOC66 = nimBoolToStr(LOC65);
	printf("%s\015\012", (LOC66)->data);
	LOC67 = 0;
	LOC67 = aabb_177317(0, 0, 8, 8, -1, 0, 1, 1);
	LOC68 = 0;
	LOC68 = nimBoolToStr(LOC67);
	printf("%s\015\012", (LOC68)->data);
	LOC69 = 0;
	LOC69 = aabb_177317(0, 0, 8, 8, -2, 0, 1, 1);
	LOC70 = 0;
	LOC70 = nimBoolToStr(LOC69);
	printf("%s\015\012", (LOC70)->data);
	LOC71 = 0;
	LOC71 = aabb_177317(0, 0, 8, 8, 0, -1, 1, 1);
	LOC72 = 0;
	LOC72 = nimBoolToStr(LOC71);
	printf("%s\015\012", (LOC72)->data);
	LOC73 = 0;
	LOC73 = aabb_177317(0, 0, 8, 8, 0, -2, 1, 1);
	LOC74 = 0;
	LOC74 = nimBoolToStr(LOC73);
	printf("%s\015\012", (LOC74)->data);
	LOC75 = 0;
	LOC75 = aabb_177317(0, 0, 8, 8, 0, -9, 1, 1);
	LOC76 = 0;
	LOC76 = nimBoolToStr(LOC75);
	printf("%s\015\012", (LOC76)->data);
	pg2 = (TY176050*) newSeq((&NTI176050), 0);
	{
		NI i0_177576;
		NI res_177687;
		i0_177576 = 0;
		res_177687 = 0;
		{
			while (1) {
				NI LOC80;
				NI LOC81;
				assetHEX3Aobjecttype160027* LOC82;
				if (!(res_177687 <= 30)) goto LA79;
				i0_177576 = res_177687;
				LOC80 = 0;
				LOC80 = random_134023(50);
				LOC81 = 0;
				LOC81 = random_134023(50);
				LOC82 = 0;
				LOC82 = newtestasset_177580(o, 0, 0, (NI32)(5 + LOC80), (NI32)(5 + LOC81));
				pg2 = (TY176050*) incrSeq(&(pg2)->Sup, sizeof(assetHEX3Aobjecttype160027*));
				asgnRef((void**) (&pg2->data[pg2->Sup.len-1]), LOC82);
				res_177687 += 1;
			} LA79: ;
		}
	}
	LOC83 = 0;
	LOC83 = packscanline_163054(o, pg2, 1, NIM_FALSE, NIM_TRUE);
	LOC84 = 0;
	LOC84 = HEX24_176228((*LOC83).Pack);
	printf("%s\015\012", (LOC84)->data);
}
N_NIMCALL(void, TMP201)(void* p, NI op) {
	TY178163* a;
	a = (TY178163*)p;
}
N_NIMCALL(void, TMP212)(void* p, NI op) {
	TY178166* a;
	a = (TY178166*)p;
	nimGCvisit((void*)(*a).HEX3Aup178203, op);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tcell44733* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_48446(src);
		(*c).Refcount += 8;
	}
	LA3: ;
	{
		tcell44733* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_48446((*dest));
		{
			(*c).Refcount -= 8;
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			rtladdzct_50004(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}
N_NIMCALL(void, TMP214)(void* p, NI op) {
	TY178169* a;
	a = (TY178169*)p;
	nimGCvisit((void*)(*a).HEX3Aup178200, op);
}
N_NIMCALL(void, TMP216)(void* p, NI op) {
	TY178178* a;
	a = (TY178178*)p;
	nimGCvisit((void*)(*a).HEX3Aup178195, op);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(void, doclear_177710)(rendererptrHEX3Aobjecttype143572* renr) {
	NI LOC1;
	NI LOC2;
	NI LOC3;
	NI32 LOC4;
	int LOC5;
	LOC1 = 0;
	LOC1 = random_134023(64);
	LOC2 = 0;
	LOC2 = random_134023(64);
	LOC3 = 0;
	LOC3 = random_134023(64);
	LOC4 = 0;
	LOC4 = Dl_152432(renr, ((NU8) (LOC1)), ((NU8) (LOC2)), ((NU8) (LOC3)), ((NU8) 255));
	LOC5 = 0;
	LOC5 = Dl_153060(renr);
}

static N_INLINE(void, destroy_154601)(surface143709* surface) {
	Dl_153125(surface);
}

N_CLOSURE(void, drawcopy_177735)(assetgroupHEX3Aobjecttype160022* g, NI count, NI basex, NI basey, NI randomx, NI randomy, void* ClEnv) {
	TY178178* HEX3Aenvp_178193;
	surface143709* surf;
	TY176050* pg0;
	packmanifestHEX3Aobjecttype163045* manifest;
	HEX3Aenvp_178193 = (TY178178*) ClEnv;
	surf = newsurface_167426((&(*g).Rect));
	pg0 = (TY176050*) newSeq((&NTI176050), 0);
	{
		NI i0_177787;
		NI HEX3Atmp_177864;
		NI res_177867;
		i0_177787 = 0;
		HEX3Atmp_177864 = 0;
		HEX3Atmp_177864 = (count - 1);
		res_177867 = 0;
		{
			while (1) {
				NI w0;
				NI h0;
				assetHEX3Aobjecttype160027* LOC16;
				if (!(res_177867 <= HEX3Atmp_177864)) goto LA3;
				i0_177787 = res_177867;
				{
					NI LOC8;
					if (!(0 < randomx)) goto LA6;
					LOC8 = 0;
					LOC8 = random_134023(randomx);
					w0 = (NI32)(LOC8 + basex);
				}
				goto LA4;
				LA6: ;
				{
					w0 = basex;
				}
				LA4: ;
				{
					NI LOC14;
					if (!(0 < randomy)) goto LA12;
					LOC14 = 0;
					LOC14 = random_134023(randomy);
					h0 = (NI32)(LOC14 + basey);
				}
				goto LA10;
				LA12: ;
				{
					h0 = basey;
				}
				LA10: ;
				LOC16 = 0;
				LOC16 = newtestasset_177580(g, 0, 0, w0, h0);
				pg0 = (TY176050*) incrSeq(&(pg0)->Sup, sizeof(assetHEX3Aobjecttype160027*));
				asgnRef((void**) (&pg0->data[pg0->Sup.len-1]), LOC16);
				res_177867 += 1;
			} LA3: ;
		}
	}
	manifest = packscanline_163054(g, pg0, 1, NIM_FALSE, NIM_TRUE);
	genericSeqAssign((&pg0), (*manifest).Pack, (&NTI176050));
	{
		NIM_BOOL LOC19;
		NimStringDesc* LOC22;
		NimStringDesc* LOC23;
		LOC19 = 0;
		LOC19 = HEX3DHEX3D_165903((*manifest).Remainder, NIM_NIL);
		if (!!(LOC19)) goto LA20;
		LOC22 = 0;
		LOC23 = 0;
		LOC23 = nimIntToStr((*manifest).Remainder->Sup.len);
		LOC22 = rawNewString(LOC23->Sup.len + 13);
appendString(LOC22, ((NimStringDesc*) &TMP217));
appendString(LOC22, LOC23);
appendString(LOC22, ((NimStringDesc*) &TMP218));
		printf("%s\015\012", (LOC22)->data);
	}
	LA20: ;
	drawcolors_167374(surf, pg0);
	doclear_177710((*(*(*(*HEX3Aenvp_178193).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734);
	copy_167519((*(*(*(*HEX3Aenvp_178193).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734, surf, NIM_NIL, (&(*g).Rect));
	destroy_154601(surf);
}

N_CLOSURE(void, drawcrops_177869)(assetgroupHEX3Aobjecttype160022* g, void* ClEnv) {
	TY178178* HEX3Aenvp_178210;
	surface143709* surf;
	assetHEX3Aobjecttype160027* ta;
	NI LOC1;
	NI LOC2;
	NI LOC3;
	NI LOC4;
	TY176050* LOC5;
	TY177913 LOC6;
	assetHEX3Aobjecttype160027* a0;
	TY160031* LOC7;
	TY176128 LOC8;
	assetHEX3Aobjecttype160027* sml;
	assetHEX3Aobjecttype160027* aspr;
	NI32 LOC9;
	NI32 LOC10;
	HEX3Aenvp_178210 = (TY178178*) ClEnv;
	surf = newsurface_167426((&(*g).Rect));
	LOC1 = 0;
	LOC1 = random_134023(128);
	LOC2 = 0;
	LOC2 = random_134023(128);
	LOC3 = 0;
	LOC3 = random_134023(128);
	LOC4 = 0;
	LOC4 = random_134023(128);
	ta = newtestasset_177580(g, LOC1, LOC2, LOC3, LOC4);
	LOC5 = 0;
	LOC5 = (TY176050*) newSeq((&NTI176050), 1);
	memset((void*)LOC6, 0, sizeof(LOC6));
	LOC6[0] = ta;
	asgnRef((void**) (&LOC5->data[0]), LOC6[0]);
	drawcolors_167374(surf, LOC5);
	LOC7 = 0;
	LOC7 = (TY160031*) newSeq((&NTI160031), 1);
	memset((void*)LOC8, 0, sizeof(LOC8));
	genericAssign((void*)(&LOC8[0]), (void*)(&(*g).Rect), (&NTI160007));
	genericAssign((void*)(&LOC7->data[0]), (void*)(&LOC8[0]), (&NTI160007));
	a0 = newasset_160044(0, g, LOC7);
	doclear_177710((*(*(*(*HEX3Aenvp_178210).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734);
	copy_167519((*(*(*(*HEX3Aenvp_178210).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734, surf, NIM_NIL, (&(*g).Rect));
	sml = copy_160074(a0);
	reduce_168371(sml, surf, (*(*(*(*HEX3Aenvp_178210).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Alpha177730, ((NU8) 0));
	aspr = copy_160074(a0);
	reduce_168371(aspr, surf, (*(*(*(*HEX3Aenvp_178210).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Alpha177730, ((NU8) 1));
	LOC9 = 0;
	LOC9 = Dl_152432((*(*(*(*HEX3Aenvp_178210).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	drawrect_167134((*(*(*(*HEX3Aenvp_178210).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734, (&(*sml).R->data[0]));
	LOC10 = 0;
	LOC10 = Dl_152432((*(*(*(*HEX3Aenvp_178210).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734, ((NU8) 0), ((NU8) 255), ((NU8) 0), ((NU8) 255));
	drawrect_167134((*(*(*(*HEX3Aenvp_178210).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734, (&(*aspr).R->data[0]));
	destroy_154601(surf);
}

N_CLOSURE(void, drawimage_177940)(surface143709* isurf, NI tw, NI th, void* ClEnv) {
	TY178178* HEX3Aenvp_178225;
	assetgroupHEX3Aobjecttype160022* ig;
	rect160007 LOC1;
	assetgroupHEX3Aobjecttype160022* og;
	rect160007 LOC2;
	surface143709* osurf;
	TY160031* r0;
	TY176050* a1;
	TY176050* a2;
	packmanifestHEX3Aobjecttype163045* LOC14;
	HEX3Aenvp_178225 = (TY178178*) ClEnv;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	newrect_160904(0, 0, ((NI) ((*isurf).W)), ((NI) ((*isurf).H)), NIM_NIL, (&LOC1));
	ig = newassetgroup_176021(((NimStringDesc*) &TMP225), (&LOC1));
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	newrect_160904(0, 0, ((NI) ((*isurf).W)), ((NI) ((*isurf).H)), NIM_NIL, (&LOC2));
	og = newassetgroup_176021(((NimStringDesc*) &TMP226), (&LOC2));
	doclear_177710((*(*(*(*HEX3Aenvp_178225).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734);
	osurf = newsurface_167426((&(*og).Rect));
	r0 = rhoriztiling_161161(ig, tw, th, 0, 0, 0, 0);
	a1 = newseq_162259(0);
	{
		NI n0_178011;
		NI HEX3Atmp_178053;
		NI res_178056;
		n0_178011 = 0;
		HEX3Atmp_178053 = 0;
		HEX3Atmp_178053 = (r0->Sup.len-1);
		res_178056 = 0;
		{
			while (1) {
				assetHEX3Aobjecttype160027* asset;
				TY160031* LOC6;
				TY176128 LOC7;
				assetHEX3Aobjecttype160027* c;
				cropresultHEX3Aobjecttype160033* LOC8;
				if (!(res_178056 <= HEX3Atmp_178053)) goto LA5;
				n0_178011 = res_178056;
				LOC6 = 0;
				LOC6 = (TY160031*) newSeq((&NTI160031), 1);
				memset((void*)LOC7, 0, sizeof(LOC7));
				genericAssign((void*)(&LOC7[0]), (void*)(&r0->data[n0_178011]), (&NTI160007));
				genericAssign((void*)(&LOC6->data[0]), (void*)(&LOC7[0]), (&NTI160007));
				asset = newasset_160044(n0_178011, ig, LOC6);
				c = copy_160074(asset);
				asgnRefNoCycle((void**) (&(*c).G), og);
				LOC8 = 0;
				LOC8 = crop_168061(c, isurf, (*(*(*(*HEX3Aenvp_178225).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Alpha177730, ((NU8) 0));
				reduce_162569((&(*c).R), LOC8);
				{
					NIM_BOOL LOC11;
					LOC11 = 0;
					LOC11 = isempty_168241((&(*c).R->data[0]), isurf, (*(*(*(*HEX3Aenvp_178225).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Alpha177730);
					if (!!(LOC11)) goto LA12;
					a1 = (TY176050*) incrSeq(&(a1)->Sup, sizeof(assetHEX3Aobjecttype160027*));
					asgnRef((void**) (&a1->data[a1->Sup.len-1]), c);
				}
				LA12: ;
				res_178056 += 1;
			} LA5: ;
		}
	}
	LOC14 = 0;
	LOC14 = packscanline_163054(og, a1, 1, NIM_FALSE, NIM_TRUE);
	genericSeqAssign((&a2), (*LOC14).Pack, (&NTI176050));
	copy_167759(osurf, isurf, a2);
	copy_167519((*(*(*(*HEX3Aenvp_178225).HEX3Aup178195).HEX3Aup178200).HEX3Aup178203).Renr177734, osurf, NIM_NIL, (&(*og).Rect));
}

N_CLOSURE(void, rundemo_178060)(void* ClEnv) {
	TY178169* HEX3Aenvp_178198;
	TY178178* HEX3Aenv_178232;
	HEX3Aenvp_178198 = (TY178169*) ClEnv;
	HEX3Aenv_178232 = 0;
	HEX3Aenv_178232 = (TY178178*) newObj((&NTI178233), sizeof(TY178178));
	asgnRefNoCycle((void**) (&(*HEX3Aenv_178232).HEX3Aup178195), HEX3Aenvp_178198);
	{
		TY177736 LOC5;
		rect160007 LOC6;
		assetgroupHEX3Aobjecttype160022* LOC7;
		if (!((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Demo178059 == 0)) goto LA3;
		memset((void*)(&LOC5), 0, sizeof(LOC5));
		LOC5.ClPrc = drawcopy_177735; LOC5.ClEnv = HEX3Aenv_178232;
		memset((void*)(&LOC6), 0, sizeof(LOC6));
		newrect_160904(0, 0, 256, 256, NIM_NIL, (&LOC6));
		LOC7 = 0;
		LOC7 = newassetgroup_176021(((NimStringDesc*) &TMP144), (&LOC6));
		LOC5.ClEnv? LOC5.ClPrc(LOC7, 150, 4, 4, 30, 30, LOC5.ClEnv):((TMP219)(LOC5.ClPrc))(LOC7, 150, 4, 4, 30, 30);
	}
	goto LA1;
	LA3: ;
	{
		TY177736 LOC11;
		rect160007 LOC12;
		assetgroupHEX3Aobjecttype160022* LOC13;
		if (!((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Demo178059 == 1)) goto LA9;
		memset((void*)(&LOC11), 0, sizeof(LOC11));
		LOC11.ClPrc = drawcopy_177735; LOC11.ClEnv = HEX3Aenv_178232;
		memset((void*)(&LOC12), 0, sizeof(LOC12));
		newrect_160904(0, 0, 512, 512, NIM_NIL, (&LOC12));
		LOC13 = 0;
		LOC13 = newassetgroup_176021(((NimStringDesc*) &TMP144), (&LOC12));
		LOC11.ClEnv? LOC11.ClPrc(LOC13, 600, 4, 4, 30, 30, LOC11.ClEnv):((TMP220)(LOC11.ClPrc))(LOC13, 600, 4, 4, 30, 30);
	}
	goto LA1;
	LA9: ;
	{
		TY177736 LOC17;
		rect160007 LOC18;
		assetgroupHEX3Aobjecttype160022* LOC19;
		if (!((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Demo178059 == 2)) goto LA15;
		memset((void*)(&LOC17), 0, sizeof(LOC17));
		LOC17.ClPrc = drawcopy_177735; LOC17.ClEnv = HEX3Aenv_178232;
		memset((void*)(&LOC18), 0, sizeof(LOC18));
		newrect_160904(0, 0, 512, 512, NIM_NIL, (&LOC18));
		LOC19 = 0;
		LOC19 = newassetgroup_176021(((NimStringDesc*) &TMP144), (&LOC18));
		LOC17.ClEnv? LOC17.ClPrc(LOC19, 1024, 16, 16, 0, 0, LOC17.ClEnv):((TMP221)(LOC17.ClPrc))(LOC19, 1024, 16, 16, 0, 0);
	}
	goto LA1;
	LA15: ;
	{
		TY177870 LOC23;
		rect160007 LOC24;
		assetgroupHEX3Aobjecttype160022* LOC25;
		if (!((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Demo178059 == 3)) goto LA21;
		memset((void*)(&LOC23), 0, sizeof(LOC23));
		LOC23.ClPrc = drawcrops_177869; LOC23.ClEnv = HEX3Aenv_178232;
		memset((void*)(&LOC24), 0, sizeof(LOC24));
		newrect_160904(0, 0, 256, 256, NIM_NIL, (&LOC24));
		LOC25 = 0;
		LOC25 = newassetgroup_176021(((NimStringDesc*) &TMP144), (&LOC24));
		LOC23.ClEnv? LOC23.ClPrc(LOC25, LOC23.ClEnv):((TMP224)(LOC23.ClPrc))(LOC25);
	}
	goto LA1;
	LA21: ;
	{
		TY177941 LOC29;
		if (!((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Demo178059 == 4)) goto LA27;
		memset((void*)(&LOC29), 0, sizeof(LOC29));
		LOC29.ClPrc = drawimage_177940; LOC29.ClEnv = HEX3Aenv_178232;
		LOC29.ClEnv? LOC29.ClPrc((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Surftiles32177725, 32, 32, LOC29.ClEnv):((TMP228)(LOC29.ClPrc))((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Surftiles32177725, 32, 32);
	}
	goto LA1;
	LA27: ;
	{
		TY177941 LOC33;
		if (!((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Demo178059 == 5)) goto LA31;
		memset((void*)(&LOC33), 0, sizeof(LOC33));
		LOC33.ClPrc = drawimage_177940; LOC33.ClEnv = HEX3Aenv_178232;
		LOC33.ClEnv? LOC33.ClPrc((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Surftiles16177726, 16, 16, LOC33.ClEnv):((TMP229)(LOC33.ClPrc))((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Surftiles16177726, 16, 16);
	}
	goto LA1;
	LA31: ;
	{
		TY177941 LOC37;
		if (!((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Demo178059 == 6)) goto LA35;
		memset((void*)(&LOC37), 0, sizeof(LOC37));
		LOC37.ClPrc = drawimage_177940; LOC37.ClEnv = HEX3Aenv_178232;
		LOC37.ClEnv? LOC37.ClPrc((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Surftiles8177727, 8, 8, LOC37.ClEnv):((TMP230)(LOC37.ClPrc))((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Surftiles8177727, 8, 8);
	}
	goto LA1;
	LA35: ;
	{
		TY177941 LOC41;
		if (!((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Demo178059 == 7)) goto LA39;
		memset((void*)(&LOC41), 0, sizeof(LOC41));
		LOC41.ClPrc = drawimage_177940; LOC41.ClEnv = HEX3Aenv_178232;
		LOC41.ClEnv? LOC41.ClPrc((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Surftiles162177728, 16, 16, LOC41.ClEnv):((TMP231)(LOC41.ClPrc))((*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Surftiles162177728, 16, 16);
	}
	goto LA1;
	LA39: ;
	{
		(*(*(*HEX3Aenvp_178198).HEX3Aup178200).HEX3Aup178203).Demo178059 = 0;
	}
	LA1: ;
}

N_NIMCALL(void, display_177720)(void) {
	TY178163* HEX3Aenv_178238;
	NI32 LOC1;
	windowptrHEX3Aobjecttype143571* wiow;
	event143161 evnt;
	NIM_BOOL done;
	NF tt;
	HEX3Aenv_178238 = 0;
	HEX3Aenv_178238 = (TY178163*) newObj((&NTI178239), sizeof(TY178163));
	LOC1 = 0;
	LOC1 = Dl_152672(((int) 65535));
	wiow = Dl_153577("Sprite Sheets!", ((int) 805240832), ((int) 805240832), ((int) 640), ((int) 480), ((int) 4));
	(*HEX3Aenv_178238).Surftiles32177725 = loadimage_173011(((NimStringDesc*) &TMP207));
	(*HEX3Aenv_178238).Surftiles16177726 = loadimage_173011(((NimStringDesc*) &TMP208));
	(*HEX3Aenv_178238).Surftiles8177727 = loadimage_173011(((NimStringDesc*) &TMP209));
	(*HEX3Aenv_178238).Surftiles162177728 = loadimage_173011(((NimStringDesc*) &TMP210));
	(*HEX3Aenv_178238).Alpha177730 = ((NU32) 255);
	memset((void*)(&evnt), 0, sizeof(evnt));
	(*HEX3Aenv_178238).Renr177734 = Dl_152748(wiow, ((int) -1), ((int) 0));
	done = NIM_FALSE;
	(*HEX3Aenv_178238).Demo178059 = 0;
	tt = 0.0;
	{
		TY178166* HEX3Aenv_178236;
		HEX3Aenv_178236 = 0;
		HEX3Aenv_178236 = (TY178166*) newObj((&NTI178237), sizeof(TY178166));
		asgnRefNoCycle((void**) (&(*HEX3Aenv_178236).HEX3Aup178203), HEX3Aenv_178238);
		while (1) {
			TY178169* HEX3Aenv_178234;
			NU32 ct;
			TY178061 LOC16;
			NU32 lt;
			NimStringDesc* LOC17;
			NimStringDesc* LOC18;
			if (!!(done)) goto LA3;
			HEX3Aenv_178234 = 0;
			HEX3Aenv_178234 = (TY178169*) newObj((&NTI178235), sizeof(TY178169));
			asgnRefNoCycle((void**) (&(*HEX3Aenv_178234).HEX3Aup178200), HEX3Aenv_178236);
			{
				while (1) {
					NI32 LOC6;
					NIM_BOOL LOC7;
					LOC6 = 0;
					LOC6 = Dl_154016((&evnt));
					LOC7 = 0;
					LOC7 = tobool_143657(LOC6);
					if (!LOC7) goto LA5;
					{
						if (!(evnt.Kind == ((NI32) 256))) goto LA10;
						done = NIM_TRUE;
					}
					LA10: ;
					{
						if (!(evnt.Kind == ((NI32) 768))) goto LA14;
						(*HEX3Aenv_178238).Demo178059 = (NI32)((*HEX3Aenv_178238).Demo178059 + 1);
					}
					LA14: ;
				} LA5: ;
			}
			ct = Dl_153657();
			memset((void*)(&LOC16), 0, sizeof(LOC16));
			LOC16.ClPrc = rundemo_178060; LOC16.ClEnv = HEX3Aenv_178234;
			LOC16.ClEnv? LOC16.ClPrc(LOC16.ClEnv):((TMP232)(LOC16.ClPrc))();
			lt = Dl_153657();
			tt = ((NF)(((NF)(((NF) ((NU32)((NU32)(lt) - (NU32)(ct))))) * (NF)(1.0000000000000001e-001))) + (NF)(((NF)(tt) * (NF)(9.0000000000000002e-001))));
			LOC17 = 0;
			LOC17 = HEX24_6201(((NU64) ((NU32)((NU32)(lt) - (NU32)(ct)))));
			LOC18 = 0;
			LOC18 = nimFloatToStr(tt);
			printf("%s%s%s%s\015\012", (((NimStringDesc*) &TMP233))->data, (LOC17)->data, (((NimStringDesc*) &TMP234))->data, (LOC18)->data);
			Dl_153077((*HEX3Aenv_178238).Renr177734);
			Dl_153672(((NU32) 1));
		} LA3: ;
	}
	Dl_153636(wiow);
	exit(0);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_hashesDatInit();
	stdlib_streamsDatInit();
	stdlib_lexbaseDatInit();
	stdlib_unicodeDatInit();
	stdlib_jsonDatInit();
	stdlib_winleanDatInit();
	stdlib_timesDatInit();
	stdlib_mathDatInit();
	stdlib_macrosDatInit();
	stdlib_unsignedDatInit();
	sdl2_sdl2DatInit();
	sdl2_imageDatInit();
	stdlib_sequtilsDatInit();
	stdlib_algorithmDatInit();
	HEX00_packDatInit();
	HEX00_packsdlDatInit();
	stdlib_tablesDatInit();
	HEX00_packsdleasyDatInit();
	example1DatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_hashesInit();
	stdlib_streamsInit();
	stdlib_lexbaseInit();
	stdlib_unicodeInit();
	stdlib_jsonInit();
	stdlib_winleanInit();
	stdlib_timesInit();
	stdlib_mathInit();
	stdlib_macrosInit();
	stdlib_unsignedInit();
	sdl2_sdl2Init();
	sdl2_imageInit();
	stdlib_sequtilsInit();
	stdlib_algorithmInit();
	HEX00_packInit();
	HEX00_packsdlInit();
	stdlib_tablesInit();
	HEX00_packsdleasyInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	example1Init();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, example1Init)(void) {
	test_176010();
	display_177720();
}

NIM_EXTERNC N_NOINLINE(void, example1DatInit)(void) {
static TNimNode* TMP195[8];
static TNimNode* TMP211[2];
static TNimNode* TMP213[2];
static TNimNode* TMP215[2];
static TNimNode TMP3[18];
NTI176050.size = sizeof(TY176050*);
NTI176050.kind = 24;
NTI176050.base = (&NTI160011);
NTI176050.flags = 2;
NTI176050.marker = TMP148;
NTI178163.size = sizeof(TY178163);
NTI178163.kind = 18;
NTI178163.base = 0;
NTI178163.flags = 3;
TMP195[0] = &TMP3[1];
TMP3[1].kind = 1;
TMP3[1].offset = offsetof(TY178163, HEX3Astate);
TMP3[1].typ = (&NTI159033);
TMP3[1].name = ":state";
TMP195[1] = &TMP3[2];
TMP3[2].kind = 1;
TMP3[2].offset = offsetof(TY178163, Renr177734);
TMP3[2].typ = (&NTI143540);
TMP3[2].name = "renr177734";
TMP195[2] = &TMP3[3];
TMP3[3].kind = 1;
TMP3[3].offset = offsetof(TY178163, Alpha177730);
TMP3[3].typ = (&NTI124);
TMP3[3].name = "alpha177730";
TMP195[3] = &TMP3[4];
TMP3[4].kind = 1;
TMP3[4].offset = offsetof(TY178163, Demo178059);
TMP3[4].typ = (&NTI108);
TMP3[4].name = "demo178059";
TMP195[4] = &TMP3[5];
TMP3[5].kind = 1;
TMP3[5].offset = offsetof(TY178163, Surftiles32177725);
TMP3[5].typ = (&NTI143707);
TMP3[5].name = "surftiles32177725";
TMP195[5] = &TMP3[6];
TMP3[6].kind = 1;
TMP3[6].offset = offsetof(TY178163, Surftiles16177726);
TMP3[6].typ = (&NTI143707);
TMP3[6].name = "surftiles16177726";
TMP195[6] = &TMP3[7];
TMP3[7].kind = 1;
TMP3[7].offset = offsetof(TY178163, Surftiles8177727);
TMP3[7].typ = (&NTI143707);
TMP3[7].name = "surftiles8177727";
TMP195[7] = &TMP3[8];
TMP3[8].kind = 1;
TMP3[8].offset = offsetof(TY178163, Surftiles162177728);
TMP3[8].typ = (&NTI143707);
TMP3[8].name = "surftiles16_2177728";
TMP3[0].len = 8; TMP3[0].kind = 2; TMP3[0].sons = &TMP195[0];
NTI178163.node = &TMP3[0];
NTI178239.size = sizeof(TY178163*);
NTI178239.kind = 22;
NTI178239.base = (&NTI178163);
NTI178239.flags = 2;
NTI178239.marker = TMP201;
NTI178166.size = sizeof(TY178166);
NTI178166.kind = 18;
NTI178166.base = 0;
NTI178166.flags = 2;
TMP211[0] = &TMP3[10];
TMP3[10].kind = 1;
TMP3[10].offset = offsetof(TY178166, HEX3Astate);
TMP3[10].typ = (&NTI159033);
TMP3[10].name = ":state";
TMP211[1] = &TMP3[11];
TMP3[11].kind = 1;
TMP3[11].offset = offsetof(TY178166, HEX3Aup178203);
TMP3[11].typ = (&NTI178239);
TMP3[11].name = ":up178203";
TMP3[9].len = 2; TMP3[9].kind = 2; TMP3[9].sons = &TMP211[0];
NTI178166.node = &TMP3[9];
NTI178237.size = sizeof(TY178166*);
NTI178237.kind = 22;
NTI178237.base = (&NTI178166);
NTI178237.flags = 2;
NTI178237.marker = TMP212;
NTI178169.size = sizeof(TY178169);
NTI178169.kind = 18;
NTI178169.base = 0;
NTI178169.flags = 2;
TMP213[0] = &TMP3[13];
TMP3[13].kind = 1;
TMP3[13].offset = offsetof(TY178169, HEX3Astate);
TMP3[13].typ = (&NTI159033);
TMP3[13].name = ":state";
TMP213[1] = &TMP3[14];
TMP3[14].kind = 1;
TMP3[14].offset = offsetof(TY178169, HEX3Aup178200);
TMP3[14].typ = (&NTI178237);
TMP3[14].name = ":up178200";
TMP3[12].len = 2; TMP3[12].kind = 2; TMP3[12].sons = &TMP213[0];
NTI178169.node = &TMP3[12];
NTI178235.size = sizeof(TY178169*);
NTI178235.kind = 22;
NTI178235.base = (&NTI178169);
NTI178235.flags = 2;
NTI178235.marker = TMP214;
NTI178178.size = sizeof(TY178178);
NTI178178.kind = 18;
NTI178178.base = 0;
NTI178178.flags = 2;
TMP215[0] = &TMP3[16];
TMP3[16].kind = 1;
TMP3[16].offset = offsetof(TY178178, HEX3Astate);
TMP3[16].typ = (&NTI159033);
TMP3[16].name = ":state";
TMP215[1] = &TMP3[17];
TMP3[17].kind = 1;
TMP3[17].offset = offsetof(TY178178, HEX3Aup178195);
TMP3[17].typ = (&NTI178235);
TMP3[17].name = ":up178195";
TMP3[15].len = 2; TMP3[15].kind = 2; TMP3[15].sons = &TMP215[0];
NTI178178.node = &TMP3[15];
NTI178233.size = sizeof(TY178178*);
NTI178233.kind = 22;
NTI178233.base = (&NTI178178);
NTI178233.flags = 2;
NTI178233.marker = TMP216;
}

