/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\example2.o c:\dropbox\2015\nim\packer\example\nimcache\example2.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct surface132715 surface132715;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct assetgroupHEX3Aobjecttype149022 assetgroupHEX3Aobjecttype149022;
typedef struct rect149007 rect149007;
typedef struct TY149020 TY149020;
typedef struct dataentry149005 dataentry149005;
typedef struct pixelformat132709 pixelformat132709;
typedef struct rect132277 rect132277;
typedef struct blitmapptrHEX3Aobjecttype132757 blitmapptrHEX3Aobjecttype132757;
typedef struct tcell44933 tcell44933;
typedef struct TNimType TNimType;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct TY149663 TY149663;
typedef struct assetHEX3Aobjecttype149027 assetHEX3Aobjecttype149027;
typedef struct sheetbundleHEX3Aobjecttype167013 sheetbundleHEX3Aobjecttype167013;
typedef struct TY154808 TY154808;
typedef struct TY167016 TY167016;
typedef struct TY167018 TY167018;
typedef struct TNimNode TNimNode;
typedef struct orderedtable176685 orderedtable176685;
typedef struct orderedkeyvaluepairseq176688 orderedkeyvaluepairseq176688;
typedef struct orderedkeyvaluepair176691 orderedkeyvaluepair176691;
typedef struct bundletup176025 bundletup176025;
typedef struct TY176096 TY176096;
typedef struct palette132707 palette132707;
typedef struct jsonnodeobj119051 jsonnodeobj119051;
typedef struct assetjsonmanifest176679 assetjsonmanifest176679;
typedef struct orderedtable176715 orderedtable176715;
typedef struct orderedkeyvaluepairseq176718 orderedkeyvaluepairseq176718;
typedef struct orderedkeyvaluepair176721 orderedkeyvaluepair176721;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
typedef struct TY149048 TY149048;
typedef struct color132705 color132705;
typedef struct TY119066 TY119066;
typedef struct TY119067 TY119067;
typedef struct TY119071 TY119071;
typedef N_CDECL_PTR(int, TY146221) (int flags);
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  dataentry149005  {
NimStringDesc* K;
NI V;
};
struct  rect149007  {
NI X;
NI Y;
NI W;
NI H;
TY149020* D;
};
struct rect132277 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  surface132715  {
NU32 Flags;
pixelformat132709* Format;
NI32 W;
NI32 H;
NI32 Pitch;
void* Pixels;
void* Userdata;
NI32 Locked;
void* Lockdata;
rect132277 Cliprect;
blitmapptrHEX3Aobjecttype132757* Map;
int Refcount;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef TY149663* TY179244[3];
typedef assetgroupHEX3Aobjecttype149022* TY179262[3];
typedef surface132715* TY179280[3];
struct orderedkeyvaluepair176691 {
NU8 Field0;
NI Field1;
NI Field2;
assetHEX3Aobjecttype149027* Field3;
};
struct  orderedtable176685  {
orderedkeyvaluepairseq176688* Data;
NI Counter;
NI First;
NI Last;
};
struct bundletup176025 {
surface132715* Field0;
sheetbundleHEX3Aobjecttype167013* Field1;
};
typedef N_CDECL_PTR(NCSTRING, TY143112) (NU32 format);
typedef NU8 TY132739[2];
struct  pixelformat132709  {
NU32 Format;
palette132707* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY132739 Padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int Refcount;
pixelformat132709* Next;
};
struct orderedkeyvaluepair176721 {
NU8 Field0;
NI Field1;
NI Field2;
assetgroupHEX3Aobjecttype149022* Field3;
};
struct  orderedtable176715  {
orderedkeyvaluepairseq176718* Data;
NI Counter;
NI First;
NI Last;
};
struct assetjsonmanifest176679 {
orderedtable176685 Field0;
orderedtable176715 Field1;
jsonnodeobj119051* Field2;
};
struct  sheetbundleHEX3Aobjecttype167013  {
TY149663* Asset;
TY167016* Group;
TY167018* Surf;
};
struct  assetgroupHEX3Aobjecttype149022  {
rect149007 Rect;
NimStringDesc* Name;
NI Counter;
NI Id;
};
struct  blitmapptrHEX3Aobjecttype132757  {
char dummy;
};
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  assetHEX3Aobjecttype149027  {
assetHEX3Aobjecttype149027* P;
NI I;
assetgroupHEX3Aobjecttype149022* G;
TY149048* R;
};
struct  palette132707  {
int Ncolors;
color132705* Colors;
NU32 Version;
int Refcount;
};
struct TY119067 {
NimStringDesc* Field0;
jsonnodeobj119051* Field1;
};
struct  jsonnodeobj119051  {
NU8 Kind;
union {
struct {NimStringDesc* Str;
} S1;
struct {NI64 Num;
} S2;
struct {NF Fnum;
} S3;
struct {NIM_BOOL Bval;
} S4;
struct {TY119066* Fields;
} S6;
struct {TY119071* Elems;
} S7;
} kindU;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
struct color132705 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
struct TY149020 {
  TGenericSeq Sup;
  dataentry149005 data[SEQ_DECL_SIZE];
};
struct TY149663 {
  TGenericSeq Sup;
  assetHEX3Aobjecttype149027* data[SEQ_DECL_SIZE];
};
struct TY154808 {
  TGenericSeq Sup;
  TY149663* data[SEQ_DECL_SIZE];
};
struct TY167016 {
  TGenericSeq Sup;
  assetgroupHEX3Aobjecttype149022* data[SEQ_DECL_SIZE];
};
struct TY167018 {
  TGenericSeq Sup;
  surface132715* data[SEQ_DECL_SIZE];
};
struct orderedkeyvaluepairseq176688 {
  TGenericSeq Sup;
  orderedkeyvaluepair176691 data[SEQ_DECL_SIZE];
};
struct TY176096 {
  TGenericSeq Sup;
  bundletup176025 data[SEQ_DECL_SIZE];
};
struct orderedkeyvaluepairseq176718 {
  TGenericSeq Sup;
  orderedkeyvaluepair176721 data[SEQ_DECL_SIZE];
};
struct TY149048 {
  TGenericSeq Sup;
  rect149007 data[SEQ_DECL_SIZE];
};
struct TY119066 {
  TGenericSeq Sup;
  TY119067 data[SEQ_DECL_SIZE];
};
struct TY119071 {
  TGenericSeq Sup;
  jsonnodeobj119051* data[SEQ_DECL_SIZE];
};
N_NIMCALL(surface132715*, loadimage_176031)(NimStringDesc* filename);
N_NIMCALL(assetgroupHEX3Aobjecttype149022*, newassetgroup_179012)(NimStringDesc* name_179017, rect149007* rect_179019);
N_NIMCALL(void, newrect_149915)(NI x, NI y, NI w, NI h, TY149020* d, rect149007* Result);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(TY149663*, gettiles_179098)(assetgroupHEX3Aobjecttype149022* ig_179105, surface132715* isurf_179107, NI tw_179109, NI th_179111);
N_NIMCALL(sheetbundleHEX3Aobjecttype167013*, newbundle_168373)(TY154808* asa, TY167016* gra, TY167018* surfa);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_81404, TNimType* mt);
N_NIMCALL(NimStringDesc*, HEX24_179436)(orderedtable176685 t_179443);
static N_INLINE(NI, len_179448)(orderedtable176685 t_179455);
N_NIMCALL(TY176096*, packbundle_176092)(sheetbundleHEX3Aobjecttype167013* abd, assetgroupHEX3Aobjecttype149022* og);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(FILE*, open_12617)(NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void, writebmp32_171007)(FILE* fhdl, surface132715* isurf);
N_NIMCALL(void, savejson_176744)(TY149663* asset, NimStringDesc* fn, assetjsonmanifest176679* Result);
N_NIMCALL(void, loadjson_177754)(jsonnodeobj119051* jobj, assetjsonmanifest176679* Result);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_86825)(NimStringDesc* msg);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdlInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdlDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_bmpsdlInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_bmpsdlDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdleasyInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdleasyDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, example2Init)(void);
NIM_EXTERNC N_NOINLINE(void, example2DatInit)(void);
STRING_LITERAL(TMP718, "jerom-fantasy-tileset-32.png", 28);
STRING_LITERAL(TMP719, "Input32", 7);
STRING_LITERAL(TMP720, "jerom-fantasy-tileset-16.png", 28);
STRING_LITERAL(TMP721, "Input16", 7);
STRING_LITERAL(TMP722, "jerom-fantasy-tileset-8.png", 27);
STRING_LITERAL(TMP723, "Input8", 6);
STRING_LITERAL(TMP724, "Output", 6);
STRING_LITERAL(TMP730, "result", 6);
STRING_LITERAL(TMP731, ".bmp", 4);
STRING_LITERAL(TMP732, "(system.len|system.len|system.len|system.len|system.len|system."
"len|...)(a) (system.==|system.==|system.==|system.==|system.==|s"
"ystem.==|system.==|system.==|system.==|system.==|system.==|syste"
"m.==|system.==|system.==|system.==|system.==|system.==|system.=="
"|system.==|system.==|...)\015\012    L seq modified while iterating ov"
"er it", 324);
extern TY146221 Dl_146220;
surface132715* isurf32_179007;
assetgroupHEX3Aobjecttype149022* ig32_179040;
extern TFrame* frameptr_16242;
extern tgcheap47016 gch_47044;
surface132715* isurf16_179044;
assetgroupHEX3Aobjecttype149022* ig16_179058;
surface132715* isurf8_179062;
assetgroupHEX3Aobjecttype149022* ig8_179076;
assetgroupHEX3Aobjecttype149022* og_179092;
sheetbundleHEX3Aobjecttype167013* bd_179282;
extern TNimType NTI154808; /* seq[seq[Asset]] */
extern TNimType NTI149663; /* seq[Asset] */
extern TNimType NTI167016; /* seq[AssetGroup] */
extern TNimType NTI167018; /* seq[SurfacePtr] */
NI ct_179286;
bundletup176025 tup_179422;
extern TY143112 Dl_143111;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, len_179448)(orderedtable176685 t_179455) {
	NI result;
	nimfr("len", "tables.nim")
	result = 0;
	nimln(374, "tables.nim");
	result = t_179455.Counter;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_hashesDatInit();
	stdlib_streamsDatInit();
	stdlib_lexbaseDatInit();
	stdlib_unicodeDatInit();
	stdlib_jsonDatInit();
	stdlib_macrosDatInit();
	stdlib_unsignedDatInit();
	sdl2_sdl2DatInit();
	sdl2_imageDatInit();
	stdlib_sequtilsDatInit();
	stdlib_algorithmDatInit();
	HEX00_packDatInit();
	stdlib_winleanDatInit();
	stdlib_timesDatInit();
	stdlib_mathDatInit();
	HEX00_packsdlDatInit();
	stdlib_endiansDatInit();
	HEX00_bmpsdlDatInit();
	stdlib_tablesDatInit();
	HEX00_packsdleasyDatInit();
	example2DatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_hashesInit();
	stdlib_streamsInit();
	stdlib_lexbaseInit();
	stdlib_unicodeInit();
	stdlib_jsonInit();
	stdlib_macrosInit();
	stdlib_unsignedInit();
	sdl2_sdl2Init();
	sdl2_imageInit();
	stdlib_sequtilsInit();
	stdlib_algorithmInit();
	HEX00_packInit();
	stdlib_winleanInit();
	stdlib_timesInit();
	stdlib_mathInit();
	HEX00_packsdlInit();
	stdlib_endiansInit();
	HEX00_bmpsdlInit();
	stdlib_tablesInit();
	HEX00_packsdleasyInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	example2Init();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, example2Init)(void) {
	rect149007 LOC1;
	rect149007 LOC2;
	rect149007 LOC3;
	rect149007 LOC4;
	TY154808* LOC5;
	TY179244 LOC6;
	TY167016* LOC7;
	TY179262 LOC8;
	TY167018* LOC9;
	TY179280 LOC10;
	nimfr("example2", "example2.nim")
	nimln(11, "example2.nim");
	nimln(13, "example2.nim");
	isurf32_179007 = loadimage_176031(((NimStringDesc*) &TMP718));
	nimln(14, "example2.nim");
	nimln(14, "example2.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	newrect_149915(0, 0, ((NI) ((*isurf32_179007).W)), ((NI) ((*isurf32_179007).H)), NIM_NIL, (&LOC1));
	asgnRefNoCycle((void**) (&ig32_179040), newassetgroup_179012(((NimStringDesc*) &TMP719), (&LOC1)));
	nimln(15, "example2.nim");
	isurf16_179044 = loadimage_176031(((NimStringDesc*) &TMP720));
	nimln(16, "example2.nim");
	nimln(16, "example2.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	newrect_149915(0, 0, ((NI) ((*isurf16_179044).W)), ((NI) ((*isurf16_179044).H)), NIM_NIL, (&LOC2));
	asgnRefNoCycle((void**) (&ig16_179058), newassetgroup_179012(((NimStringDesc*) &TMP721), (&LOC2)));
	nimln(17, "example2.nim");
	isurf8_179062 = loadimage_176031(((NimStringDesc*) &TMP722));
	nimln(18, "example2.nim");
	nimln(18, "example2.nim");
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	newrect_149915(0, 0, ((NI) ((*isurf8_179062).W)), ((NI) ((*isurf8_179062).H)), NIM_NIL, (&LOC3));
	asgnRefNoCycle((void**) (&ig8_179076), newassetgroup_179012(((NimStringDesc*) &TMP723), (&LOC3)));
	nimln(19, "example2.nim");
	nimln(19, "example2.nim");
	memset((void*)(&LOC4), 0, sizeof(LOC4));
	newrect_149915(0, 0, 256, 256, NIM_NIL, (&LOC4));
	asgnRefNoCycle((void**) (&og_179092), newassetgroup_179012(((NimStringDesc*) &TMP724), (&LOC4)));
	nimln(21, "example2.nim");
	nimln(21, "example2.nim");
	LOC5 = 0;
	LOC5 = (TY154808*) newSeq((&NTI154808), 3);
	memset((void*)LOC6, 0, sizeof(LOC6));
	nimln(22, "example2.nim");
	LOC6[0] = gettiles_179098(ig32_179040, isurf32_179007, 32, 32);
	nimln(23, "example2.nim");
	LOC6[1] = gettiles_179098(ig16_179058, isurf16_179044, 16, 16);
	nimln(24, "example2.nim");
	LOC6[2] = gettiles_179098(ig8_179076, isurf8_179062, 8, 8);
	genericSeqAssign((&LOC5->data[0]), LOC6[0], (&NTI149663));
	genericSeqAssign((&LOC5->data[1]), LOC6[1], (&NTI149663));
	genericSeqAssign((&LOC5->data[2]), LOC6[2], (&NTI149663));
	nimln(25, "example2.nim");
	LOC7 = 0;
	LOC7 = (TY167016*) newSeq((&NTI167016), 3);
	memset((void*)LOC8, 0, sizeof(LOC8));
	LOC8[0] = ig32_179040;
	LOC8[1] = ig16_179058;
	LOC8[2] = ig8_179076;
	asgnRefNoCycle((void**) (&LOC7->data[0]), LOC8[0]);
	asgnRefNoCycle((void**) (&LOC7->data[1]), LOC8[1]);
	asgnRefNoCycle((void**) (&LOC7->data[2]), LOC8[2]);
	nimln(26, "example2.nim");
	LOC9 = 0;
	LOC9 = (TY167018*) newSeq((&NTI167018), 3);
	LOC10[0] = isurf32_179007;
	LOC10[1] = isurf16_179044;
	LOC10[2] = isurf8_179062;
	LOC9->data[0] = LOC10[0];
	LOC9->data[1] = LOC10[1];
	LOC9->data[2] = LOC10[2];
	asgnRefNoCycle((void**) (&bd_179282), newbundle_168373(LOC5, LOC7, LOC9));
	nimln(28, "example2.nim");
	ct_179286 = 0;
	{
		TY176096* HEX3Atmp_179538;
		NI i_179541;
		NI l_179543;
		HEX3Atmp_179538 = 0;
		nimln(29, "example2.nim");
		HEX3Atmp_179538 = packbundle_176092(bd_179282, og_179092);
		nimln(2986, "system.nim");
		i_179541 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_179543 = HEX3Atmp_179538->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				NimStringDesc* fname;
				NimStringDesc* LOC14;
				NimStringDesc* LOC15;
				NCSTRING LOC16;
				NimStringDesc* LOC17;
				FILE* outf;
				jsonnodeobj119051* j;
				assetjsonmanifest176679 LOC18;
				assetjsonmanifest176679 LOC19;
				NimStringDesc* LOC20;
				nimln(2988, "system.nim");
				if (!(i_179541 < l_179543)) goto LA13;
				nimln(2989, "system.nim");
				if ((NU)(i_179541) >= (NU)(HEX3Atmp_179538->Sup.len)) raiseIndexError();
				tup_179422.Field0 = HEX3Atmp_179538->data[i_179541].Field0;
				asgnRefNoCycle((void**) (&tup_179422.Field1), HEX3Atmp_179538->data[i_179541].Field1);
				nimln(30, "example2.nim");
				nimln(30, "example2.nim");
				LOC14 = 0;
				nimln(30, "example2.nim");
				LOC15 = 0;
				LOC15 = nsuIntToStr(ct_179286, 4);
				LOC14 = rawNewString(LOC15->Sup.len + 10);
appendString(LOC14, ((NimStringDesc*) &TMP730));
appendString(LOC14, LOC15);
appendString(LOC14, ((NimStringDesc*) &TMP731));
				fname = LOC14;
				nimln(31, "example2.nim");
				nimln(31, "example2.nim");
				printf("%s\015\012", (fname)->data);
				nimln(32, "example2.nim");
				nimln(32, "example2.nim");
				nimln(32, "example2.nim");
				LOC16 = 0;
				LOC16 = Dl_143111((*(*tup_179422.Field0).Format).Format);
				LOC17 = 0;
				LOC17 = cstrToNimstr(LOC16);
				printf("%s\015\012", (LOC17)->data);
				nimln(33, "example2.nim");
				outf = open_12617(fname, ((NU8) 1), -1);
				nimln(33, "example2.nim");
				writebmp32_171007(outf, tup_179422.Field0);
				nimln(33, "example2.nim");
				fclose(outf);
				nimln(34, "example2.nim");
				nimln(34, "example2.nim");
				memset((void*)(&LOC18), 0, sizeof(LOC18));
				savejson_176744((*tup_179422.Field1).Asset, fname, (&LOC18));
				j = LOC18.Field2;
				nimln(35, "example2.nim");
				nimln(35, "example2.nim");
				nimln(35, "example2.nim");
				memset((void*)(&LOC19), 0, sizeof(LOC19));
				loadjson_177754(j, (&LOC19));
				LOC20 = 0;
				LOC20 = HEX24_179436(LOC19.Field0);
				printf("%s\015\012", (LOC20)->data);
				nimln(36, "example2.nim");
				ct_179286 = addInt(ct_179286, 1);
				nimln(2990, "system.nim");
				i_179541 = addInt(i_179541, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((HEX3Atmp_179538->Sup.len == l_179543))) goto LA23;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP732));
				}
				LA23: ;
			} LA13: ;
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, example2DatInit)(void) {
}

