/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\packsdl.o c:\dropbox\2015\nim\packer\example\nimcache\packsdl.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct rect132277 rect132277;
typedef struct rect149007 rect149007;
typedef struct TY149020 TY149020;
typedef struct dataentry149005 dataentry149005;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct rendererptrHEX3Aobjecttype132578 rendererptrHEX3Aobjecttype132578;
typedef struct TY149663 TY149663;
typedef struct assetHEX3Aobjecttype149027 assetHEX3Aobjecttype149027;
typedef struct assetgroupHEX3Aobjecttype149022 assetgroupHEX3Aobjecttype149022;
typedef struct TY149048 TY149048;
typedef struct surface132715 surface132715;
typedef struct pixelformat132709 pixelformat132709;
typedef struct palette132707 palette132707;
typedef struct textureptrHEX3Aobjecttype132579 textureptrHEX3Aobjecttype132579;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct sheetbundleHEX3Aobjecttype167013 sheetbundleHEX3Aobjecttype167013;
typedef struct TY167016 TY167016;
typedef struct TY167018 TY167018;
typedef struct cropresultHEX3Aobjecttype149033 cropresultHEX3Aobjecttype149033;
typedef struct blitmapptrHEX3Aobjecttype132757 blitmapptrHEX3Aobjecttype132757;
typedef struct TY154808 TY154808;
typedef struct color132705 color132705;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
struct rect132277 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  dataentry149005  {
NimStringDesc* K;
NI V;
};
struct  rect149007  {
NI X;
NI Y;
NI W;
NI H;
TY149020* D;
};
typedef N_CDECL_PTR(NI32, TY142006) (rendererptrHEX3Aobjecttype132578* renderer, rect132277* rect);
typedef N_CDECL_PTR(NI32, TY141981) (rendererptrHEX3Aobjecttype132578* renderer, rect132277* rect);
typedef N_CDECL_PTR(NI32, TY141945) (rendererptrHEX3Aobjecttype132578* renderer, int x, int y);
struct  assetHEX3Aobjecttype149027  {
assetHEX3Aobjecttype149027* P;
NI I;
assetgroupHEX3Aobjecttype149022* G;
TY149048* R;
};
typedef N_CDECL_PTR(NI32, TY141433) (rendererptrHEX3Aobjecttype132578* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(rendererptrHEX3Aobjecttype132578*, TY141757) (surface132715* surface);
typedef N_CDECL_PTR(void, TY141475) (rendererptrHEX3Aobjecttype132578* renderer);
typedef N_CDECL_PTR(pixelformat132709*, TY143141) (NU32 pixelformat);
typedef N_CDECL_PTR(surface132715*, TY142099) (int flags, int width, int height, int depth, NU32 rmask, NU32 gmask, NU32 bmask, NU32 amask);
typedef NU8 TY132739[2];
struct  pixelformat132709  {
NU32 Format;
palette132707* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY132739 Padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int Refcount;
pixelformat132709* Next;
};
typedef N_CDECL_PTR(void, TY143151) (pixelformat132709* format);
typedef N_CDECL_PTR(NU32, TY143131) (int bpp, NU32 rmask, NU32 gmask, NU32 bmask, NU32 amask);
typedef N_CDECL_PTR(textureptrHEX3Aobjecttype132579*, TY141786) (rendererptrHEX3Aobjecttype132578* renderer, surface132715* surface);
typedef N_CDECL_PTR(NI32, TY142023) (rendererptrHEX3Aobjecttype132578* renderer, textureptrHEX3Aobjecttype132579* texture, rect132277* srcrect, rect132277* dstrect);
typedef N_CDECL_PTR(void, TY141469) (textureptrHEX3Aobjecttype132579* texture);
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
struct  sheetbundleHEX3Aobjecttype167013  {
TY149663* Asset;
TY167016* Group;
TY167018* Surf;
};
struct  assetgroupHEX3Aobjecttype149022  {
rect149007 Rect;
NimStringDesc* Name;
NI Counter;
NI Id;
};
struct  surface132715  {
NU32 Flags;
pixelformat132709* Format;
NI32 W;
NI32 H;
NI32 Pitch;
void* Pixels;
void* Userdata;
NI32 Locked;
void* Lockdata;
rect132277 Cliprect;
blitmapptrHEX3Aobjecttype132757* Map;
int Refcount;
};
typedef NI TY168145[4];
struct  cropresultHEX3Aobjecttype149033  {
NI Left;
NI Right;
NI Top;
NI Bottom;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  rendererptrHEX3Aobjecttype132578  {
char dummy;
};
struct  palette132707  {
int Ncolors;
color132705* Colors;
NU32 Version;
int Refcount;
};
struct  textureptrHEX3Aobjecttype132579  {
char dummy;
};
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  blitmapptrHEX3Aobjecttype132757  {
char dummy;
};
struct color132705 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
struct TY149020 {
  TGenericSeq Sup;
  dataentry149005 data[SEQ_DECL_SIZE];
};
struct TY149663 {
  TGenericSeq Sup;
  assetHEX3Aobjecttype149027* data[SEQ_DECL_SIZE];
};
struct TY149048 {
  TGenericSeq Sup;
  rect149007 data[SEQ_DECL_SIZE];
};
struct TY167016 {
  TGenericSeq Sup;
  assetgroupHEX3Aobjecttype149022* data[SEQ_DECL_SIZE];
};
struct TY167018 {
  TGenericSeq Sup;
  surface132715* data[SEQ_DECL_SIZE];
};
struct TY154808 {
  TGenericSeq Sup;
  TY149663* data[SEQ_DECL_SIZE];
};
N_NIMCALL(rect132277, newsdlrect_167024)(rect149007* r);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(rect132277, newsdlrect_167045)(NI x, NI y, NI w, NI h);
N_NIMCALL(rect132277, sdlrect_167068)(rect149007* r);
N_NIMCALL(void, fillrect_167080)(rendererptrHEX3Aobjecttype132578* renr, NI x, NI y, NI w, NI h);
N_NIMCALL(void, fillrect_167095)(rendererptrHEX3Aobjecttype132578* renr, rect149007* r);
N_NIMCALL(void, drawrect_167108)(rendererptrHEX3Aobjecttype132578* renr, NI x, NI y, NI w, NI h);
N_NIMCALL(void, drawrect_167123)(rendererptrHEX3Aobjecttype132578* renr, rect149007* r);
N_NIMCALL(void, drawcorners_167136)(rendererptrHEX3Aobjecttype132578* renr, NI x, NI y, NI w, NI h);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, drawcolors_167255)(rendererptrHEX3Aobjecttype132578* renr, TY149663* a0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TY149020*, HEX5BHEX5D_150080)(TY149020* s, NimStringDesc* k);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(void, drawcolors_167363)(surface132715* surf, TY149663* a0);
N_NIMCALL(surface132715*, newsurface_167421)(NI w_167426, NI h_167428);
N_NIMCALL(surface132715*, newsurface_167434)(NI w_167440, NI h_167442, NU32 format_167444);
static N_INLINE(void, destroy_143610)(pixelformat132709* format);
N_NIMCALL(surface132715*, newsurface_167415)(rect149007* rect);
N_NIMCALL(void, copy_167462)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, rect132277* srcrect, rect132277* destrect);
N_NIMCALL(void, copy_167479)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, rect149007* srcrect, rect149007* destrect);
N_NIMCALL(Exception*, new_155056)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void, copy_167508)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, rect132277* srcrect, rect149007* destrect);
N_NIMCALL(void, copy_167525)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, rect149007* srcrect, rect132277* destrect);
N_NIMCALL(void, copy_167542)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, assetHEX3Aobjecttype149027* a0, assetHEX3Aobjecttype149027* a1);
N_NIMCALL(void, copy_167560)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, TY149663* a0, TY149663* a1);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, copy_167651)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, TY149663* a0);
N_NIMCALL(void, failedassertimpl_86825)(NimStringDesc* msg);
N_NIMCALL(void, copy_167709)(rendererptrHEX3Aobjecttype132578* renr, sheetbundleHEX3Aobjecttype167013* sbd);
N_NIMCALL(void, copy_167748)(surface132715* dest, surface132715* src, TY149663* a0);
N_NIMCALL(void, copy_167761)(surface132715* dest, sheetbundleHEX3Aobjecttype167013* sbd);
N_NIMCALL(cropresultHEX3Aobjecttype149033*, newcropresult_167972)(NI left_167979, NI top_167981, NI right_167983, NI bottom_167985);
N_NIMCALL(cropresultHEX3Aobjecttype149033*, cropbounds_167772)(surface132715* surf, NU32 colorkey, rect149007* r);
N_NIMCALL(NI, min_168106)(NI* x_168112, NI x_168112Len0);
N_NIMCALL(cropresultHEX3Aobjecttype149033*, crop_168050)(assetHEX3Aobjecttype149027* asset, surface132715* surf, NU32 colorkey, NU8 cropt);
N_NIMCALL(NIM_BOOL, isempty_168230)(rect149007* rect, surface132715* surf, NU32 colorkey);
N_NIMCALL(NIM_BOOL, isempty_168348)(assetHEX3Aobjecttype149027* asset, surface132715* surf, NU32 colorkey);
N_NIMCALL(void, reduce_168360)(assetHEX3Aobjecttype149027* asset, surface132715* isurf, NU32 colorkey, NU8 cropt);
N_NIMCALL(void, reduce_151580)(TY149048** r, cropresultHEX3Aobjecttype149033* cropr);
N_NIMCALL(sheetbundleHEX3Aobjecttype167013*, newbundle_168373)(TY154808* asa, TY167016* gra, TY167018* surfa);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP647)(void* p, NI op);
N_NIMCALL(void, TMP653)(void* p, NI op);
N_NIMCALL(void, TMP654)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51025)(tcell44933* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c);
static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c);
N_NOINLINE(void, incl_45671)(tcellset44945* s, tcell44933* cell);
static N_INLINE(void, decref_50604)(tcell44933* c);
STRING_LITERAL(TMP616, "Color", 5);
STRING_LITERAL(TMP618, "Source asset dimensions are different from dest asset dimension"
"s: ", 66);
STRING_LITERAL(TMP619, "x", 1);
STRING_LITERAL(TMP620, " ", 1);
STRING_LITERAL(TMP621, "Source asset sequence is different size from dest asset sequenc"
"e", 64);
STRING_LITERAL(TMP622, "Source asset dimensions are different from dest asset dimension"
"s", 64);
STRING_LITERAL(TMP623, "(system.len|system.len|system.len|system.len|system.len|system."
"len|...)(a) (system.==|system.==|system.==|system.==|system.==|s"
"ystem.==|system.==|system.==|system.==|system.==|system.==|syste"
"m.==|system.==|system.==|system.==|system.==|system.==|system.=="
"|system.==|system.==|...)\015\012    L seq modified while iterating ov"
"er it", 324);
extern TFrame* frameptr_16242;
extern TY142006 Dl_142005;
extern TY141981 Dl_141980;
extern TY141945 Dl_141944;
extern TY141433 Dl_141432;
extern TY141757 Dl_141756;
extern TY141475 Dl_141474;
extern TY143141 Dl_143140;
extern TY142099 Dl_142098;
extern TY143151 Dl_143150;
extern TY143131 Dl_143130;
extern TY141786 Dl_141785;
extern TY142023 Dl_142022;
extern TY141469 Dl_141468;
extern tgcheap47016 gch_47044;
TNimType NTI167013; /* SheetBundle:ObjectType */
extern TNimType NTI149663; /* seq[Asset] */
extern TNimType NTI149009; /* AssetGroup */
TNimType NTI167016; /* seq[AssetGroup] */
extern TNimType NTI132713; /* SurfacePtr */
TNimType NTI167018; /* seq[SurfacePtr] */
TNimType NTI167007; /* SheetBundle */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(rect132277, newsdlrect_167024)(rect149007* r) {
	rect132277 result;
	nimfr("newSDLRect", "packsdl.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(19, "packsdl.nim");
	result.Field0 = ((int) ((*r).X));
	result.Field1 = ((int) ((*r).Y));
	result.Field2 = ((int) ((*r).W));
	result.Field3 = ((int) ((*r).H));
	popFrame();
	return result;
}

N_NIMCALL(rect132277, newsdlrect_167045)(NI x, NI y, NI w, NI h) {
	rect132277 result;
	nimfr("newSDLRect", "packsdl.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(21, "packsdl.nim");
	result.Field0 = ((int) (x));
	result.Field1 = ((int) (y));
	result.Field2 = ((int) (w));
	result.Field3 = ((int) (h));
	popFrame();
	return result;
}

N_NIMCALL(rect132277, sdlrect_167068)(rect149007* r) {
	rect132277 result;
	nimfr("SDLRect", "packsdl.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(22, "packsdl.nim");
	nimln(22, "packsdl.nim");
	result = newsdlrect_167024(r);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, fillrect_167080)(rendererptrHEX3Aobjecttype132578* renr, NI x, NI y, NI w, NI h) {
	rect132277 rect0;
	NI32 LOC1;
	nimfr("fillRect", "packsdl.nim")
	nimln(24, "packsdl.nim");
	rect0 = newsdlrect_167045(x, y, w, h);
	nimln(25, "packsdl.nim");
	LOC1 = 0;
	LOC1 = Dl_142005(renr, (&rect0));
	popFrame();
}

N_NIMCALL(void, fillrect_167095)(rendererptrHEX3Aobjecttype132578* renr, rect149007* r) {
	rect132277 rect0;
	NI32 LOC1;
	nimfr("fillRect", "packsdl.nim")
	nimln(27, "packsdl.nim");
	rect0 = sdlrect_167068(r);
	nimln(28, "packsdl.nim");
	LOC1 = 0;
	LOC1 = Dl_142005(renr, (&rect0));
	popFrame();
}

N_NIMCALL(void, drawrect_167108)(rendererptrHEX3Aobjecttype132578* renr, NI x, NI y, NI w, NI h) {
	rect132277 rect0;
	NI32 LOC1;
	nimfr("drawRect", "packsdl.nim")
	nimln(30, "packsdl.nim");
	rect0 = newsdlrect_167045(x, y, w, h);
	nimln(31, "packsdl.nim");
	LOC1 = 0;
	LOC1 = Dl_141980(renr, (&rect0));
	popFrame();
}

N_NIMCALL(void, drawrect_167123)(rendererptrHEX3Aobjecttype132578* renr, rect149007* r) {
	rect132277 rect0;
	NI32 LOC1;
	nimfr("drawRect", "packsdl.nim")
	nimln(33, "packsdl.nim");
	rect0 = sdlrect_167068(r);
	nimln(34, "packsdl.nim");
	LOC1 = 0;
	LOC1 = Dl_141980(renr, (&rect0));
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, drawcorners_167136)(rendererptrHEX3Aobjecttype132578* renr, NI x, NI y, NI w, NI h) {
	NI32 LOC1;
	NI TMP612;
	NI32 LOC2;
	NI TMP613;
	NI32 LOC3;
	NI TMP614;
	NI TMP615;
	NI32 LOC4;
	nimfr("drawCorners", "packsdl.nim")
	nimln(36, "packsdl.nim");
	LOC1 = 0;
	LOC1 = Dl_141944(renr, ((int) (x)), ((int) (y)));
	nimln(37, "packsdl.nim");
	nimln(37, "packsdl.nim");
	nimln(37, "packsdl.nim");
	TMP612 = addInt(x, subInt(w, 1));
	LOC2 = 0;
	LOC2 = Dl_141944(renr, ((int) ((NI32)(TMP612))), ((int) (y)));
	nimln(38, "packsdl.nim");
	nimln(38, "packsdl.nim");
	nimln(38, "packsdl.nim");
	TMP613 = addInt(y, subInt(h, 1));
	LOC3 = 0;
	LOC3 = Dl_141944(renr, ((int) (x)), ((int) ((NI32)(TMP613))));
	nimln(39, "packsdl.nim");
	nimln(39, "packsdl.nim");
	nimln(39, "packsdl.nim");
	TMP614 = addInt(x, subInt(w, 1));
	nimln(39, "packsdl.nim");
	nimln(39, "packsdl.nim");
	TMP615 = addInt(y, subInt(h, 1));
	LOC4 = 0;
	LOC4 = Dl_141944(renr, ((int) ((NI32)(TMP614))), ((int) ((NI32)(TMP615))));
	popFrame();
}

N_NIMCALL(void, drawcolors_167255)(rendererptrHEX3Aobjecttype132578* renr, TY149663* a0) {
	nimfr("drawColors", "packsdl.nim")
	{
		NI i0_167270;
		NI HEX3Atmp_167343;
		NI res_167346;
		i0_167270 = 0;
		HEX3Atmp_167343 = 0;
		nimln(47, "packsdl.nim");
		nimln(47, "packsdl.nim");
		HEX3Atmp_167343 = (a0->Sup.len-1);
		nimln(1576, "system.nim");
		res_167346 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				rect149007 r;
				TY149020* ci;
				NI c;
				NI TMP617;
				NI32 LOC9;
				NI32 LOC10;
				nimln(1577, "system.nim");
				if (!(res_167346 <= HEX3Atmp_167343)) goto LA3;
				nimln(1576, "system.nim");
				i0_167270 = res_167346;
				memset((void*)(&r), 0, sizeof(r));
				nimln(48, "packsdl.nim");
				if ((NU)(i0_167270) >= (NU)(a0->Sup.len)) raiseIndexError();
				if ((NU)(0) >= (NU)((*a0->data[i0_167270]).R->Sup.len)) raiseIndexError();
				memcpy((void*)(&r), (NIM_CONST void*)(&(*a0->data[i0_167270]).R->data[0]), sizeof(r));
				nimln(49, "packsdl.nim");
				ci = HEX5BHEX5D_150080(r.D, ((NimStringDesc*) &TMP616));
				nimln(50, "packsdl.nim");
				nimln(50, "packsdl.nim");
				{
					nimln(50, "packsdl.nim");
					nimln(50, "packsdl.nim");
					if (!(0 < ci->Sup.len)) goto LA6;
					if ((NU)(0) >= (NU)(ci->Sup.len)) raiseIndexError();
					c = ci->data[0].V;
				}
				goto LA4;
				LA6: ;
				{
					c = 16777215;
				}
				LA4: ;
				nimln(51, "packsdl.nim");
				nimln(51, "packsdl.nim");
				nimln(51, "packsdl.nim");
				nimln(51, "packsdl.nim");
				TMP617 = mulInt((NI)((NU32)(c) >> (NU32)(4)), 2);
				nimln(52, "packsdl.nim");
				nimln(52, "packsdl.nim");
				nimln(52, "packsdl.nim");
				LOC9 = 0;
				LOC9 = Dl_141432(renr, ((NU8) ((NI)((NI32)(TMP617) & 255))), ((NU8) ((NI)((NI)((NU32)(c) >> (NU32)(4)) & 255))), ((NU8) ((NI)(c & 255))), ((NU8) 255));
				nimln(53, "packsdl.nim");
				fillrect_167080(renr, r.X, r.Y, r.W, r.H);
				nimln(54, "packsdl.nim");
				LOC10 = 0;
				LOC10 = Dl_141432(renr, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
				nimln(55, "packsdl.nim");
				drawcorners_167136(renr, r.X, r.Y, r.W, r.H);
				nimln(1579, "system.nim");
				res_167346 = addInt(res_167346, 1);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, drawcolors_167363)(surface132715* surf, TY149663* a0) {
	rendererptrHEX3Aobjecttype132578* swrenr;
	nimfr("drawColors", "packsdl.nim")
	nimln(57, "packsdl.nim");
	swrenr = Dl_141756(surf);
	nimln(58, "packsdl.nim");
	drawcolors_167255(swrenr, a0);
	nimln(59, "packsdl.nim");
	Dl_141474(swrenr);
	popFrame();
}

static N_INLINE(void, destroy_143610)(pixelformat132709* format) {
	nimfr("destroy", "sdl2.nim")
	nimln(1485, "sdl2.nim");
	Dl_143150(format);
	popFrame();
}

N_NIMCALL(surface132715*, newsurface_167434)(NI w_167440, NI h_167442, NU32 format_167444) {
	surface132715* result;
	pixelformat132709* fmt;
	nimfr("newSurface", "packsdl.nim")
	result = 0;
	nimln(61, "packsdl.nim");
	fmt = Dl_143140(format_167444);
	nimln(62, "packsdl.nim");
	result = Dl_142098(((int) 0), ((int) (w_167440)), ((int) (h_167442)), ((int) ((*fmt).Bitsperpixel)), (*fmt).Rmask, (*fmt).Gmask, (*fmt).Bmask, (*fmt).Amask);
	nimln(64, "packsdl.nim");
	destroy_143610(fmt);
	popFrame();
	return result;
}

N_NIMCALL(surface132715*, newsurface_167421)(NI w_167426, NI h_167428) {
	surface132715* result;
	NU32 LOC1;
	nimfr("newSurface", "packsdl.nim")
	result = 0;
	nimln(66, "packsdl.nim");
	nimln(66, "packsdl.nim");
	nimln(66, "packsdl.nim");
	LOC1 = 0;
	LOC1 = Dl_143130(((int) 32), ((NU32) IL64(4278190080)), ((NU32) 16711680), ((NU32) 65280), ((NU32) 255));
	result = newsurface_167434(w_167426, h_167428, LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(surface132715*, newsurface_167415)(rect149007* rect) {
	surface132715* result;
	nimfr("newSurface", "packsdl.nim")
	result = 0;
	nimln(69, "packsdl.nim");
	result = newsurface_167421((*rect).W, (*rect).H);
	popFrame();
	return result;
}

N_NIMCALL(void, copy_167462)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, rect132277* srcrect, rect132277* destrect) {
	textureptrHEX3Aobjecttype132579* tx;
	NI32 LOC1;
	nimfr("copy", "packsdl.nim")
	nimln(71, "packsdl.nim");
	tx = Dl_141785(renr, src);
	nimln(72, "packsdl.nim");
	LOC1 = 0;
	LOC1 = Dl_142022(renr, tx, srcrect, destrect);
	nimln(73, "packsdl.nim");
	Dl_141468(tx);
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, copy_167479)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, rect149007* srcrect, rect149007* destrect) {
	rect132277 r0;
	rect132277 r1;
	nimfr("copy", "packsdl.nim")
	nimln(75, "packsdl.nim");
	{
		NIM_BOOL LOC3;
		Exception* ex;
		NimStringDesc* LOC7;
		NimStringDesc* LOC8;
		NimStringDesc* LOC9;
		NimStringDesc* LOC10;
		NimStringDesc* LOC11;
		nimln(75, "packsdl.nim");
		LOC3 = 0;
		nimln(75, "packsdl.nim");
		nimln(75, "packsdl.nim");
		LOC3 = !(((*srcrect).W == (*destrect).W));
		if (LOC3) goto LA4;
		nimln(75, "packsdl.nim");
		nimln(75, "packsdl.nim");
		LOC3 = !(((*srcrect).H == (*destrect).H));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(76, "packsdl.nim");
		ex = new_155056();
		nimln(77, "packsdl.nim");
		nimln(79, "packsdl.nim");
		LOC7 = 0;
		nimln(78, "packsdl.nim");
		LOC8 = 0;
		LOC8 = nimIntToStr((*srcrect).W);
		nimln(78, "packsdl.nim");
		LOC9 = 0;
		LOC9 = nimIntToStr((*srcrect).H);
		nimln(79, "packsdl.nim");
		LOC10 = 0;
		LOC10 = nimIntToStr((*destrect).W);
		nimln(79, "packsdl.nim");
		LOC11 = 0;
		LOC11 = nimIntToStr((*destrect).H);
		LOC7 = rawNewString(LOC8->Sup.len + LOC9->Sup.len + LOC10->Sup.len + LOC11->Sup.len + 70);
appendString(LOC7, ((NimStringDesc*) &TMP618));
appendString(LOC7, LOC8);
appendString(LOC7, ((NimStringDesc*) &TMP619));
appendString(LOC7, LOC9);
appendString(LOC7, ((NimStringDesc*) &TMP620));
appendString(LOC7, LOC10);
appendString(LOC7, ((NimStringDesc*) &TMP619));
appendString(LOC7, LOC11);
appendString(LOC7, ((NimStringDesc*) &TMP620));
		asgnRefNoCycle((void**) (&(*ex).message), LOC7);
		nimln(80, "packsdl.nim");
		raiseException((Exception*)ex, "Exception");
	}
	LA5: ;
	nimln(81, "packsdl.nim");
	r0 = sdlrect_167068(srcrect);
	nimln(81, "packsdl.nim");
	r1 = sdlrect_167068(destrect);
	nimln(82, "packsdl.nim");
	copy_167462(renr, src, (&r0), (&r1));
	popFrame();
}

N_NIMCALL(void, copy_167508)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, rect132277* srcrect, rect149007* destrect) {
	rect132277 r1;
	nimfr("copy", "packsdl.nim")
	nimln(84, "packsdl.nim");
	r1 = sdlrect_167068(destrect);
	nimln(85, "packsdl.nim");
	copy_167462(renr, src, srcrect, (&r1));
	popFrame();
}

N_NIMCALL(void, copy_167525)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, rect149007* srcrect, rect132277* destrect) {
	rect132277 r0;
	nimfr("copy", "packsdl.nim")
	nimln(87, "packsdl.nim");
	r0 = sdlrect_167068(srcrect);
	nimln(88, "packsdl.nim");
	copy_167462(renr, src, (&r0), destrect);
	popFrame();
}

N_NIMCALL(void, copy_167542)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, assetHEX3Aobjecttype149027* a0, assetHEX3Aobjecttype149027* a1) {
	rect132277 rect0;
	rect132277 rect1;
	nimfr("copy", "packsdl.nim")
	nimln(90, "packsdl.nim");
	nimln(90, "packsdl.nim");
	if ((NU)(0) >= (NU)((*a0).R->Sup.len)) raiseIndexError();
	rect0 = sdlrect_167068((&(*a0).R->data[0]));
	nimln(91, "packsdl.nim");
	nimln(91, "packsdl.nim");
	if ((NU)(0) >= (NU)((*a1).R->Sup.len)) raiseIndexError();
	rect1 = sdlrect_167068((&(*a1).R->data[0]));
	nimln(92, "packsdl.nim");
	copy_167462(renr, src, (&rect0), (&rect1));
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell44933* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48646(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50204(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, copy_167560)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, TY149663* a0, TY149663* a1) {
	rect132277 rect0;
	rect132277 rect1;
	textureptrHEX3Aobjecttype132579* tx;
	nimfr("copy", "packsdl.nim")
	nimln(95, "packsdl.nim");
	{
		Exception* ex;
		NimStringDesc* LOC5;
		nimln(95, "packsdl.nim");
		nimln(95, "packsdl.nim");
		nimln(95, "packsdl.nim");
		nimln(95, "packsdl.nim");
		if (!!((a0->Sup.len == a1->Sup.len))) goto LA3;
		nimln(96, "packsdl.nim");
		ex = new_155056();
		nimln(97, "packsdl.nim");
		LOC5 = 0;
		LOC5 = (*ex).message; (*ex).message = copyStringRC1(((NimStringDesc*) &TMP621));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(98, "packsdl.nim");
		raiseException((Exception*)ex, "Exception");
	}
	LA3: ;
	memset((void*)(&rect0), 0, sizeof(rect0));
	memset((void*)(&rect1), 0, sizeof(rect1));
	nimln(101, "packsdl.nim");
	tx = Dl_141785(renr, src);
	{
		NI i0_167615;
		NI HEX3Atmp_167631;
		NI res_167634;
		i0_167615 = 0;
		HEX3Atmp_167631 = 0;
		nimln(102, "packsdl.nim");
		nimln(102, "packsdl.nim");
		HEX3Atmp_167631 = (a0->Sup.len-1);
		nimln(1576, "system.nim");
		res_167634 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				NI32 LOC16;
				nimln(1577, "system.nim");
				if (!(res_167634 <= HEX3Atmp_167631)) goto LA8;
				nimln(1576, "system.nim");
				i0_167615 = res_167634;
				nimln(103, "packsdl.nim");
				if ((NU)(i0_167615) >= (NU)(a0->Sup.len)) raiseIndexError();
				if ((NU)(0) >= (NU)((*a0->data[i0_167615]).R->Sup.len)) raiseIndexError();
				rect0 = sdlrect_167068((&(*a0->data[i0_167615]).R->data[0]));
				nimln(104, "packsdl.nim");
				if ((NU)(i0_167615) >= (NU)(a1->Sup.len)) raiseIndexError();
				if ((NU)(0) >= (NU)((*a1->data[i0_167615]).R->Sup.len)) raiseIndexError();
				rect1 = sdlrect_167068((&(*a1->data[i0_167615]).R->data[0]));
				nimln(105, "packsdl.nim");
				{
					NIM_BOOL LOC11;
					Exception* ex;
					NimStringDesc* LOC15;
					nimln(105, "packsdl.nim");
					LOC11 = 0;
					nimln(105, "packsdl.nim");
					nimln(105, "packsdl.nim");
					LOC11 = !((rect0.Field2 == rect1.Field2));
					if (LOC11) goto LA12;
					nimln(105, "packsdl.nim");
					nimln(105, "packsdl.nim");
					LOC11 = !((rect0.Field3 == rect1.Field3));
					LA12: ;
					if (!LOC11) goto LA13;
					nimln(106, "packsdl.nim");
					ex = new_155056();
					nimln(107, "packsdl.nim");
					LOC15 = 0;
					LOC15 = (*ex).message; (*ex).message = copyStringRC1(((NimStringDesc*) &TMP622));
					if (LOC15) nimGCunrefNoCycle(LOC15);
					nimln(108, "packsdl.nim");
					raiseException((Exception*)ex, "Exception");
				}
				LA13: ;
				nimln(109, "packsdl.nim");
				LOC16 = 0;
				LOC16 = Dl_142022(renr, tx, (&rect0), (&rect1));
				nimln(1579, "system.nim");
				res_167634 = addInt(res_167634, 1);
			} LA8: ;
		}
	}
	nimln(110, "packsdl.nim");
	Dl_141468(tx);
	popFrame();
}

N_NIMCALL(void, copy_167651)(rendererptrHEX3Aobjecttype132578* renr, surface132715* src, TY149663* a0) {
	rect132277 rect0;
	rect132277 rect1;
	textureptrHEX3Aobjecttype132579* tx;
	nimfr("copy", "packsdl.nim")
	memset((void*)(&rect0), 0, sizeof(rect0));
	memset((void*)(&rect1), 0, sizeof(rect1));
	nimln(115, "packsdl.nim");
	tx = Dl_141785(renr, src);
	{
		assetHEX3Aobjecttype149027* a1_167674;
		NI i_167691;
		NI l_167693;
		a1_167674 = 0;
		nimln(2986, "system.nim");
		i_167691 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_167693 = a0->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				NI32 LOC11;
				nimln(2988, "system.nim");
				if (!(i_167691 < l_167693)) goto LA3;
				nimln(2989, "system.nim");
				if ((NU)(i_167691) >= (NU)(a0->Sup.len)) raiseIndexError();
				a1_167674 = a0->data[i_167691];
				nimln(117, "packsdl.nim");
				if ((NU)(0) >= (NU)((*(*a1_167674).P).R->Sup.len)) raiseIndexError();
				rect0 = sdlrect_167068((&(*(*a1_167674).P).R->data[0]));
				nimln(118, "packsdl.nim");
				if ((NU)(0) >= (NU)((*a1_167674).R->Sup.len)) raiseIndexError();
				rect1 = sdlrect_167068((&(*a1_167674).R->data[0]));
				nimln(119, "packsdl.nim");
				{
					NIM_BOOL LOC6;
					Exception* ex;
					NimStringDesc* LOC10;
					nimln(119, "packsdl.nim");
					LOC6 = 0;
					nimln(119, "packsdl.nim");
					nimln(119, "packsdl.nim");
					LOC6 = !((rect0.Field2 == rect1.Field2));
					if (LOC6) goto LA7;
					nimln(119, "packsdl.nim");
					nimln(119, "packsdl.nim");
					LOC6 = !((rect0.Field3 == rect1.Field3));
					LA7: ;
					if (!LOC6) goto LA8;
					nimln(120, "packsdl.nim");
					ex = new_155056();
					nimln(121, "packsdl.nim");
					LOC10 = 0;
					LOC10 = (*ex).message; (*ex).message = copyStringRC1(((NimStringDesc*) &TMP622));
					if (LOC10) nimGCunrefNoCycle(LOC10);
					nimln(122, "packsdl.nim");
					raiseException((Exception*)ex, "Exception");
				}
				LA8: ;
				nimln(123, "packsdl.nim");
				LOC11 = 0;
				LOC11 = Dl_142022(renr, tx, (&rect0), (&rect1));
				nimln(2990, "system.nim");
				i_167691 = addInt(i_167691, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((a0->Sup.len == l_167693))) goto LA14;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP623));
				}
				LA14: ;
			} LA3: ;
		}
	}
	nimln(124, "packsdl.nim");
	Dl_141468(tx);
	popFrame();
}

N_NIMCALL(void, copy_167709)(rendererptrHEX3Aobjecttype132578* renr, sheetbundleHEX3Aobjecttype167013* sbd) {
	nimfr("copy", "packsdl.nim")
	{
		assetHEX3Aobjecttype149027* a0_167725;
		TY149663* HEX3Atmp_167727;
		NI i_167730;
		NI l_167732;
		a0_167725 = 0;
		HEX3Atmp_167727 = 0;
		nimln(126, "packsdl.nim");
		HEX3Atmp_167727 = (*sbd).Asset;
		nimln(2986, "system.nim");
		i_167730 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_167732 = HEX3Atmp_167727->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_167730 < l_167732)) goto LA3;
				nimln(2989, "system.nim");
				if ((NU)(i_167730) >= (NU)(HEX3Atmp_167727->Sup.len)) raiseIndexError();
				a0_167725 = HEX3Atmp_167727->data[i_167730];
				nimln(127, "packsdl.nim");
				if ((NU)((*(*(*a0_167725).P).G).Id) >= (NU)((*sbd).Surf->Sup.len)) raiseIndexError();
				copy_167651(renr, (*sbd).Surf->data[(*(*(*a0_167725).P).G).Id], (*sbd).Asset);
				nimln(2990, "system.nim");
				i_167730 = addInt(i_167730, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((HEX3Atmp_167727->Sup.len == l_167732))) goto LA6;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP623));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, copy_167748)(surface132715* dest, surface132715* src, TY149663* a0) {
	rendererptrHEX3Aobjecttype132578* renr;
	nimfr("copy", "packsdl.nim")
	nimln(129, "packsdl.nim");
	renr = Dl_141756(dest);
	nimln(130, "packsdl.nim");
	copy_167651(renr, src, a0);
	nimln(131, "packsdl.nim");
	Dl_141474(renr);
	popFrame();
}

N_NIMCALL(void, copy_167761)(surface132715* dest, sheetbundleHEX3Aobjecttype167013* sbd) {
	rendererptrHEX3Aobjecttype132578* renr;
	nimfr("copy", "packsdl.nim")
	nimln(133, "packsdl.nim");
	renr = Dl_141756(dest);
	nimln(134, "packsdl.nim");
	copy_167709(renr, sbd);
	nimln(135, "packsdl.nim");
	Dl_141474(renr);
	popFrame();
}

N_NIMCALL(cropresultHEX3Aobjecttype149033*, cropbounds_167772)(surface132715* surf, NU32 colorkey, rect149007* r) {
	cropresultHEX3Aobjecttype149033* result;
	NI bottom;
	NI right;
	NI top;
	NI TMP626;
	NI left;
	NI TMP627;
	NI TMP634;
	NI TMP635;
	NI TMP636;
	NI TMP637;
	NI TMP638;
	NI TMP639;
	nimfr("cropBounds", "packsdl.nim")
	result = 0;
	nimln(139, "packsdl.nim");
	nimln(139, "packsdl.nim");
	nimln(139, "packsdl.nim");
	bottom = (((*r).Y <= ((NI) (subInt((*surf).H, 1)))) ? (*r).Y : ((NI) (subInt((*surf).H, 1))));
	nimln(140, "packsdl.nim");
	nimln(140, "packsdl.nim");
	nimln(140, "packsdl.nim");
	right = (((*r).X <= ((NI) (subInt((*surf).W, 1)))) ? (*r).X : ((NI) (subInt((*surf).W, 1))));
	nimln(141, "packsdl.nim");
	nimln(141, "packsdl.nim");
	nimln(141, "packsdl.nim");
	nimln(141, "packsdl.nim");
	TMP626 = addInt((*r).Y, subInt((*r).H, 1));
	top = (((NI32)(TMP626) >= 0) ? (NI32)(TMP626) : 0);
	nimln(142, "packsdl.nim");
	nimln(142, "packsdl.nim");
	nimln(142, "packsdl.nim");
	nimln(142, "packsdl.nim");
	TMP627 = addInt((*r).X, subInt((*r).W, 1));
	left = (((NI32)(TMP627) >= 0) ? (NI32)(TMP627) : 0);
	{
		NI y0_167860;
		NI HEX3Atmp_168020;
		NI HEX3Atmp_168021;
		NI TMP628;
		NI res_168024;
		y0_167860 = 0;
		HEX3Atmp_168020 = 0;
		HEX3Atmp_168021 = 0;
		nimln(143, "packsdl.nim");
		HEX3Atmp_168020 = (*r).Y;
		nimln(143, "packsdl.nim");
		nimln(143, "packsdl.nim");
		nimln(143, "packsdl.nim");
		TMP628 = addInt(subInt((*r).Y, 1), (*r).H);
		HEX3Atmp_168021 = (NI32)(TMP628);
		nimln(1576, "system.nim");
		res_168024 = HEX3Atmp_168020;
		{
			nimln(1577, "system.nim");
			while (1) {
				nimln(1577, "system.nim");
				if (!(res_168024 <= HEX3Atmp_168021)) goto LA3;
				nimln(1576, "system.nim");
				y0_167860 = res_168024;
				{
					NI x0_167882;
					NI HEX3Atmp_168014;
					NI HEX3Atmp_168015;
					NI TMP629;
					NI res_168018;
					x0_167882 = 0;
					HEX3Atmp_168014 = 0;
					HEX3Atmp_168015 = 0;
					nimln(144, "packsdl.nim");
					HEX3Atmp_168014 = (*r).X;
					nimln(144, "packsdl.nim");
					nimln(144, "packsdl.nim");
					nimln(144, "packsdl.nim");
					TMP629 = addInt(subInt((*r).X, 1), (*r).W);
					HEX3Atmp_168015 = (NI32)(TMP629);
					nimln(1576, "system.nim");
					res_168018 = HEX3Atmp_168014;
					{
						nimln(1577, "system.nim");
						while (1) {
							NI p0;
							NI TMP630;
							NI TMP631;
							NI TMP632;
							NU32 px;
							NI TMP633;
							NU32 maskresult;
							nimln(1577, "system.nim");
							if (!(res_168018 <= HEX3Atmp_168015)) goto LA6;
							nimln(1576, "system.nim");
							x0_167882 = res_168018;
							nimln(145, "packsdl.nim");
							nimln(145, "packsdl.nim");
							nimln(145, "packsdl.nim");
							TMP630 = mulInt(x0_167882, ((NI) ((*(*surf).Format).Bytesperpixel)));
							nimln(146, "packsdl.nim");
							TMP631 = mulInt(y0_167860, ((NI) ((*surf).Pitch)));
							TMP632 = addInt((NI32)(TMP630), (NI32)(TMP631));
							p0 = (NI32)(TMP632);
							nimln(147, "packsdl.nim");
							nimln(147, "packsdl.nim");
							TMP633 = addInt(((NI) ((*surf).Pixels)), p0);
							px = (*((int*) ((NI32)(TMP633))));
							nimln(148, "packsdl.nim");
							nimln(148, "packsdl.nim");
							maskresult = (NU32)(colorkey & px);
							nimln(149, "packsdl.nim");
							{
								nimln(149, "packsdl.nim");
								nimln(149, "packsdl.nim");
								if (!!((maskresult == ((NU32) 0)))) goto LA9;
								nimln(150, "packsdl.nim");
								nimln(150, "packsdl.nim");
								top = ((y0_167860 <= top) ? y0_167860 : top);
								nimln(151, "packsdl.nim");
								nimln(151, "packsdl.nim");
								left = ((x0_167882 <= left) ? x0_167882 : left);
								nimln(152, "packsdl.nim");
								nimln(152, "packsdl.nim");
								bottom = ((y0_167860 >= bottom) ? y0_167860 : bottom);
								nimln(153, "packsdl.nim");
								nimln(153, "packsdl.nim");
								right = ((x0_167882 >= right) ? x0_167882 : right);
							}
							LA9: ;
							nimln(1579, "system.nim");
							res_168018 = addInt(res_168018, 1);
						} LA6: ;
					}
				}
				nimln(1579, "system.nim");
				res_168024 = addInt(res_168024, 1);
			} LA3: ;
		}
	}
	nimln(154, "packsdl.nim");
	{
		NI LOC15;
		nimln(154, "packsdl.nim");
		if (!(bottom < top)) goto LA13;
		nimln(155, "packsdl.nim");
		LOC15 = 0;
		LOC15 = top;
		top = bottom;
		bottom = LOC15;
	}
	LA13: ;
	nimln(156, "packsdl.nim");
	{
		NI LOC20;
		nimln(156, "packsdl.nim");
		if (!(right < left)) goto LA18;
		nimln(157, "packsdl.nim");
		LOC20 = 0;
		LOC20 = left;
		left = right;
		right = LOC20;
	}
	LA18: ;
	nimln(158, "packsdl.nim");
	nimln(158, "packsdl.nim");
	nimln(158, "packsdl.nim");
	TMP634 = subInt(left, (*r).X);
	nimln(158, "packsdl.nim");
	TMP635 = subInt(top, (*r).Y);
	nimln(158, "packsdl.nim");
	nimln(158, "packsdl.nim");
	nimln(158, "packsdl.nim");
	TMP636 = addInt((*r).X, subInt((*r).W, 1));
	TMP637 = subInt((NI32)(TMP636), right);
	nimln(158, "packsdl.nim");
	nimln(158, "packsdl.nim");
	nimln(158, "packsdl.nim");
	TMP638 = addInt((*r).Y, subInt((*r).H, 1));
	TMP639 = subInt((NI32)(TMP638), bottom);
	result = newcropresult_167972((NI32)(TMP634), (NI32)(TMP635), (NI32)(TMP637), (NI32)(TMP639));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(cropresultHEX3Aobjecttype149033*, crop_168050)(assetHEX3Aobjecttype149027* asset, surface132715* surf, NU32 colorkey, NU8 cropt) {
	cropresultHEX3Aobjecttype149033* result;
	nimfr("crop", "packsdl.nim")
	result = 0;
	nimln(160, "packsdl.nim");
	{
		nimln(160, "packsdl.nim");
		if (!(cropt == ((NU8) 4))) goto LA3;
		nimln(161, "packsdl.nim");
		nimln(161, "packsdl.nim");
		result = newcropresult_167972(0, 0, 0, 0);
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		cropresultHEX3Aobjecttype149033* e;
		nimln(162, "packsdl.nim");
		if (!(cropt == ((NU8) 0))) goto LA6;
		nimln(163, "packsdl.nim");
		if ((NU)(0) >= (NU)((*asset).R->Sup.len)) raiseIndexError();
		e = cropbounds_167772(surf, colorkey, (&(*asset).R->data[0]));
		nimln(164, "packsdl.nim");
		nimln(164, "packsdl.nim");
		result = e;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		cropresultHEX3Aobjecttype149033* b;
		NI sz;
		TY168145 LOC11;
		nimln(165, "packsdl.nim");
		if (!(cropt == ((NU8) 1))) goto LA9;
		nimln(166, "packsdl.nim");
		if ((NU)(0) >= (NU)((*asset).R->Sup.len)) raiseIndexError();
		b = cropbounds_167772(surf, colorkey, (&(*asset).R->data[0]));
		nimln(167, "packsdl.nim");
		LOC11[0] = (*b).Left;
		LOC11[1] = (*b).Right;
		LOC11[2] = (*b).Top;
		LOC11[3] = (*b).Bottom;
		sz = min_168106(LOC11, 4);
		nimln(168, "packsdl.nim");
		nimln(168, "packsdl.nim");
		result = newcropresult_167972(sz, sz, sz, sz);
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		cropresultHEX3Aobjecttype149033* b;
		NI sz;
		nimln(169, "packsdl.nim");
		if (!(cropt == ((NU8) 2))) goto LA13;
		nimln(170, "packsdl.nim");
		if ((NU)(0) >= (NU)((*asset).R->Sup.len)) raiseIndexError();
		b = cropbounds_167772(surf, colorkey, (&(*asset).R->data[0]));
		nimln(171, "packsdl.nim");
		nimln(171, "packsdl.nim");
		sz = (((*b).Top <= (*b).Bottom) ? (*b).Top : (*b).Bottom);
		nimln(172, "packsdl.nim");
		nimln(172, "packsdl.nim");
		result = newcropresult_167972((*b).Left, sz, (*b).Right, sz);
		goto BeforeRet;
	}
	goto LA1;
	LA13: ;
	{
		cropresultHEX3Aobjecttype149033* b;
		NI sz;
		nimln(173, "packsdl.nim");
		if (!(cropt == ((NU8) 3))) goto LA16;
		nimln(174, "packsdl.nim");
		if ((NU)(0) >= (NU)((*asset).R->Sup.len)) raiseIndexError();
		b = cropbounds_167772(surf, colorkey, (&(*asset).R->data[0]));
		nimln(175, "packsdl.nim");
		nimln(175, "packsdl.nim");
		sz = (((*b).Left <= (*b).Right) ? (*b).Left : (*b).Right);
		nimln(176, "packsdl.nim");
		nimln(176, "packsdl.nim");
		result = newcropresult_167972(sz, (*b).Top, sz, (*b).Bottom);
		goto BeforeRet;
	}
	goto LA1;
	LA16: ;
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isempty_168230)(rect149007* rect, surface132715* surf, NU32 colorkey) {
	NIM_BOOL result;
	nimfr("isEmpty", "packsdl.nim")
	result = 0;
	{
		NI y0_168258;
		NI HEX3Atmp_168318;
		NI HEX3Atmp_168319;
		NI TMP640;
		NI res_168322;
		y0_168258 = 0;
		HEX3Atmp_168318 = 0;
		HEX3Atmp_168319 = 0;
		nimln(178, "packsdl.nim");
		HEX3Atmp_168318 = (*rect).Y;
		nimln(178, "packsdl.nim");
		nimln(178, "packsdl.nim");
		nimln(178, "packsdl.nim");
		TMP640 = addInt(subInt((*rect).Y, 1), (*rect).H);
		HEX3Atmp_168319 = (NI32)(TMP640);
		nimln(1576, "system.nim");
		res_168322 = HEX3Atmp_168318;
		{
			nimln(1577, "system.nim");
			while (1) {
				nimln(1577, "system.nim");
				if (!(res_168322 <= HEX3Atmp_168319)) goto LA3;
				nimln(1576, "system.nim");
				y0_168258 = res_168322;
				{
					NI x0_168280;
					NI HEX3Atmp_168312;
					NI HEX3Atmp_168313;
					NI TMP641;
					NI res_168316;
					x0_168280 = 0;
					HEX3Atmp_168312 = 0;
					HEX3Atmp_168313 = 0;
					nimln(179, "packsdl.nim");
					HEX3Atmp_168312 = (*rect).X;
					nimln(179, "packsdl.nim");
					nimln(179, "packsdl.nim");
					nimln(179, "packsdl.nim");
					TMP641 = addInt(subInt((*rect).X, 1), (*rect).W);
					HEX3Atmp_168313 = (NI32)(TMP641);
					nimln(1576, "system.nim");
					res_168316 = HEX3Atmp_168312;
					{
						nimln(1577, "system.nim");
						while (1) {
							NI p0;
							NI TMP642;
							NI TMP643;
							NI TMP644;
							NU32 px;
							NI TMP645;
							NU32 maskresult;
							nimln(1577, "system.nim");
							if (!(res_168316 <= HEX3Atmp_168313)) goto LA6;
							nimln(1576, "system.nim");
							x0_168280 = res_168316;
							nimln(180, "packsdl.nim");
							nimln(180, "packsdl.nim");
							nimln(180, "packsdl.nim");
							TMP642 = mulInt(x0_168280, ((NI) ((*(*surf).Format).Bytesperpixel)));
							nimln(181, "packsdl.nim");
							TMP643 = mulInt(y0_168258, ((NI) ((*surf).Pitch)));
							TMP644 = addInt((NI32)(TMP642), (NI32)(TMP643));
							p0 = (NI32)(TMP644);
							nimln(182, "packsdl.nim");
							nimln(182, "packsdl.nim");
							TMP645 = addInt(((NI) ((*surf).Pixels)), p0);
							px = (*((int*) ((NI32)(TMP645))));
							nimln(183, "packsdl.nim");
							nimln(183, "packsdl.nim");
							maskresult = (NU32)(colorkey & px);
							nimln(184, "packsdl.nim");
							{
								nimln(184, "packsdl.nim");
								if (!((NU32)(((NU32) 0)) < (NU32)(maskresult))) goto LA9;
								nimln(185, "packsdl.nim");
								nimln(185, "packsdl.nim");
								result = NIM_FALSE;
								goto BeforeRet;
							}
							LA9: ;
							nimln(1579, "system.nim");
							res_168316 = addInt(res_168316, 1);
						} LA6: ;
					}
				}
				nimln(1579, "system.nim");
				res_168322 = addInt(res_168322, 1);
			} LA3: ;
		}
	}
	nimln(186, "packsdl.nim");
	nimln(186, "packsdl.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isempty_168348)(assetHEX3Aobjecttype149027* asset, surface132715* surf, NU32 colorkey) {
	NIM_BOOL result;
	nimfr("isEmpty", "packsdl.nim")
	result = 0;
	nimln(188, "packsdl.nim");
	if ((NU)(0) >= (NU)((*asset).R->Sup.len)) raiseIndexError();
	result = isempty_168230((&(*asset).R->data[0]), surf, colorkey);
	popFrame();
	return result;
}

N_NIMCALL(void, reduce_168360)(assetHEX3Aobjecttype149027* asset, surface132715* isurf, NU32 colorkey, NU8 cropt) {
	cropresultHEX3Aobjecttype149033* LOC1;
	nimfr("reduce", "packsdl.nim")
	nimln(190, "packsdl.nim");
	nimln(190, "packsdl.nim");
	LOC1 = 0;
	LOC1 = crop_168050(asset, isurf, colorkey, cropt);
	reduce_151580((&(*asset).R), LOC1);
	popFrame();
}
N_NIMCALL(void, TMP647)(void* p, NI op) {
	TY167016* a;
	NI LOC1;
	a = (TY167016*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
N_NIMCALL(void, TMP653)(void* p, NI op) {
	TY167018* a;
	NI LOC1;
	a = (TY167018*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
N_NIMCALL(void, TMP654)(void* p, NI op) {
	sheetbundleHEX3Aobjecttype167013* a;
	a = (sheetbundleHEX3Aobjecttype167013*)p;
	nimGCvisit((void*)(*a).Asset, op);
	nimGCvisit((void*)(*a).Group, op);
	nimGCvisit((void*)(*a).Surf, op);
}

static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45671((&gch_47044.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51025)(tcell44933* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48667(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49429(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_50604)(tcell44933* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48667(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49429(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell44933* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48646(src);
		incref_51025(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell44933* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48646((*dest));
		decref_50604(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(sheetbundleHEX3Aobjecttype167013*, newbundle_168373)(TY154808* asa, TY167016* gra, TY167018* surfa) {
	sheetbundleHEX3Aobjecttype167013* result;
	NI gid;
	NI aid;
	nimfr("newBundle", "packsdl.nim")
	result = 0;
	nimln(194, "packsdl.nim");
	result = (sheetbundleHEX3Aobjecttype167013*) newObj((&NTI167007), sizeof(sheetbundleHEX3Aobjecttype167013));
	nimln(195, "packsdl.nim");
	if ((*result).Asset) nimGCunrefNoCycle((*result).Asset);
	(*result).Asset = (TY149663*) newSeqRC1((&NTI149663), 0);
	nimln(196, "packsdl.nim");
	if ((*result).Group) nimGCunrefNoCycle((*result).Group);
	(*result).Group = (TY167016*) newSeqRC1((&NTI167016), 0);
	nimln(197, "packsdl.nim");
	if ((*result).Surf) nimGCunrefNoCycle((*result).Surf);
	(*result).Surf = (TY167018*) newSeqRC1((&NTI167018), 0);
	nimln(198, "packsdl.nim");
	gid = 0;
	{
		assetgroupHEX3Aobjecttype149022* g0_168622;
		NI i_169044;
		NI l_169046;
		g0_168622 = 0;
		nimln(2986, "system.nim");
		i_169044 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_169046 = gra->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_169044 < l_169046)) goto LA3;
				nimln(2989, "system.nim");
				if ((NU)(i_169044) >= (NU)(gra->Sup.len)) raiseIndexError();
				g0_168622 = gra->data[i_169044];
				nimln(200, "packsdl.nim");
				(*g0_168622).Id = gid;
				nimln(201, "packsdl.nim");
				gid = addInt(gid, 1);
				nimln(202, "packsdl.nim");
				(*result).Group = (TY167016*) incrSeq(&((*result).Group)->Sup, sizeof(assetgroupHEX3Aobjecttype149022*));
				asgnRefNoCycle((void**) (&(*result).Group->data[(*result).Group->Sup.len-1]), g0_168622);
				nimln(2990, "system.nim");
				i_169044 = addInt(i_169044, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((gra->Sup.len == l_169046))) goto LA6;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP623));
				}
				LA6: ;
			} LA3: ;
		}
	}
	nimln(203, "packsdl.nim");
	if ((NU)(0) >= (NU)(asa->Sup.len)) raiseIndexError();
	if ((NU)(0) >= (NU)(asa->data[0]->Sup.len)) raiseIndexError();
	aid = (*asa->data[0]->data[0]).I;
	{
		TY149663* s0_168822;
		NI i_169056;
		NI l_169058;
		s0_168822 = 0;
		nimln(2986, "system.nim");
		i_169056 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_169058 = asa->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_169056 < l_169058)) goto LA10;
				nimln(2989, "system.nim");
				if ((NU)(i_169056) >= (NU)(asa->Sup.len)) raiseIndexError();
				s0_168822 = asa->data[i_169056];
				{
					assetHEX3Aobjecttype149027* a0_168835;
					NI i_169051;
					NI l_169053;
					a0_168835 = 0;
					nimln(2986, "system.nim");
					i_169051 = 0;
					nimln(2987, "system.nim");
					nimln(2987, "system.nim");
					l_169053 = s0_168822->Sup.len;
					{
						nimln(2988, "system.nim");
						while (1) {
							nimln(2988, "system.nim");
							if (!(i_169051 < l_169053)) goto LA13;
							nimln(2989, "system.nim");
							if ((NU)(i_169051) >= (NU)(s0_168822->Sup.len)) raiseIndexError();
							a0_168835 = s0_168822->data[i_169051];
							nimln(206, "packsdl.nim");
							(*a0_168835).I = aid;
							nimln(206, "packsdl.nim");
							aid = addInt(aid, 1);
							nimln(207, "packsdl.nim");
							(*result).Asset = (TY149663*) incrSeq(&((*result).Asset)->Sup, sizeof(assetHEX3Aobjecttype149027*));
							asgnRef((void**) (&(*result).Asset->data[(*result).Asset->Sup.len-1]), a0_168835);
							nimln(2990, "system.nim");
							i_169051 = addInt(i_169051, 1);
							nimln(2991, "system.nim");
							{
								nimln(2991, "system.nim");
								nimln(2991, "system.nim");
								nimln(2991, "system.nim");
								if (!!((s0_168822->Sup.len == l_169053))) goto LA16;
								nimln(2991, "system.nim");
								failedassertimpl_86825(((NimStringDesc*) &TMP623));
							}
							LA16: ;
						} LA13: ;
					}
				}
				nimln(2990, "system.nim");
				i_169056 = addInt(i_169056, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((asa->Sup.len == l_169058))) goto LA20;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP623));
				}
				LA20: ;
			} LA10: ;
		}
	}
	{
		surface132715* s1_169022;
		NI i_169062;
		NI l_169064;
		s1_169022 = 0;
		nimln(2986, "system.nim");
		i_169062 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_169064 = surfa->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_169062 < l_169064)) goto LA24;
				nimln(2989, "system.nim");
				if ((NU)(i_169062) >= (NU)(surfa->Sup.len)) raiseIndexError();
				s1_169022 = surfa->data[i_169062];
				nimln(209, "packsdl.nim");
				(*result).Surf = (TY167018*) incrSeq(&((*result).Surf)->Sup, sizeof(surface132715*));
				(*result).Surf->data[(*result).Surf->Sup.len-1] = s1_169022;
				nimln(2990, "system.nim");
				i_169062 = addInt(i_169062, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((surfa->Sup.len == l_169064))) goto LA27;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP623));
				}
				LA27: ;
			} LA24: ;
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdlInit)(void) {
	nimfr("packsdl", "packsdl.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_packsdlDatInit)(void) {
static TNimNode* TMP646[3];
static TNimNode TMP527[4];
NTI167013.size = sizeof(sheetbundleHEX3Aobjecttype167013);
NTI167013.kind = 18;
NTI167013.base = 0;
NTI167013.flags = 2;
TMP646[0] = &TMP527[1];
TMP527[1].kind = 1;
TMP527[1].offset = offsetof(sheetbundleHEX3Aobjecttype167013, Asset);
TMP527[1].typ = (&NTI149663);
TMP527[1].name = "asset";
TMP646[1] = &TMP527[2];
NTI167016.size = sizeof(TY167016*);
NTI167016.kind = 24;
NTI167016.base = (&NTI149009);
NTI167016.flags = 2;
NTI167016.marker = TMP647;
TMP527[2].kind = 1;
TMP527[2].offset = offsetof(sheetbundleHEX3Aobjecttype167013, Group);
TMP527[2].typ = (&NTI167016);
TMP527[2].name = "group";
TMP646[2] = &TMP527[3];
NTI167018.size = sizeof(TY167018*);
NTI167018.kind = 24;
NTI167018.base = (&NTI132713);
NTI167018.flags = 2;
NTI167018.marker = TMP653;
TMP527[3].kind = 1;
TMP527[3].offset = offsetof(sheetbundleHEX3Aobjecttype167013, Surf);
TMP527[3].typ = (&NTI167018);
TMP527[3].name = "surf";
TMP527[0].len = 3; TMP527[0].kind = 2; TMP527[0].sons = &TMP646[0];
NTI167013.node = &TMP527[0];
NTI167007.size = sizeof(sheetbundleHEX3Aobjecttype167013*);
NTI167007.kind = 22;
NTI167007.base = (&NTI167013);
NTI167007.flags = 2;
NTI167007.marker = TMP654;
}

