/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\packsdleasy.o c:\dropbox\2015\nim\packer\example\nimcache\packsdleasy.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct surface132715 surface132715;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct TY176096 TY176096;
typedef struct bundletup176025 bundletup176025;
typedef struct sheetbundleHEX3Aobjecttype167013 sheetbundleHEX3Aobjecttype167013;
typedef struct assetgroupHEX3Aobjecttype149022 assetgroupHEX3Aobjecttype149022;
typedef struct TY154808 TY154808;
typedef struct TY149663 TY149663;
typedef struct assetHEX3Aobjecttype149027 assetHEX3Aobjecttype149027;
typedef struct TY167016 TY167016;
typedef struct TY167018 TY167018;
typedef struct rect149007 rect149007;
typedef struct TY149020 TY149020;
typedef struct dataentry149005 dataentry149005;
typedef struct TY149048 TY149048;
typedef struct slice86066 slice86066;
typedef struct jsonnodeobj119051 jsonnodeobj119051;
typedef struct TY119066 TY119066;
typedef struct TY119067 TY119067;
typedef struct TY119071 TY119071;
typedef struct orderedtable176685 orderedtable176685;
typedef struct orderedkeyvaluepairseq176688 orderedkeyvaluepairseq176688;
typedef struct orderedkeyvaluepair176691 orderedkeyvaluepair176691;
typedef struct orderedtable176715 orderedtable176715;
typedef struct orderedkeyvaluepairseq176718 orderedkeyvaluepairseq176718;
typedef struct orderedkeyvaluepair176721 orderedkeyvaluepair176721;
typedef struct assetjsonmanifest176679 assetjsonmanifest176679;
typedef struct pixelformat132709 pixelformat132709;
typedef struct rect132277 rect132277;
typedef struct blitmapptrHEX3Aobjecttype132757 blitmapptrHEX3Aobjecttype132757;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
typedef struct palette132707 palette132707;
typedef struct color132705 color132705;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(surface132715*, TY146240) (NCSTRING file);
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef N_CDECL_PTR(NCSTRING, TY143102) (void);
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
struct bundletup176025 {
surface132715* Field0;
sheetbundleHEX3Aobjecttype167013* Field1;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  sheetbundleHEX3Aobjecttype167013  {
TY149663* Asset;
TY167016* Group;
TY167018* Surf;
};
struct  dataentry149005  {
NimStringDesc* K;
NI V;
};
struct  rect149007  {
NI X;
NI Y;
NI W;
NI H;
TY149020* D;
};
struct  assetgroupHEX3Aobjecttype149022  {
rect149007 Rect;
NimStringDesc* Name;
NI Counter;
NI Id;
};
typedef NimStringDesc* TY176237[3];
struct  slice86066  {
NI A;
NI B;
};
struct TY119067 {
NimStringDesc* Field0;
jsonnodeobj119051* Field1;
};
struct  jsonnodeobj119051  {
NU8 Kind;
union {
struct {NimStringDesc* Str;
} S1;
struct {NI64 Num;
} S2;
struct {NF Fnum;
} S3;
struct {NIM_BOOL Bval;
} S4;
struct {TY119066* Fields;
} S6;
struct {TY119071* Elems;
} S7;
} kindU;
};
struct orderedkeyvaluepair176691 {
NU8 Field0;
NI Field1;
NI Field2;
assetHEX3Aobjecttype149027* Field3;
};
struct  orderedtable176685  {
orderedkeyvaluepairseq176688* Data;
NI Counter;
NI First;
NI Last;
};
struct orderedkeyvaluepair176721 {
NU8 Field0;
NI Field1;
NI Field2;
assetgroupHEX3Aobjecttype149022* Field3;
};
struct  orderedtable176715  {
orderedkeyvaluepairseq176718* Data;
NI Counter;
NI First;
NI Last;
};
struct assetjsonmanifest176679 {
orderedtable176685 Field0;
orderedtable176715 Field1;
jsonnodeobj119051* Field2;
};
struct  assetHEX3Aobjecttype149027  {
assetHEX3Aobjecttype149027* P;
NI I;
assetgroupHEX3Aobjecttype149022* G;
TY149048* R;
};
typedef rect149007 TY150226[1];
struct rect132277 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  surface132715  {
NU32 Flags;
pixelformat132709* Format;
NI32 W;
NI32 H;
NI32 Pitch;
void* Pixels;
void* Userdata;
NI32 Locked;
void* Lockdata;
rect132277 Cliprect;
blitmapptrHEX3Aobjecttype132757* Map;
int Refcount;
};
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
typedef NU8 TY132739[2];
struct  pixelformat132709  {
NU32 Format;
palette132707* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY132739 Padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int Refcount;
pixelformat132709* Next;
};
struct  blitmapptrHEX3Aobjecttype132757  {
char dummy;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
struct  palette132707  {
int Ncolors;
color132705* Colors;
NU32 Version;
int Refcount;
};
struct color132705 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
struct TY176096 {
  TGenericSeq Sup;
  bundletup176025 data[SEQ_DECL_SIZE];
};
struct TY149663 {
  TGenericSeq Sup;
  assetHEX3Aobjecttype149027* data[SEQ_DECL_SIZE];
};
struct TY154808 {
  TGenericSeq Sup;
  TY149663* data[SEQ_DECL_SIZE];
};
struct TY167016 {
  TGenericSeq Sup;
  assetgroupHEX3Aobjecttype149022* data[SEQ_DECL_SIZE];
};
struct TY167018 {
  TGenericSeq Sup;
  surface132715* data[SEQ_DECL_SIZE];
};
struct TY149020 {
  TGenericSeq Sup;
  dataentry149005 data[SEQ_DECL_SIZE];
};
struct TY149048 {
  TGenericSeq Sup;
  rect149007 data[SEQ_DECL_SIZE];
};
struct TY119066 {
  TGenericSeq Sup;
  TY119067 data[SEQ_DECL_SIZE];
};
struct TY119071 {
  TGenericSeq Sup;
  jsonnodeobj119051* data[SEQ_DECL_SIZE];
};
struct orderedkeyvaluepairseq176688 {
  TGenericSeq Sup;
  orderedkeyvaluepair176691 data[SEQ_DECL_SIZE];
};
struct orderedkeyvaluepairseq176718 {
  TGenericSeq Sup;
  orderedkeyvaluepair176721 data[SEQ_DECL_SIZE];
};
N_NIMCALL(surface132715*, loadimage_176031)(NimStringDesc* filename);
N_NIMCALL(Exception*, new_155056)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(TY176096*, packbundle_176092)(sheetbundleHEX3Aobjecttype167013* abd, assetgroupHEX3Aobjecttype149022* og);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP688)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(TY154808*, multipackscanline_154763)(assetgroupHEX3Aobjecttype149022* g, TY149663* assets, NI skipstride, NIM_BOOL speedy, NIM_BOOL sort);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(surface132715*, newsurface_167415)(rect149007* rect);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_81404, TNimType* mt);
N_NIMCALL(void, copy_167761)(surface132715* dest, sheetbundleHEX3Aobjecttype167013* sbd);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_86825)(NimStringDesc* msg);
N_NIMCALL(TY176096*, tilebundle_176193)(sheetbundleHEX3Aobjecttype167013* abd, assetgroupHEX3Aobjecttype149022* og, NI w0, NI h0);
N_NIMCALL(TY149663*, fitsintilesize_151674)(TY149663* assets, NI w0, NI h0);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, HEX24_149470)(assetHEX3Aobjecttype149027* p);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(TY149048*, rhoriztiling_150172)(assetgroupHEX3Aobjecttype149022* g, NI tw, NI th, NI iw, NI ih, NI sx, NI sy);
N_NIMCALL(TY149663*, HEX5BHEX5D_154069)(TY149663* s_154075, slice86066 x_154080);
static N_INLINE(slice86066, HEX2EHEX2E_92098)(NI a_92102, NI b_92104);
N_NIMCALL(TY149663*, packtorectsc_151836)(assetgroupHEX3Aobjecttype149022* g, TY149663* assets, TY149048* rects);
N_NIMCALL(jsonnodeobj119051*, jsondataentry_176438)(TY149020* ds);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_149117)(TY149020* x_149123, TY149020* y_149128);
N_NIMCALL(jsonnodeobj119051*, newjarray_119398)(void);
N_NIMCALL(void, add_121871)(jsonnodeobj119051* father, jsonnodeobj119051* child);
N_NIMCALL(jsonnodeobj119051*, newjstring_119114)(NimStringDesc* s);
N_NIMCALL(jsonnodeobj119051*, newjint_119194)(NI64 n);
N_NIMCALL(TY149020*, ofjsondataentry_176497)(jsonnodeobj119051* ja);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NIMCALL(void, newdata_150161)(NimStringDesc* k, NI v, dataentry149005* Result);
N_NIMCALL(jsonnodeobj119051*, HEX5BHEX5D_121246)(jsonnodeobj119051* node, NI index);
N_NIMCALL(NI64, chckRange64)(NI64 i, NI64 a, NI64 b);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(jsonnodeobj119051*, jsonrect_176599)(rect149007* r0);
N_NIMCALL(void, ofjsonrect_176611)(jsonnodeobj119051* ja, rect149007* Result);
N_NIMCALL(void, newrect_149915)(NI x, NI y, NI w, NI h, TY149020* d, rect149007* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, initorderedtable_176751)(NI initialsize_176756, orderedtable176685* Result);
N_NIMCALL(void, initorderedtable_176822)(NI initialsize_176827, orderedtable176715* Result);
N_NIMCALL(NIM_BOOL, haskey_177038)(orderedtable176685 t_177045, NI key_177048);
N_NIMCALL(NI, rawget_177052)(orderedtable176685 t_177059, NI key_177062);
N_NIMCALL(void, HEX5BHEX5DHEX3D_177110)(orderedtable176685* t_177119, NI key_177123, assetHEX3Aobjecttype149027* val_177125);
N_NIMCALL(void, enlarge_177155)(orderedtable176685* t_177164);
N_NIMCALL(void, rawinsert_177214)(orderedtable176685* t_177223, orderedkeyvaluepairseq176688** data_177231, NI key_177235, assetHEX3Aobjecttype149027* val_177237);
N_NIMCALL(NIM_BOOL, haskey_177351)(orderedtable176715 t_177358, NI key_177361);
N_NIMCALL(NI, rawget_177365)(orderedtable176715 t_177372, NI key_177375);
N_NIMCALL(assetgroupHEX3Aobjecttype149022*, HEX5BHEX5D_177412)(orderedtable176715 t_177419, NI key_177422);
N_NIMCALL(void, HEX5BHEX5DHEX3D_177485)(orderedtable176715* t_177494, NI key_177498, assetgroupHEX3Aobjecttype149022* val_177500);
N_NIMCALL(void, enlarge_177530)(orderedtable176715* t_177539);
N_NIMCALL(void, rawinsert_177589)(orderedtable176715* t_177598, orderedkeyvaluepairseq176718** data_177606, NI key_177610, assetgroupHEX3Aobjecttype149022* val_177612);
N_NIMCALL(void, savejson_176744)(TY149663* asset, NimStringDesc* fn, assetjsonmanifest176679* Result);
N_NIMCALL(jsonnodeobj119051*, newjobject_119339)(void);
N_NIMCALL(void, add_122048)(jsonnodeobj119051* obj, NimStringDesc* key, jsonnodeobj119051* val);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, add_177815)(orderedtable176715* t_177824, NI key_177828, assetgroupHEX3Aobjecttype149022* val_177830);
N_NIMCALL(TY149048*, newseq_177950)(NI len_177954);
N_NIMCALL(void, loadjson_177754)(jsonnodeobj119051* jobj, assetjsonmanifest176679* Result);
N_NIMCALL(jsonnodeobj119051*, HEX5BHEX5D_120709)(jsonnodeobj119051* node, NimStringDesc* name);
N_NIMCALL(NI, len_120649)(jsonnodeobj119051* n);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(assetHEX3Aobjecttype149027*, newasset_149044)(NI i, assetgroupHEX3Aobjecttype149022* g, TY149048* r);
N_NIMCALL(TY149663*, newseq_151270)(NI len_151274);
N_NIMCALL(void, reduce_168360)(assetHEX3Aobjecttype149027* asset, surface132715* isurf, NU32 colorkey, NU8 cropt);
N_NIMCALL(NIM_BOOL, isempty_168348)(assetHEX3Aobjecttype149027* asset, surface132715* surf, NU32 colorkey);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51025)(tcell44933* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c);
static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c);
N_NOINLINE(void, incl_45671)(tcellset44945* s, tcell44933* cell);
static N_INLINE(void, decref_50604)(tcell44933* c);
STRING_LITERAL(TMP685, "Failed to load \"", 16);
STRING_LITERAL(TMP686, "\": ", 3);
STRING_LITERAL(TMP689, "(system.len|system.len|system.len|system.len|system.len|system."
"len|...)(a) (system.==|system.==|system.==|system.==|system.==|s"
"ystem.==|system.==|system.==|system.==|system.==|system.==|syste"
"m.==|system.==|system.==|system.==|system.==|system.==|system.=="
"|system.==|system.==|...)\015\012    L seq modified while iterating ov"
"er it", 324);
STRING_LITERAL(TMP690, "$1 doesn\'t fit in tile size $2,$3", 33);
STRING_LITERAL(TMP691, "node.kind == JArray ", 20);
STRING_LITERAL(TMP692, "elems", 5);
STRING_LITERAL(TMP693, "str", 3);
STRING_LITERAL(TMP694, "num", 3);
STRING_LITERAL(TMP705, "collision: two different assets identified #", 44);
STRING_LITERAL(TMP706, "i", 1);
STRING_LITERAL(TMP707, "g", 1);
STRING_LITERAL(TMP708, "r", 1);
STRING_LITERAL(TMP709, "collision: two different output groups identified #", 51);
STRING_LITERAL(TMP710, ": ", 2);
STRING_LITERAL(TMP711, ", ", 2);
STRING_LITERAL(TMP712, "rect", 4);
STRING_LITERAL(TMP713, "name", 4);
STRING_LITERAL(TMP714, "counter", 7);
STRING_LITERAL(TMP715, "id", 2);
STRING_LITERAL(TMP716, "group", 5);
STRING_LITERAL(TMP717, "asset", 5);
extern TY146240 Dl_146239;
extern TY143102 Dl_143101;
extern TFrame* frameptr_16242;
extern tgcheap47016 gch_47044;
TNimType NTI176025; /* BundleTup */
extern TNimType NTI132713; /* SurfacePtr */
extern TNimType NTI167007; /* SheetBundle */
TNimType NTI176096; /* seq[BundleTup] */
extern TNimType NTI167016; /* seq[AssetGroup] */
extern TNimType NTI167018; /* seq[SurfacePtr] */
extern TNimType NTI149663; /* seq[Asset] */
extern TNimType NTI149020; /* seq[DataEntry] */
extern TNimType NTI149007; /* Rect */
extern TNimType NTI176688; /* OrderedKeyValuePairSeq */
extern TNimType NTI176718; /* OrderedKeyValuePairSeq */
extern TNimType NTI149009; /* AssetGroup */
extern TNimType NTI149048; /* seq[Rect] */

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(surface132715*, loadimage_176031)(NimStringDesc* filename) {
	surface132715* result;
	surface132715* suce;
	nimfr("loadImage", "packsdleasy.nim")
	result = 0;
	nimln(12, "packsdleasy.nim");
	suce = Dl_146239(filename->data);
	nimln(13, "packsdleasy.nim");
	{
		Exception* err;
		NimStringDesc* LOC5;
		NCSTRING LOC6;
		NimStringDesc* LOC7;
		nimln(13, "packsdleasy.nim");
		if (!(suce == NIM_NIL)) goto LA3;
		nimln(14, "packsdleasy.nim");
		err = new_155056();
		nimln(15, "packsdleasy.nim");
		nimln(15, "packsdleasy.nim");
		LOC5 = 0;
		nimln(15, "packsdleasy.nim");
		nimln(15, "packsdleasy.nim");
		LOC6 = 0;
		LOC6 = Dl_143101();
		LOC7 = 0;
		LOC7 = cstrToNimstr(LOC6);
		LOC5 = rawNewString(filename->Sup.len + LOC7->Sup.len + 19);
appendString(LOC5, ((NimStringDesc*) &TMP685));
appendString(LOC5, filename);
appendString(LOC5, ((NimStringDesc*) &TMP686));
appendString(LOC5, LOC7);
		asgnRefNoCycle((void**) (&(*err).message), LOC5);
		nimln(16, "packsdleasy.nim");
		raiseException((Exception*)err, "Exception");
	}
	LA3: ;
	nimln(17, "packsdleasy.nim");
	nimln(17, "packsdleasy.nim");
	result = suce;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP688)(void* p, NI op) {
	TY176096* a;
	NI LOC1;
	a = (TY176096*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(TY176096*, packbundle_176092)(sheetbundleHEX3Aobjecttype167013* abd, assetgroupHEX3Aobjecttype149022* og) {
	TY176096* result;
	TY154808* aseq;
	nimfr("packBundle", "packsdleasy.nim")
	result = 0;
	nimln(23, "packsdleasy.nim");
	result = (TY176096*) newSeq((&NTI176096), 0);
	nimln(24, "packsdleasy.nim");
	aseq = multipackscanline_154763(og, (*abd).Asset, 1, NIM_FALSE, NIM_TRUE);
	{
		TY149663* a0_176131;
		NI i_176175;
		NI l_176177;
		a0_176131 = 0;
		nimln(2986, "system.nim");
		i_176175 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_176177 = aseq->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				surface132715* osurf;
				sheetbundleHEX3Aobjecttype167013* sb0;
				bundletup176025 LOC4;
				nimln(2988, "system.nim");
				if (!(i_176175 < l_176177)) goto LA3;
				nimln(2989, "system.nim");
				if ((NU)(i_176175) >= (NU)(aseq->Sup.len)) raiseIndexError();
				a0_176131 = aseq->data[i_176175];
				nimln(26, "packsdleasy.nim");
				osurf = newsurface_167415((&(*og).Rect));
				sb0 = 0;
				nimln(27, "packsdleasy.nim");
				sb0 = (sheetbundleHEX3Aobjecttype167013*) newObj((&NTI167007), sizeof(sheetbundleHEX3Aobjecttype167013));
				nimln(28, "packsdleasy.nim");
				genericSeqAssign((&(*sb0).Group), (*abd).Group, (&NTI167016));
				nimln(29, "packsdleasy.nim");
				genericSeqAssign((&(*sb0).Surf), (*abd).Surf, (&NTI167018));
				nimln(30, "packsdleasy.nim");
				genericSeqAssign((&(*sb0).Asset), a0_176131, (&NTI149663));
				nimln(31, "packsdleasy.nim");
				copy_167761(osurf, sb0);
				nimln(32, "packsdleasy.nim");
				memset((void*)(&LOC4), 0, sizeof(LOC4));
				LOC4.Field0 = osurf;
				LOC4.Field1 = sb0;
				result = (TY176096*) incrSeq(&(result)->Sup, sizeof(bundletup176025));
				result->data[result->Sup.len-1].Field0 = LOC4.Field0;
				asgnRefNoCycle((void**) (&result->data[result->Sup.len-1].Field1), LOC4.Field1);
				nimln(2990, "system.nim");
				i_176175 = addInt(i_176175, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((aseq->Sup.len == l_176177))) goto LA7;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP689));
				}
				LA7: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(slice86066, HEX2EHEX2E_92098)(NI a_92102, NI b_92104) {
	slice86066 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_92102;
	nimln(227, "system.nim");
	result.B = b_92104;
	popFrame();
	return result;
}

N_NIMCALL(TY176096*, tilebundle_176193)(sheetbundleHEX3Aobjecttype167013* abd, assetgroupHEX3Aobjecttype149022* og, NI w0, NI h0) {
	TY176096* result;
	TY149663* remainder;
	nimfr("tileBundle", "packsdleasy.nim")
	result = 0;
	nimln(34, "packsdleasy.nim");
	result = (TY176096*) newSeq((&NTI176096), 0);
	nimln(35, "packsdleasy.nim");
	genericSeqAssign((&remainder), (*abd).Asset, (&NTI149663));
	{
		assetHEX3Aobjecttype149027* r0_176234;
		TY149663* HEX3Atmp_176408;
		NI i_176411;
		NI l_176413;
		r0_176234 = 0;
		HEX3Atmp_176408 = 0;
		nimln(36, "packsdleasy.nim");
		HEX3Atmp_176408 = fitsintilesize_151674(remainder, w0, h0);
		nimln(2986, "system.nim");
		i_176411 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_176413 = HEX3Atmp_176408->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				TY176237 LOC4;
				NimStringDesc* LOC5;
				nimln(2988, "system.nim");
				if (!(i_176411 < l_176413)) goto LA3;
				nimln(2989, "system.nim");
				if ((NU)(i_176411) >= (NU)(HEX3Atmp_176408->Sup.len)) raiseIndexError();
				r0_176234 = HEX3Atmp_176408->data[i_176411];
				nimln(37, "packsdleasy.nim");
				nimln(37, "packsdleasy.nim");
				nimln(37, "packsdleasy.nim");
				memset((void*)LOC4, 0, sizeof(LOC4));
				nimln(37, "packsdleasy.nim");
				LOC4[0] = HEX24_149470(r0_176234);
				nimln(37, "packsdleasy.nim");
				LOC4[1] = nimIntToStr(w0);
				nimln(37, "packsdleasy.nim");
				LOC4[2] = nimIntToStr(h0);
				LOC5 = 0;
				LOC5 = nsuFormatOpenArray(((NimStringDesc*) &TMP690), LOC4, 3);
				printf("%s\015\012", (LOC5)->data);
				nimln(2990, "system.nim");
				i_176411 = addInt(i_176411, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((HEX3Atmp_176408->Sup.len == l_176413))) goto LA8;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP689));
				}
				LA8: ;
			} LA3: ;
		}
	}
	{
		nimln(38, "packsdleasy.nim");
		while (1) {
			TY149048* tiling0;
			TY149663* working;
			TY149663* a0;
			surface132715* osurf;
			sheetbundleHEX3Aobjecttype167013* sb0;
			bundletup176025 LOC19;
			nimln(38, "packsdleasy.nim");
			nimln(38, "packsdleasy.nim");
			if (!(0 < remainder->Sup.len)) goto LA11;
			nimln(39, "packsdleasy.nim");
			tiling0 = rhoriztiling_150172(og, w0, h0, 0, 0, 0, 0);
			working = 0;
			nimln(41, "packsdleasy.nim");
			{
				nimln(41, "packsdleasy.nim");
				nimln(41, "packsdleasy.nim");
				nimln(41, "packsdleasy.nim");
				if (!(remainder->Sup.len <= tiling0->Sup.len)) goto LA14;
				nimln(42, "packsdleasy.nim");
				genericSeqAssign((&working), remainder, (&NTI149663));
				nimln(43, "packsdleasy.nim");
				remainder = (TY149663*) newSeq((&NTI149663), 0);
			}
			goto LA12;
			LA14: ;
			{
				slice86066 LOC17;
				slice86066 LOC18;
				nimln(45, "packsdleasy.nim");
				nimln(45, "packsdleasy.nim");
				nimln(45, "packsdleasy.nim");
				LOC17 = HEX2EHEX2E_92098(0, (tiling0->Sup.len-1));
				working = HEX5BHEX5D_154069(remainder, LOC17);
				nimln(46, "packsdleasy.nim");
				nimln(46, "packsdleasy.nim");
				nimln(46, "packsdleasy.nim");
				nimln(46, "packsdleasy.nim");
				LOC18 = HEX2EHEX2E_92098(tiling0->Sup.len, (remainder->Sup.len-1));
				remainder = HEX5BHEX5D_154069(remainder, LOC18);
			}
			LA12: ;
			nimln(47, "packsdleasy.nim");
			a0 = packtorectsc_151836(og, working, tiling0);
			nimln(48, "packsdleasy.nim");
			osurf = newsurface_167415((&(*og).Rect));
			sb0 = 0;
			nimln(49, "packsdleasy.nim");
			sb0 = (sheetbundleHEX3Aobjecttype167013*) newObj((&NTI167007), sizeof(sheetbundleHEX3Aobjecttype167013));
			nimln(50, "packsdleasy.nim");
			genericSeqAssign((&(*sb0).Group), (*abd).Group, (&NTI167016));
			nimln(51, "packsdleasy.nim");
			genericSeqAssign((&(*sb0).Surf), (*abd).Surf, (&NTI167018));
			nimln(52, "packsdleasy.nim");
			genericSeqAssign((&(*sb0).Asset), a0, (&NTI149663));
			nimln(53, "packsdleasy.nim");
			copy_167761(osurf, sb0);
			nimln(54, "packsdleasy.nim");
			asgnRefNoCycle((void**) (&(*sb0).Asset), packtorectsc_151836(og, working, tiling0));
			nimln(55, "packsdleasy.nim");
			memset((void*)(&LOC19), 0, sizeof(LOC19));
			LOC19.Field0 = osurf;
			LOC19.Field1 = sb0;
			result = (TY176096*) incrSeq(&(result)->Sup, sizeof(bundletup176025));
			result->data[result->Sup.len-1].Field0 = LOC19.Field0;
			asgnRefNoCycle((void**) (&result->data[result->Sup.len-1].Field1), LOC19.Field1);
		} LA11: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(jsonnodeobj119051*, jsondataentry_176438)(TY149020* ds) {
	jsonnodeobj119051* result;
	jsonnodeobj119051* ja0;
	nimfr("JSONDataEntry", "packsdleasy.nim")
	result = 0;
	nimln(58, "packsdleasy.nim");
	{
		NIM_BOOL LOC3;
		nimln(58, "packsdleasy.nim");
		LOC3 = 0;
		LOC3 = HEX3DHEX3D_149117(ds, NIM_NIL);
		if (!LOC3) goto LA4;
		nimln(59, "packsdleasy.nim");
		nimln(59, "packsdleasy.nim");
		result = newjarray_119398();
		goto BeforeRet;
	}
	LA4: ;
	nimln(60, "packsdleasy.nim");
	ja0 = newjarray_119398();
	{
		dataentry149005 d0_176474;
		NI i_176479;
		NI l_176481;
		memset((void*)(&d0_176474), 0, sizeof(d0_176474));
		nimln(2986, "system.nim");
		i_176479 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_176481 = ds->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				jsonnodeobj119051* ja1;
				jsonnodeobj119051* LOC9;
				jsonnodeobj119051* LOC10;
				nimln(2988, "system.nim");
				if (!(i_176479 < l_176481)) goto LA8;
				nimln(2989, "system.nim");
				if ((NU)(i_176479) >= (NU)(ds->Sup.len)) raiseIndexError();
				d0_176474.K = ds->data[i_176479].K;
				d0_176474.V = ds->data[i_176479].V;
				nimln(62, "packsdleasy.nim");
				ja1 = newjarray_119398();
				nimln(63, "packsdleasy.nim");
				nimln(63, "packsdleasy.nim");
				LOC9 = 0;
				LOC9 = newjstring_119114(d0_176474.K);
				add_121871(ja1, LOC9);
				nimln(64, "packsdleasy.nim");
				nimln(64, "packsdleasy.nim");
				LOC10 = 0;
				LOC10 = newjint_119194(((NI64) (d0_176474.V)));
				add_121871(ja1, LOC10);
				nimln(65, "packsdleasy.nim");
				add_121871(ja0, ja1);
				nimln(2990, "system.nim");
				i_176479 = addInt(i_176479, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((ds->Sup.len == l_176481))) goto LA13;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP689));
				}
				LA13: ;
			} LA8: ;
		}
	}
	nimln(66, "packsdleasy.nim");
	nimln(66, "packsdleasy.nim");
	result = ja0;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell44933* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48646(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50204(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(TY149020*, ofjsondataentry_176497)(jsonnodeobj119051* ja) {
	TY149020* result;
	nimfr("ofJSONDataEntry", "packsdleasy.nim")
	result = 0;
	nimln(68, "packsdleasy.nim");
	result = (TY149020*) newSeq((&NTI149020), 0);
	{
		jsonnodeobj119051* d0_176523;
		d0_176523 = 0;
		nimln(871, "json.nim");
		{
			nimln(871, "json.nim");
			nimln(871, "json.nim");
			if (!!(((*ja).Kind == ((NU8) 6)))) goto LA4;
			nimln(871, "json.nim");
			failedassertimpl_86825(((NimStringDesc*) &TMP691));
		}
		LA4: ;
		{
			jsonnodeobj119051* i_176574;
			TY119071* HEX3Atmp_176576;
			NI i_176578;
			NI l_176580;
			i_176574 = 0;
			HEX3Atmp_176576 = 0;
			nimln(872, "json.nim");
			if (!(((64 &(1<<(((*ja).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP692));
			HEX3Atmp_176576 = (*ja).kindU.S7.Elems;
			nimln(2986, "system.nim");
			i_176578 = 0;
			nimln(2987, "system.nim");
			nimln(2987, "system.nim");
			l_176580 = HEX3Atmp_176576->Sup.len;
			{
				nimln(2988, "system.nim");
				while (1) {
					jsonnodeobj119051* LOC9;
					jsonnodeobj119051* LOC10;
					dataentry149005 LOC11;
					NimStringDesc* LOC12;
					nimln(2988, "system.nim");
					if (!(i_176578 < l_176580)) goto LA8;
					nimln(2989, "system.nim");
					if ((NU)(i_176578) >= (NU)(HEX3Atmp_176576->Sup.len)) raiseIndexError();
					i_176574 = HEX3Atmp_176576->data[i_176578];
					nimln(872, "json.nim");
					d0_176523 = i_176574;
					nimln(70, "packsdleasy.nim");
					nimln(70, "packsdleasy.nim");
					nimln(70, "packsdleasy.nim");
					LOC9 = 0;
					LOC9 = HEX5BHEX5D_121246(d0_176523, 0);
					if (!(((16 &(1<<(((*LOC9).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP693));
					nimln(70, "packsdleasy.nim");
					LOC10 = 0;
					LOC10 = HEX5BHEX5D_121246(d0_176523, 1);
					if (!(((4 &(1<<(((*LOC10).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP694));
					memset((void*)(&LOC11), 0, sizeof(LOC11));
					newdata_150161((*LOC9).kindU.S1.Str, ((NI)chckRange64((*LOC10).kindU.S2.Num, (-2147483647 -1), 2147483647)), (&LOC11));
					result = (TY149020*) incrSeq(&(result)->Sup, sizeof(dataentry149005));
					LOC12 = 0;
					LOC12 = result->data[result->Sup.len-1].K; result->data[result->Sup.len-1].K = copyStringRC1(LOC11.K);
					if (LOC12) nimGCunrefNoCycle(LOC12);
					result->data[result->Sup.len-1].V = LOC11.V;
					nimln(2990, "system.nim");
					i_176578 = addInt(i_176578, 1);
					nimln(2991, "system.nim");
					{
						nimln(2991, "system.nim");
						nimln(2991, "system.nim");
						nimln(2991, "system.nim");
						if (!!((HEX3Atmp_176576->Sup.len == l_176580))) goto LA15;
						nimln(2991, "system.nim");
						failedassertimpl_86825(((NimStringDesc*) &TMP689));
					}
					LA15: ;
				} LA8: ;
			}
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(jsonnodeobj119051*, jsonrect_176599)(rect149007* r0) {
	jsonnodeobj119051* result;
	jsonnodeobj119051* ja;
	jsonnodeobj119051* LOC1;
	jsonnodeobj119051* LOC2;
	jsonnodeobj119051* LOC3;
	jsonnodeobj119051* LOC4;
	jsonnodeobj119051* LOC5;
	nimfr("JSONRect", "packsdleasy.nim")
	result = 0;
	nimln(72, "packsdleasy.nim");
	ja = newjarray_119398();
	nimln(73, "packsdleasy.nim");
	nimln(73, "packsdleasy.nim");
	LOC1 = 0;
	LOC1 = newjint_119194(((NI64) ((*r0).X)));
	add_121871(ja, LOC1);
	nimln(74, "packsdleasy.nim");
	nimln(74, "packsdleasy.nim");
	LOC2 = 0;
	LOC2 = newjint_119194(((NI64) ((*r0).Y)));
	add_121871(ja, LOC2);
	nimln(75, "packsdleasy.nim");
	nimln(75, "packsdleasy.nim");
	LOC3 = 0;
	LOC3 = newjint_119194(((NI64) ((*r0).W)));
	add_121871(ja, LOC3);
	nimln(76, "packsdleasy.nim");
	nimln(76, "packsdleasy.nim");
	LOC4 = 0;
	LOC4 = newjint_119194(((NI64) ((*r0).H)));
	add_121871(ja, LOC4);
	nimln(77, "packsdleasy.nim");
	nimln(77, "packsdleasy.nim");
	LOC5 = 0;
	LOC5 = jsondataentry_176438((*r0).D);
	add_121871(ja, LOC5);
	nimln(78, "packsdleasy.nim");
	nimln(78, "packsdleasy.nim");
	result = ja;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, ofjsonrect_176611)(jsonnodeobj119051* ja, rect149007* Result) {
	jsonnodeobj119051* LOC1;
	jsonnodeobj119051* LOC2;
	jsonnodeobj119051* LOC3;
	jsonnodeobj119051* LOC4;
	jsonnodeobj119051* LOC5;
	TY149020* LOC6;
	nimfr("ofJSONRect", "packsdleasy.nim")
	nimln(80, "packsdleasy.nim");
	nimln(80, "packsdleasy.nim");
	nimln(80, "packsdleasy.nim");
	LOC1 = 0;
	LOC1 = HEX5BHEX5D_121246(ja, 0);
	if (!(((4 &(1<<(((*LOC1).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP694));
	nimln(81, "packsdleasy.nim");
	LOC2 = 0;
	LOC2 = HEX5BHEX5D_121246(ja, 1);
	if (!(((4 &(1<<(((*LOC2).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP694));
	nimln(81, "packsdleasy.nim");
	LOC3 = 0;
	LOC3 = HEX5BHEX5D_121246(ja, 2);
	if (!(((4 &(1<<(((*LOC3).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP694));
	nimln(81, "packsdleasy.nim");
	LOC4 = 0;
	LOC4 = HEX5BHEX5D_121246(ja, 3);
	if (!(((4 &(1<<(((*LOC4).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP694));
	nimln(82, "packsdleasy.nim");
	nimln(82, "packsdleasy.nim");
	LOC5 = 0;
	LOC5 = HEX5BHEX5D_121246(ja, 4);
	LOC6 = 0;
	LOC6 = ofjsondataentry_176497(LOC5);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI149007));
	newrect_149915(((NI)chckRange64((*LOC1).kindU.S2.Num, (-2147483647 -1), 2147483647)), ((NI)chckRange64((*LOC2).kindU.S2.Num, (-2147483647 -1), 2147483647)), ((NI)chckRange64((*LOC3).kindU.S2.Num, (-2147483647 -1), 2147483647)), ((NI)chckRange64((*LOC4).kindU.S2.Num, (-2147483647 -1), 2147483647)), LOC6, Result);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, savejson_176744)(TY149663* asset, NimStringDesc* fn, assetjsonmanifest176679* Result) {
	orderedtable176685 atbl;
	orderedtable176715 gtbl;
	jsonnodeobj119051* ga;
	jsonnodeobj119051* aa;
	jsonnodeobj119051* jobj;
	nimfr("saveJSON", "packsdleasy.nim")
	memset((void*)(&atbl), 0, sizeof(atbl));
	nimln(91, "packsdleasy.nim");
	chckNil((void*)(&atbl));
	memset((void*)(&atbl), 0, sizeof(atbl));
	initorderedtable_176751(64, (&atbl));
	memset((void*)(&gtbl), 0, sizeof(gtbl));
	nimln(92, "packsdleasy.nim");
	chckNil((void*)(&gtbl));
	memset((void*)(&gtbl), 0, sizeof(gtbl));
	initorderedtable_176822(64, (&gtbl));
	nimln(93, "packsdleasy.nim");
	ga = newjarray_119398();
	nimln(94, "packsdleasy.nim");
	aa = newjarray_119398();
	{
		assetHEX3Aobjecttype149027* a0_177035;
		NI i_177727;
		NI l_177729;
		a0_177035 = 0;
		nimln(2986, "system.nim");
		i_177727 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_177729 = asset->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_177727 < l_177729)) goto LA3;
				nimln(2989, "system.nim");
				if ((NU)(i_177727) >= (NU)(asset->Sup.len)) raiseIndexError();
				a0_177035 = asset->data[i_177727];
				nimln(97, "packsdleasy.nim");
				{
					NIM_BOOL LOC6;
					Exception* ex;
					NimStringDesc* LOC9;
					NimStringDesc* LOC10;
					nimln(97, "packsdleasy.nim");
					LOC6 = 0;
					LOC6 = haskey_177038(atbl, (*a0_177035).I);
					if (!LOC6) goto LA7;
					nimln(98, "packsdleasy.nim");
					ex = new_155056();
					nimln(99, "packsdleasy.nim");
					nimln(99, "packsdleasy.nim");
					LOC9 = 0;
					nimln(99, "packsdleasy.nim");
					LOC10 = 0;
					LOC10 = nimIntToStr((*a0_177035).I);
					LOC9 = rawNewString(LOC10->Sup.len + 44);
appendString(LOC9, ((NimStringDesc*) &TMP705));
appendString(LOC9, LOC10);
					asgnRefNoCycle((void**) (&(*ex).message), LOC9);
					nimln(100, "packsdleasy.nim");
					raiseException((Exception*)ex, "Exception");
				}
				goto LA4;
				LA7: ;
				{
					jsonnodeobj119051* aobj;
					jsonnodeobj119051* LOC12;
					jsonnodeobj119051* LOC13;
					jsonnodeobj119051* ra;
					nimln(102, "packsdleasy.nim");
					HEX5BHEX5DHEX3D_177110((&atbl), (*a0_177035).I, a0_177035);
					nimln(103, "packsdleasy.nim");
					aobj = newjobject_119339();
					nimln(104, "packsdleasy.nim");
					nimln(104, "packsdleasy.nim");
					LOC12 = 0;
					LOC12 = newjint_119194(((NI64) ((*a0_177035).I)));
					add_122048(aobj, ((NimStringDesc*) &TMP706), LOC12);
					nimln(105, "packsdleasy.nim");
					nimln(105, "packsdleasy.nim");
					LOC13 = 0;
					LOC13 = newjint_119194(((NI64) ((*(*a0_177035).G).Id)));
					add_122048(aobj, ((NimStringDesc*) &TMP707), LOC13);
					nimln(106, "packsdleasy.nim");
					ra = newjarray_119398();
					{
						rect149007 r0_177348;
						TY149048* HEX3Atmp_177718;
						NI i_177721;
						NI l_177723;
						memset((void*)(&r0_177348), 0, sizeof(r0_177348));
						HEX3Atmp_177718 = 0;
						nimln(107, "packsdleasy.nim");
						HEX3Atmp_177718 = (*a0_177035).R;
						nimln(2986, "system.nim");
						i_177721 = 0;
						nimln(2987, "system.nim");
						nimln(2987, "system.nim");
						l_177723 = HEX3Atmp_177718->Sup.len;
						{
							nimln(2988, "system.nim");
							while (1) {
								jsonnodeobj119051* LOC17;
								nimln(2988, "system.nim");
								if (!(i_177721 < l_177723)) goto LA16;
								nimln(2989, "system.nim");
								if ((NU)(i_177721) >= (NU)(HEX3Atmp_177718->Sup.len)) raiseIndexError();
								memcpy((void*)(&r0_177348), (NIM_CONST void*)(&HEX3Atmp_177718->data[i_177721]), sizeof(r0_177348));
								nimln(108, "packsdleasy.nim");
								nimln(108, "packsdleasy.nim");
								LOC17 = 0;
								LOC17 = jsonrect_176599((&r0_177348));
								add_121871(ra, LOC17);
								nimln(2990, "system.nim");
								i_177721 = addInt(i_177721, 1);
								nimln(2991, "system.nim");
								{
									nimln(2991, "system.nim");
									nimln(2991, "system.nim");
									nimln(2991, "system.nim");
									if (!!((HEX3Atmp_177718->Sup.len == l_177723))) goto LA20;
									nimln(2991, "system.nim");
									failedassertimpl_86825(((NimStringDesc*) &TMP689));
								}
								LA20: ;
							} LA16: ;
						}
					}
					nimln(109, "packsdleasy.nim");
					add_122048(aobj, ((NimStringDesc*) &TMP708), ra);
					nimln(110, "packsdleasy.nim");
					add_121871(aa, aobj);
				}
				LA4: ;
				nimln(112, "packsdleasy.nim");
				{
					NIM_BOOL LOC24;
					nimln(112, "packsdleasy.nim");
					LOC24 = 0;
					LOC24 = haskey_177351(gtbl, (*(*a0_177035).G).Id);
					if (!LOC24) goto LA25;
					nimln(113, "packsdleasy.nim");
					{
						assetgroupHEX3Aobjecttype149022* LOC29;
						Exception* ex;
						NimStringDesc* LOC32;
						NimStringDesc* LOC33;
						assetgroupHEX3Aobjecttype149022* LOC34;
						nimln(113, "packsdleasy.nim");
						nimln(113, "packsdleasy.nim");
						nimln(113, "packsdleasy.nim");
						LOC29 = 0;
						LOC29 = HEX5BHEX5D_177412(gtbl, (*(*a0_177035).G).Id);
						if (!!((LOC29 == (*a0_177035).G))) goto LA30;
						nimln(114, "packsdleasy.nim");
						ex = new_155056();
						nimln(115, "packsdleasy.nim");
						nimln(116, "packsdleasy.nim");
						LOC32 = 0;
						nimln(115, "packsdleasy.nim");
						LOC33 = 0;
						LOC33 = nimIntToStr((*(*a0_177035).G).Id);
						nimln(116, "packsdleasy.nim");
						LOC34 = 0;
						LOC34 = HEX5BHEX5D_177412(gtbl, (*(*a0_177035).G).Id);
						LOC32 = rawNewString(LOC33->Sup.len + (*LOC34).Name->Sup.len + (*(*a0_177035).G).Name->Sup.len + 55);
appendString(LOC32, ((NimStringDesc*) &TMP709));
appendString(LOC32, LOC33);
appendString(LOC32, ((NimStringDesc*) &TMP710));
appendString(LOC32, (*LOC34).Name);
appendString(LOC32, ((NimStringDesc*) &TMP711));
appendString(LOC32, (*(*a0_177035).G).Name);
						asgnRefNoCycle((void**) (&(*ex).message), LOC32);
						nimln(117, "packsdleasy.nim");
						raiseException((Exception*)ex, "Exception");
					}
					LA30: ;
				}
				goto LA22;
				LA25: ;
				{
					jsonnodeobj119051* gobj;
					jsonnodeobj119051* LOC36;
					jsonnodeobj119051* LOC37;
					jsonnodeobj119051* LOC38;
					jsonnodeobj119051* LOC39;
					nimln(119, "packsdleasy.nim");
					HEX5BHEX5DHEX3D_177485((&gtbl), (*(*a0_177035).G).Id, (*a0_177035).G);
					nimln(120, "packsdleasy.nim");
					gobj = newjobject_119339();
					nimln(121, "packsdleasy.nim");
					nimln(121, "packsdleasy.nim");
					LOC36 = 0;
					LOC36 = jsonrect_176599((&(*(*a0_177035).G).Rect));
					add_122048(gobj, ((NimStringDesc*) &TMP712), LOC36);
					nimln(122, "packsdleasy.nim");
					nimln(122, "packsdleasy.nim");
					LOC37 = 0;
					LOC37 = newjstring_119114((*(*a0_177035).G).Name);
					add_122048(gobj, ((NimStringDesc*) &TMP713), LOC37);
					nimln(123, "packsdleasy.nim");
					nimln(123, "packsdleasy.nim");
					LOC38 = 0;
					LOC38 = newjint_119194(((NI64) ((*(*a0_177035).G).Counter)));
					add_122048(gobj, ((NimStringDesc*) &TMP714), LOC38);
					nimln(124, "packsdleasy.nim");
					nimln(124, "packsdleasy.nim");
					LOC39 = 0;
					LOC39 = newjint_119194(((NI64) ((*(*a0_177035).G).Id)));
					add_122048(gobj, ((NimStringDesc*) &TMP715), LOC39);
					nimln(125, "packsdleasy.nim");
					add_121871(ga, gobj);
				}
				LA22: ;
				nimln(2990, "system.nim");
				i_177727 = addInt(i_177727, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((asset->Sup.len == l_177729))) goto LA42;
					nimln(2991, "system.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP689));
				}
				LA42: ;
			} LA3: ;
		}
	}
	nimln(126, "packsdleasy.nim");
	jobj = newjobject_119339();
	nimln(127, "packsdleasy.nim");
	add_122048(jobj, ((NimStringDesc*) &TMP716), ga);
	nimln(128, "packsdleasy.nim");
	add_122048(jobj, ((NimStringDesc*) &TMP717), aa);
	nimln(129, "packsdleasy.nim");
	nimln(129, "packsdleasy.nim");
	genericSeqAssign((&(*Result).Field0.Data), atbl.Data, (&NTI176688));
	(*Result).Field0.Counter = atbl.Counter;
	(*Result).Field0.First = atbl.First;
	(*Result).Field0.Last = atbl.Last;
	genericSeqAssign((&(*Result).Field1.Data), gtbl.Data, (&NTI176718));
	(*Result).Field1.Counter = gtbl.Counter;
	(*Result).Field1.First = gtbl.First;
	(*Result).Field1.Last = gtbl.Last;
	unsureAsgnRef((void**) (&(*Result).Field2), jobj);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, loadjson_177754)(jsonnodeobj119051* jobj, assetjsonmanifest176679* Result) {
	orderedtable176685 atbl;
	orderedtable176715 gtbl;
	jsonnodeobj119051* gobj;
	jsonnodeobj119051* aobj;
	NI i0;
	nimfr("loadJSON", "packsdleasy.nim")
	memset((void*)(&atbl), 0, sizeof(atbl));
	nimln(132, "packsdleasy.nim");
	chckNil((void*)(&atbl));
	memset((void*)(&atbl), 0, sizeof(atbl));
	initorderedtable_176751(64, (&atbl));
	memset((void*)(&gtbl), 0, sizeof(gtbl));
	nimln(133, "packsdleasy.nim");
	chckNil((void*)(&gtbl));
	memset((void*)(&gtbl), 0, sizeof(gtbl));
	initorderedtable_176822(64, (&gtbl));
	nimln(134, "packsdleasy.nim");
	gobj = HEX5BHEX5D_120709(jobj, ((NimStringDesc*) &TMP716));
	nimln(135, "packsdleasy.nim");
	aobj = HEX5BHEX5D_120709(jobj, ((NimStringDesc*) &TMP717));
	{
		jsonnodeobj119051* g_177780;
		g_177780 = 0;
		nimln(871, "json.nim");
		{
			nimln(871, "json.nim");
			nimln(871, "json.nim");
			if (!!(((*gobj).Kind == ((NU8) 6)))) goto LA4;
			nimln(871, "json.nim");
			failedassertimpl_86825(((NimStringDesc*) &TMP691));
		}
		LA4: ;
		{
			jsonnodeobj119051* i_178088;
			TY119071* HEX3Atmp_178090;
			NI i_178092;
			NI l_178094;
			i_178088 = 0;
			HEX3Atmp_178090 = 0;
			nimln(872, "json.nim");
			if (!(((64 &(1<<(((*gobj).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP692));
			HEX3Atmp_178090 = (*gobj).kindU.S7.Elems;
			nimln(2986, "system.nim");
			i_178092 = 0;
			nimln(2987, "system.nim");
			nimln(2987, "system.nim");
			l_178094 = HEX3Atmp_178090->Sup.len;
			{
				nimln(2988, "system.nim");
				while (1) {
					assetgroupHEX3Aobjecttype149022* ag;
					jsonnodeobj119051* LOC9;
					jsonnodeobj119051* LOC10;
					NimStringDesc* LOC11;
					jsonnodeobj119051* LOC12;
					jsonnodeobj119051* LOC13;
					nimln(2988, "system.nim");
					if (!(i_178092 < l_178094)) goto LA8;
					nimln(2989, "system.nim");
					if ((NU)(i_178092) >= (NU)(HEX3Atmp_178090->Sup.len)) raiseIndexError();
					i_178088 = HEX3Atmp_178090->data[i_178092];
					nimln(872, "json.nim");
					g_177780 = i_178088;
					ag = 0;
					nimln(137, "packsdleasy.nim");
					ag = (assetgroupHEX3Aobjecttype149022*) newObj((&NTI149009), sizeof(assetgroupHEX3Aobjecttype149022));
					nimln(138, "packsdleasy.nim");
					nimln(138, "packsdleasy.nim");
					LOC9 = 0;
					LOC9 = HEX5BHEX5D_120709(g_177780, ((NimStringDesc*) &TMP715));
					if (!(((4 &(1<<(((*LOC9).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP694));
					(*ag).Id = ((NI)chckRange64((*LOC9).kindU.S2.Num, (-2147483647 -1), 2147483647));
					nimln(139, "packsdleasy.nim");
					add_177815((&gtbl), (*ag).Id, ag);
					nimln(140, "packsdleasy.nim");
					nimln(140, "packsdleasy.nim");
					LOC10 = 0;
					LOC10 = HEX5BHEX5D_120709(g_177780, ((NimStringDesc*) &TMP713));
					if (!(((16 &(1<<(((*LOC10).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP693));
					LOC11 = 0;
					LOC11 = (*ag).Name; (*ag).Name = copyStringRC1((*LOC10).kindU.S1.Str);
					if (LOC11) nimGCunrefNoCycle(LOC11);
					nimln(141, "packsdleasy.nim");
					nimln(141, "packsdleasy.nim");
					LOC12 = 0;
					LOC12 = HEX5BHEX5D_120709(g_177780, ((NimStringDesc*) &TMP712));
					ofjsonrect_176611(LOC12, (&(*ag).Rect));
					nimln(142, "packsdleasy.nim");
					nimln(142, "packsdleasy.nim");
					LOC13 = 0;
					LOC13 = HEX5BHEX5D_120709(g_177780, ((NimStringDesc*) &TMP714));
					if (!(((4 &(1<<(((*LOC13).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP694));
					(*ag).Counter = ((NI)chckRange64((*LOC13).kindU.S2.Num, (-2147483647 -1), 2147483647));
					nimln(2990, "system.nim");
					i_178092 = addInt(i_178092, 1);
					nimln(2991, "system.nim");
					{
						nimln(2991, "system.nim");
						nimln(2991, "system.nim");
						nimln(2991, "system.nim");
						if (!!((HEX3Atmp_178090->Sup.len == l_178094))) goto LA16;
						nimln(2991, "system.nim");
						failedassertimpl_86825(((NimStringDesc*) &TMP689));
					}
					LA16: ;
				} LA8: ;
			}
		}
	}
	nimln(143, "packsdleasy.nim");
	i0 = 0;
	{
		jsonnodeobj119051* a_177932;
		a_177932 = 0;
		nimln(871, "json.nim");
		{
			nimln(871, "json.nim");
			nimln(871, "json.nim");
			if (!!(((*aobj).Kind == ((NU8) 6)))) goto LA21;
			nimln(871, "json.nim");
			failedassertimpl_86825(((NimStringDesc*) &TMP691));
		}
		LA21: ;
		{
			jsonnodeobj119051* i_178111;
			TY119071* HEX3Atmp_178113;
			NI i_178115;
			NI l_178117;
			i_178111 = 0;
			HEX3Atmp_178113 = 0;
			nimln(872, "json.nim");
			if (!(((64 &(1<<(((*aobj).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP692));
			HEX3Atmp_178113 = (*aobj).kindU.S7.Elems;
			nimln(2986, "system.nim");
			i_178115 = 0;
			nimln(2987, "system.nim");
			nimln(2987, "system.nim");
			l_178117 = HEX3Atmp_178113->Sup.len;
			{
				nimln(2988, "system.nim");
				while (1) {
					TY149048* ra;
					jsonnodeobj119051* LOC26;
					NI LOC27;
					assetHEX3Aobjecttype149027* na;
					jsonnodeobj119051* LOC41;
					jsonnodeobj119051* LOC42;
					assetgroupHEX3Aobjecttype149022* LOC43;
					nimln(2988, "system.nim");
					if (!(i_178115 < l_178117)) goto LA25;
					nimln(2989, "system.nim");
					if ((NU)(i_178115) >= (NU)(HEX3Atmp_178113->Sup.len)) raiseIndexError();
					i_178111 = HEX3Atmp_178113->data[i_178115];
					nimln(872, "json.nim");
					a_177932 = i_178111;
					nimln(145, "packsdleasy.nim");
					nimln(145, "packsdleasy.nim");
					nimln(145, "packsdleasy.nim");
					LOC26 = 0;
					LOC26 = HEX5BHEX5D_120709(a_177932, ((NimStringDesc*) &TMP708));
					LOC27 = 0;
					LOC27 = len_120649(LOC26);
					ra = newseq_177950(LOC27);
					{
						jsonnodeobj119051* r0_177985;
						jsonnodeobj119051* HEX3Atmp_178097;
						r0_177985 = 0;
						HEX3Atmp_178097 = 0;
						nimln(146, "packsdleasy.nim");
						HEX3Atmp_178097 = HEX5BHEX5D_120709(a_177932, ((NimStringDesc*) &TMP708));
						nimln(871, "json.nim");
						{
							nimln(871, "json.nim");
							nimln(871, "json.nim");
							if (!!(((*HEX3Atmp_178097).Kind == ((NU8) 6)))) goto LA31;
							nimln(871, "json.nim");
							failedassertimpl_86825(((NimStringDesc*) &TMP691));
						}
						LA31: ;
						{
							jsonnodeobj119051* i_178101;
							TY119071* HEX3Atmp_178103;
							NI i_178105;
							NI l_178107;
							i_178101 = 0;
							HEX3Atmp_178103 = 0;
							nimln(872, "json.nim");
							if (!(((64 &(1<<(((*HEX3Atmp_178097).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP692));
							HEX3Atmp_178103 = (*HEX3Atmp_178097).kindU.S7.Elems;
							nimln(2986, "system.nim");
							i_178105 = 0;
							nimln(2987, "system.nim");
							nimln(2987, "system.nim");
							l_178107 = HEX3Atmp_178103->Sup.len;
							{
								nimln(2988, "system.nim");
								while (1) {
									rect149007 LOC36;
									nimln(2988, "system.nim");
									if (!(i_178105 < l_178107)) goto LA35;
									nimln(2989, "system.nim");
									if ((NU)(i_178105) >= (NU)(HEX3Atmp_178103->Sup.len)) raiseIndexError();
									i_178101 = HEX3Atmp_178103->data[i_178105];
									nimln(872, "json.nim");
									r0_177985 = i_178101;
									nimln(147, "packsdleasy.nim");
									nimln(147, "packsdleasy.nim");
									memset((void*)(&LOC36), 0, sizeof(LOC36));
									ofjsonrect_176611(r0_177985, (&LOC36));
									ra = (TY149048*) incrSeq(&(ra)->Sup, sizeof(rect149007));
									genericAssign((void*)(&ra->data[ra->Sup.len-1]), (void*)(&LOC36), (&NTI149007));
									nimln(2990, "system.nim");
									i_178105 = addInt(i_178105, 1);
									nimln(2991, "system.nim");
									{
										nimln(2991, "system.nim");
										nimln(2991, "system.nim");
										nimln(2991, "system.nim");
										if (!!((HEX3Atmp_178103->Sup.len == l_178107))) goto LA39;
										nimln(2991, "system.nim");
										failedassertimpl_86825(((NimStringDesc*) &TMP689));
									}
									LA39: ;
								} LA35: ;
							}
						}
					}
					nimln(148, "packsdleasy.nim");
					nimln(148, "packsdleasy.nim");
					LOC41 = 0;
					LOC41 = HEX5BHEX5D_120709(a_177932, ((NimStringDesc*) &TMP706));
					if (!(((4 &(1<<(((*LOC41).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP694));
					nimln(149, "packsdleasy.nim");
					nimln(149, "packsdleasy.nim");
					LOC42 = 0;
					LOC42 = HEX5BHEX5D_120709(a_177932, ((NimStringDesc*) &TMP707));
					if (!(((4 &(1<<(((*LOC42).Kind)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP694));
					LOC43 = 0;
					LOC43 = HEX5BHEX5D_177412(gtbl, ((NI)chckRange64((*LOC42).kindU.S2.Num, (-2147483647 -1), 2147483647)));
					na = newasset_149044(((NI)chckRange64((*LOC41).kindU.S2.Num, (-2147483647 -1), 2147483647)), LOC43, ra);
					nimln(151, "packsdleasy.nim");
					HEX5BHEX5DHEX3D_177110((&atbl), i0, na);
					nimln(152, "packsdleasy.nim");
					i0 = addInt(i0, 1);
					nimln(2990, "system.nim");
					i_178115 = addInt(i_178115, 1);
					nimln(2991, "system.nim");
					{
						nimln(2991, "system.nim");
						nimln(2991, "system.nim");
						nimln(2991, "system.nim");
						if (!!((HEX3Atmp_178113->Sup.len == l_178117))) goto LA46;
						nimln(2991, "system.nim");
						failedassertimpl_86825(((NimStringDesc*) &TMP689));
					}
					LA46: ;
				} LA25: ;
			}
		}
	}
	nimln(153, "packsdleasy.nim");
	nimln(153, "packsdleasy.nim");
	genericSeqAssign((&(*Result).Field0.Data), atbl.Data, (&NTI176688));
	(*Result).Field0.Counter = atbl.Counter;
	(*Result).Field0.First = atbl.First;
	(*Result).Field0.Last = atbl.Last;
	genericSeqAssign((&(*Result).Field1.Data), gtbl.Data, (&NTI176718));
	(*Result).Field1.Counter = gtbl.Counter;
	(*Result).Field1.First = gtbl.First;
	(*Result).Field1.Last = gtbl.Last;
	unsureAsgnRef((void**) (&(*Result).Field2), jobj);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45671((&gch_47044.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51025)(tcell44933* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48667(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49429(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_50604)(tcell44933* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48667(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49429(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell44933* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48646(src);
		incref_51025(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell44933* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48646((*dest));
		decref_50604(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(TY149663*, gettiles_179098)(assetgroupHEX3Aobjecttype149022* ig_179105, surface132715* isurf_179107, NI tw_179109, NI th_179111) {
	TY149663* result;
	TY149048* tiles;
	nimfr("getTiles", "packsdleasy.nim")
	result = 0;
	nimln(156, "packsdleasy.nim");
	tiles = rhoriztiling_150172(ig_179105, tw_179109, th_179111, 0, 0, 0, 0);
	nimln(157, "packsdleasy.nim");
	result = newseq_151270(0);
	{
		NI n0_179139;
		NI HEX3Atmp_179180;
		NI res_179183;
		n0_179139 = 0;
		HEX3Atmp_179180 = 0;
		nimln(158, "packsdleasy.nim");
		nimln(158, "packsdleasy.nim");
		HEX3Atmp_179180 = (tiles->Sup.len-1);
		nimln(1576, "system.nim");
		res_179183 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				assetHEX3Aobjecttype149027* a0;
				TY149048* LOC4;
				TY150226 LOC5;
				nimln(1577, "system.nim");
				if (!(res_179183 <= HEX3Atmp_179180)) goto LA3;
				nimln(1576, "system.nim");
				n0_179139 = res_179183;
				nimln(159, "packsdleasy.nim");
				nimln(159, "packsdleasy.nim");
				LOC4 = 0;
				LOC4 = (TY149048*) newSeq((&NTI149048), 1);
				memset((void*)LOC5, 0, sizeof(LOC5));
				if ((NU)(n0_179139) >= (NU)(tiles->Sup.len)) raiseIndexError();
				genericAssign((void*)(&LOC5[0]), (void*)(&tiles->data[n0_179139]), (&NTI149007));
				genericAssign((void*)(&LOC4->data[0]), (void*)(&LOC5[0]), (&NTI149007));
				a0 = newasset_149044(n0_179139, ig_179105, LOC4);
				nimln(160, "packsdleasy.nim");
				reduce_168360(a0, isurf_179107, ((NU32) 255), ((NU8) 0));
				nimln(161, "packsdleasy.nim");
				{
					NIM_BOOL LOC8;
					nimln(161, "packsdleasy.nim");
					nimln(161, "packsdleasy.nim");
					LOC8 = 0;
					LOC8 = isempty_168348(a0, isurf_179107, ((NU32) 255));
					if (!!(LOC8)) goto LA9;
					nimln(162, "packsdleasy.nim");
					result = (TY149663*) incrSeq(&(result)->Sup, sizeof(assetHEX3Aobjecttype149027*));
					asgnRef((void**) (&result->data[result->Sup.len-1]), a0);
				}
				LA9: ;
				nimln(1579, "system.nim");
				res_179183 = addInt(res_179183, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_packsdleasyInit)(void) {
	nimfr("packsdleasy", "packsdleasy.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_packsdleasyDatInit)(void) {
static TNimNode* TMP687[2];
static TNimNode TMP683[3];
NTI176025.size = sizeof(bundletup176025);
NTI176025.kind = 18;
NTI176025.base = 0;
NTI176025.flags = 2;
TMP687[0] = &TMP683[1];
TMP683[1].kind = 1;
TMP683[1].offset = offsetof(bundletup176025, Field0);
TMP683[1].typ = (&NTI132713);
TMP683[1].name = "Field0";
TMP687[1] = &TMP683[2];
TMP683[2].kind = 1;
TMP683[2].offset = offsetof(bundletup176025, Field1);
TMP683[2].typ = (&NTI167007);
TMP683[2].name = "Field1";
TMP683[0].len = 2; TMP683[0].kind = 2; TMP683[0].sons = &TMP687[0];
NTI176025.node = &TMP683[0];
NTI176096.size = sizeof(TY176096*);
NTI176096.kind = 24;
NTI176096.base = (&NTI176025);
NTI176096.flags = 2;
NTI176096.marker = TMP688;
}

