/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_unicode.o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_unicode.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_16242;

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI c) {
	NimStringDesc* result;
	NI i;
	nimfr("toUTF8", "unicode.nim")
	result = 0;
	nimln(114, "unicode.nim");
	i = c;
	nimln(115, "unicode.nim");
	{
		nimln(115, "unicode.nim");
		if (!((NU32)(i) <= (NU32)(127))) goto LA3;
		nimln(116, "unicode.nim");
		nimln(116, "unicode.nim");
		result = mnewString(1);
		nimln(117, "unicode.nim");
		if ((NU)(0) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(117, "unicode.nim");
		result->data[0] = ((NIM_CHAR) (((NI)chckRange(i, 0, 255))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(118, "unicode.nim");
		if (!((NU32)(i) <= (NU32)(2047))) goto LA6;
		nimln(119, "unicode.nim");
		nimln(119, "unicode.nim");
		result = mnewString(2);
		nimln(120, "unicode.nim");
		if ((NU)(0) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(120, "unicode.nim");
		nimln(120, "unicode.nim");
		nimln(120, "unicode.nim");
		result->data[0] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU32)(i) >> (NU32)(6)) | 192), 0, 255))));
		nimln(121, "unicode.nim");
		if ((NU)(1) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(121, "unicode.nim");
		nimln(121, "unicode.nim");
		nimln(121, "unicode.nim");
		result->data[1] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)(i & 63))) | 128), 0, 255))));
	}
	goto LA1;
	LA6: ;
	{
		nimln(122, "unicode.nim");
		if (!((NU32)(i) <= (NU32)(65535))) goto LA9;
		nimln(123, "unicode.nim");
		nimln(123, "unicode.nim");
		result = mnewString(3);
		nimln(124, "unicode.nim");
		if ((NU)(0) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(124, "unicode.nim");
		nimln(124, "unicode.nim");
		nimln(124, "unicode.nim");
		result->data[0] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU32)(i) >> (NU32)(12)) | 224), 0, 255))));
		nimln(125, "unicode.nim");
		if ((NU)(1) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(125, "unicode.nim");
		nimln(125, "unicode.nim");
		nimln(125, "unicode.nim");
		nimln(125, "unicode.nim");
		result->data[1] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU32)(i) >> (NU32)(6)) & 63))) | 128), 0, 255))));
		nimln(126, "unicode.nim");
		if ((NU)(2) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(126, "unicode.nim");
		nimln(126, "unicode.nim");
		nimln(126, "unicode.nim");
		result->data[2] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)(i & 63))) | 128), 0, 255))));
	}
	goto LA1;
	LA9: ;
	{
		nimln(127, "unicode.nim");
		if (!((NU32)(i) <= (NU32)(1114111))) goto LA12;
		nimln(128, "unicode.nim");
		nimln(128, "unicode.nim");
		result = mnewString(4);
		nimln(129, "unicode.nim");
		if ((NU)(0) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(129, "unicode.nim");
		nimln(129, "unicode.nim");
		nimln(129, "unicode.nim");
		result->data[0] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU32)(i) >> (NU32)(18)) | 240), 0, 255))));
		nimln(130, "unicode.nim");
		if ((NU)(1) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(130, "unicode.nim");
		nimln(130, "unicode.nim");
		nimln(130, "unicode.nim");
		nimln(130, "unicode.nim");
		result->data[1] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU32)(i) >> (NU32)(12)) & 63))) | 128), 0, 255))));
		nimln(131, "unicode.nim");
		if ((NU)(2) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(131, "unicode.nim");
		nimln(131, "unicode.nim");
		nimln(131, "unicode.nim");
		nimln(131, "unicode.nim");
		result->data[2] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)((NI)((NU32)(i) >> (NU32)(6)) & 63))) | 128), 0, 255))));
		nimln(132, "unicode.nim");
		if ((NU)(3) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(132, "unicode.nim");
		nimln(132, "unicode.nim");
		nimln(132, "unicode.nim");
		result->data[3] = ((NIM_CHAR) (((NI)chckRange((NI)(((NI) ((NI)(i & 63))) | 128), 0, 255))));
	}
	goto LA1;
	LA12: ;
	{
		nimln(134, "unicode.nim");
		nimln(134, "unicode.nim");
		result = mnewString(1);
		nimln(135, "unicode.nim");
		if ((NU)(0) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(135, "unicode.nim");
		result->data[0] = ((NIM_CHAR) (((NI)chckRange(i, 0, 255))));
	}
	LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit)(void) {
	nimfr("unicode", "unicode.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit)(void) {
}

