/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_algorithm.o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_algorithm.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct assetHEX3Aobjecttype149027 assetHEX3Aobjecttype149027;
typedef struct TY149663 TY149663;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct assetgroupHEX3Aobjecttype149022 assetgroupHEX3Aobjecttype149022;
typedef struct TY149048 TY149048;
typedef struct rect149007 rect149007;
typedef struct TY149020 TY149020;
typedef struct dataentry149005 dataentry149005;
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (assetHEX3Aobjecttype149027* x_152193, assetHEX3Aobjecttype149027* y_152195, void* ClEnv);
void* ClEnv;
} TY152199;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(NI, TMP447) (assetHEX3Aobjecttype149027* x_152268, assetHEX3Aobjecttype149027* y_152270);
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CLOSURE_PTR(NI, TMP449) (assetHEX3Aobjecttype149027* x_152268, assetHEX3Aobjecttype149027* y_152270);
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (NI x_154298, NI y_154300, void* ClEnv);
void* ClEnv;
} TY154304;
typedef N_CLOSURE_PTR(NI, TMP465) (NI x_154298, NI y_154300);
typedef N_CLOSURE_PTR(NI, TMP467) (NI x_154281, NI y_154283, void* ClEnv);
struct  dataentry149005  {
NimStringDesc* K;
NI V;
};
struct  rect149007  {
NI X;
NI Y;
NI W;
NI H;
TY149020* D;
};
struct  assetHEX3Aobjecttype149027  {
assetHEX3Aobjecttype149027* P;
NI I;
assetgroupHEX3Aobjecttype149022* G;
TY149048* R;
};
struct  assetgroupHEX3Aobjecttype149022  {
rect149007 Rect;
NimStringDesc* Name;
NI Counter;
NI Id;
};
struct TY149663 {
  TGenericSeq Sup;
  assetHEX3Aobjecttype149027* data[SEQ_DECL_SIZE];
};
struct TY149020 {
  TGenericSeq Sup;
  dataentry149005 data[SEQ_DECL_SIZE];
};
struct TY149048 {
  TGenericSeq Sup;
  rect149007 data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX2A_148020)(NI x, NU8 order);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, merge_152241)(assetHEX3Aobjecttype149027** a_152249, NI a_152249Len0, assetHEX3Aobjecttype149027** b_152257, NI b_152257Len0, NI lo_152261, NI m_152263, NI hi_152265, TY152199 cmp_152273, NU8 order_152276);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, failedassertimpl_86825)(NimStringDesc* msg);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NI, lowerbound_154286)(NI* a_154292, NI a_154292Len0, NI key_154295, TY154304 cmp_154303);
N_NIMCALL(NI, cmp_152150)(NI x_152154, NI y_152156);
STRING_LITERAL(TMP448, "j (system.<=|system.<=|system.<=|system.<=|system.<=|system.<=|"
"system.<=|system.<=|system.<=|system.<=|system.<=|system.<=|syst"
"em.<=|system.<=|system.<=|...)\015\012    m ", 165);
extern TFrame* frameptr_16242;
extern TNimType NTI149663; /* seq[Asset] */
extern TNimType NTI108; /* int */
TNimType NTI148033; /* range -1..0(int) */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NI, HEX2A_148020)(NI x, NU8 order) {
	NI result;
	NI y;
	NI TMP367;
	NI TMP368;
	nimfr("*", "algorithm.nim")
	result = 0;
	nimln(24, "algorithm.nim");
	nimln(24, "algorithm.nim");
	nimln(24, "algorithm.nim");
	TMP367 = subInt(((NI) (order)), 1);
	y = (NI32)(TMP367);
	nimln(25, "algorithm.nim");
	nimln(25, "algorithm.nim");
	nimln(25, "algorithm.nim");
	TMP368 = subInt((NI)(x ^ ((NI) (y))), ((NI) (y)));
	result = (NI32)(TMP368);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (-2147483647 -1));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI32)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, merge_152241)(assetHEX3Aobjecttype149027** a_152249, NI a_152249Len0, assetHEX3Aobjecttype149027** b_152257, NI b_152257Len0, NI lo_152261, NI m_152263, NI hi_152265, TY152199 cmp_152273, NU8 order_152276) {
	NI j;
	NI bb;
	NI i;
	NI k;
	nimfr("merge", "algorithm.nim")
	nimln(118, "algorithm.nim");
	{
		NI TMP446;
		NI LOC3;
		NI LOC4;
		nimln(118, "algorithm.nim");
		nimln(118, "algorithm.nim");
		nimln(118, "algorithm.nim");
		if ((NU)(m_152263) >= (NU)(a_152249Len0)) raiseIndexError();
		nimln(118, "algorithm.nim");
		TMP446 = addInt(m_152263, 1);
		if ((NU)((NI32)(TMP446)) >= (NU)(a_152249Len0)) raiseIndexError();
		LOC3 = 0;
		LOC3 = cmp_152273.ClEnv? cmp_152273.ClPrc(a_152249[m_152263], a_152249[(NI32)(TMP446)], cmp_152273.ClEnv):((TMP447)(cmp_152273.ClPrc))(a_152249[m_152263], a_152249[(NI32)(TMP446)]);
		LOC4 = 0;
		LOC4 = HEX2A_148020(LOC3, order_152276);
		if (!(LOC4 <= 0)) goto LA5;
		nimln(118, "algorithm.nim");
		goto BeforeRet;
	}
	LA5: ;
	nimln(119, "algorithm.nim");
	j = lo_152261;
	nimln(121, "algorithm.nim");
	{
		nimln(121, "algorithm.nim");
		nimln(121, "algorithm.nim");
		if (!!((j <= m_152263))) goto LA9;
		nimln(121, "algorithm.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP448));
	}
	LA9: ;
	nimln(123, "algorithm.nim");
	bb = 0;
	{
		nimln(124, "algorithm.nim");
		while (1) {
			nimln(124, "algorithm.nim");
			if (!(j <= m_152263)) goto LA12;
			nimln(111, "algorithm.nim");
			if ((NU)(bb) >= (NU)(b_152257Len0)) raiseIndexError();
			if ((NU)(j) >= (NU)(a_152249Len0)) raiseIndexError();
			unsureAsgnRef((void**) (&b_152257[bb]), a_152249[j]);
			nimln(126, "algorithm.nim");
			bb = addInt(bb, 1);
			nimln(127, "algorithm.nim");
			j = addInt(j, 1);
		} LA12: ;
	}
	nimln(131, "algorithm.nim");
	i = 0;
	nimln(132, "algorithm.nim");
	k = lo_152261;
	{
		nimln(134, "algorithm.nim");
		while (1) {
			NIM_BOOL LOC15;
			nimln(134, "algorithm.nim");
			LOC15 = 0;
			nimln(134, "algorithm.nim");
			LOC15 = (k < j);
			if (!(LOC15)) goto LA16;
			nimln(134, "algorithm.nim");
			LOC15 = (j <= hi_152265);
			LA16: ;
			if (!LOC15) goto LA14;
			nimln(135, "algorithm.nim");
			{
				NI LOC19;
				NI LOC20;
				nimln(135, "algorithm.nim");
				nimln(135, "algorithm.nim");
				nimln(135, "algorithm.nim");
				if ((NU)(i) >= (NU)(b_152257Len0)) raiseIndexError();
				if ((NU)(j) >= (NU)(a_152249Len0)) raiseIndexError();
				LOC19 = 0;
				LOC19 = cmp_152273.ClEnv? cmp_152273.ClPrc(b_152257[i], a_152249[j], cmp_152273.ClEnv):((TMP449)(cmp_152273.ClPrc))(b_152257[i], a_152249[j]);
				LOC20 = 0;
				LOC20 = HEX2A_148020(LOC19, order_152276);
				if (!(LOC20 <= 0)) goto LA21;
				nimln(111, "algorithm.nim");
				if ((NU)(k) >= (NU)(a_152249Len0)) raiseIndexError();
				if ((NU)(i) >= (NU)(b_152257Len0)) raiseIndexError();
				unsureAsgnRef((void**) (&a_152249[k]), b_152257[i]);
				nimln(137, "algorithm.nim");
				i = addInt(i, 1);
			}
			goto LA17;
			LA21: ;
			{
				nimln(111, "algorithm.nim");
				if ((NU)(k) >= (NU)(a_152249Len0)) raiseIndexError();
				if ((NU)(j) >= (NU)(a_152249Len0)) raiseIndexError();
				unsureAsgnRef((void**) (&a_152249[k]), a_152249[j]);
				nimln(140, "algorithm.nim");
				j = addInt(j, 1);
			}
			LA17: ;
			nimln(141, "algorithm.nim");
			k = addInt(k, 1);
		} LA14: ;
	}
	{
		nimln(144, "algorithm.nim");
		while (1) {
			nimln(144, "algorithm.nim");
			if (!(k < j)) goto LA25;
			nimln(111, "algorithm.nim");
			if ((NU)(k) >= (NU)(a_152249Len0)) raiseIndexError();
			if ((NU)(i) >= (NU)(b_152257Len0)) raiseIndexError();
			unsureAsgnRef((void**) (&a_152249[k]), b_152257[i]);
			nimln(146, "algorithm.nim");
			k = addInt(k, 1);
			nimln(147, "algorithm.nim");
			i = addInt(i, 1);
		} LA25: ;
	}
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, sort_152180)(assetHEX3Aobjecttype149027** a_152188, NI a_152188Len0, TY152199 cmp_152198, NU8 order_152201) {
	NI n;
	TY149663* b;
	NI TMP443;
	NI s;
	nimfr("sort", "algorithm.nim")
	nimln(179, "algorithm.nim");
	nimln(179, "algorithm.nim");
	n = a_152188Len0;
	b = 0;
	nimln(181, "algorithm.nim");
	nimln(181, "algorithm.nim");
	TMP443 = divInt(n, 2);
	b = (TY149663*) newSeq((&NTI149663), (NI32)(TMP443));
	nimln(182, "algorithm.nim");
	s = 1;
	{
		nimln(183, "algorithm.nim");
		while (1) {
			NI m;
			NI TMP444;
			NI TMP445;
			NI TMP454;
			nimln(183, "algorithm.nim");
			if (!(s < n)) goto LA2;
			nimln(184, "algorithm.nim");
			nimln(184, "algorithm.nim");
			nimln(184, "algorithm.nim");
			TMP444 = subInt(n, 1);
			TMP445 = subInt((NI32)(TMP444), s);
			m = (NI32)(TMP445);
			{
				nimln(185, "algorithm.nim");
				while (1) {
					NI TMP450;
					NI TMP451;
					NI TMP452;
					NI TMP453;
					nimln(185, "algorithm.nim");
					if (!(0 <= m)) goto LA4;
					nimln(186, "algorithm.nim");
					nimln(186, "algorithm.nim");
					nimln(186, "algorithm.nim");
					nimln(186, "algorithm.nim");
					TMP450 = subInt(m, s);
					TMP451 = addInt((NI32)(TMP450), 1);
					nimln(186, "algorithm.nim");
					TMP452 = addInt(m, s);
					merge_152241(a_152188, a_152188Len0, b->data, b->Sup.len, (((NI32)(TMP451) >= 0) ? (NI32)(TMP451) : 0), m, (NI32)(TMP452), cmp_152198, order_152201);
					nimln(187, "algorithm.nim");
					nimln(187, "algorithm.nim");
					TMP453 = mulInt(s, 2);
					m = subInt(m, (NI32)(TMP453));
				} LA4: ;
			}
			nimln(188, "algorithm.nim");
			nimln(188, "algorithm.nim");
			TMP454 = mulInt(s, 2);
			s = (NI32)(TMP454);
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(NI, lowerbound_154286)(NI* a_154292, NI a_154292Len0, NI key_154295, TY154304 cmp_154303) {
	NI result;
	NI pos;
	NI count;
	NI step;
	NI TMP462;
	NI TMP463;
	nimfr("lowerBound", "algorithm.nim")
	result = 0;
	nimln(89, "algorithm.nim");
	result = 0;
	nimln(90, "algorithm.nim");
	pos = result;
	count = 0;
	step = 0;
	nimln(92, "algorithm.nim");
	nimln(92, "algorithm.nim");
	nimln(92, "algorithm.nim");
	nimln(92, "algorithm.nim");
	TMP462 = subInt((a_154292Len0-1), 0);
	TMP463 = addInt((NI32)(TMP462), 1);
	count = (NI32)(TMP463);
	{
		nimln(93, "algorithm.nim");
		while (1) {
			NI TMP464;
			nimln(93, "algorithm.nim");
			nimln(93, "algorithm.nim");
			if (!!((count == 0))) goto LA2;
			nimln(94, "algorithm.nim");
			pos = result;
			nimln(95, "algorithm.nim");
			nimln(95, "algorithm.nim");
			TMP464 = divInt(count, 2);
			step = (NI32)(TMP464);
			nimln(96, "algorithm.nim");
			pos = addInt(pos, step);
			nimln(97, "algorithm.nim");
			{
				NI LOC5;
				NI TMP466;
				nimln(97, "algorithm.nim");
				nimln(97, "algorithm.nim");
				if ((NU)(pos) >= (NU)(a_154292Len0)) raiseIndexError();
				LOC5 = 0;
				LOC5 = cmp_154303.ClEnv? cmp_154303.ClPrc(a_154292[pos], key_154295, cmp_154303.ClEnv):((TMP465)(cmp_154303.ClPrc))(a_154292[pos], key_154295);
				if (!(LOC5 < 0)) goto LA6;
				nimln(98, "algorithm.nim");
				pos = addInt(pos, 1);
				nimln(99, "algorithm.nim");
				result = pos;
				nimln(100, "algorithm.nim");
				nimln(100, "algorithm.nim");
				TMP466 = addInt(step, 1);
				count = subInt(count, (NI32)(TMP466));
			}
			goto LA3;
			LA6: ;
			{
				nimln(102, "algorithm.nim");
				count = step;
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(NI, lowerbound_154257)(NI* a_154263, NI a_154263Len0, NI key_154266) {
	NI result;
	TY154304 LOC1;
	nimfr("lowerBound", "algorithm.nim")
	result = 0;
	nimln(104, "algorithm.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = ((TMP467) (cmp_152150)); LOC1.ClEnv = NIM_NIL;
	result = lowerbound_154286(a_154263, a_154263Len0, key_154266, LOC1);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit)(void) {
	nimfr("algorithm", "algorithm.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit)(void) {
NTI148033.size = sizeof(NI);
NTI148033.kind = 20;
NTI148033.base = (&NTI108);
NTI148033.flags = 3;
}

