/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_tables.o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_tables.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct orderedtable176685 orderedtable176685;
typedef struct orderedkeyvaluepairseq176688 orderedkeyvaluepairseq176688;
typedef struct orderedkeyvaluepair176691 orderedkeyvaluepair176691;
typedef struct assetHEX3Aobjecttype149027 assetHEX3Aobjecttype149027;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct orderedtable176715 orderedtable176715;
typedef struct orderedkeyvaluepairseq176718 orderedkeyvaluepairseq176718;
typedef struct orderedkeyvaluepair176721 orderedkeyvaluepair176721;
typedef struct assetgroupHEX3Aobjecttype149022 assetgroupHEX3Aobjecttype149022;
typedef struct tcell44933 tcell44933;
typedef struct tcellset44945 tcellset44945;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct TY149048 TY149048;
typedef struct rect149007 rect149007;
typedef struct TY149020 TY149020;
typedef struct dataentry149005 dataentry149005;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct orderedkeyvaluepair176691 {
NU8 Field0;
NI Field1;
NI Field2;
assetHEX3Aobjecttype149027* Field3;
};
struct  orderedtable176685  {
orderedkeyvaluepairseq176688* Data;
NI Counter;
NI First;
NI Last;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct orderedkeyvaluepair176721 {
NU8 Field0;
NI Field1;
NI Field2;
assetgroupHEX3Aobjecttype149022* Field3;
};
struct  orderedtable176715  {
orderedkeyvaluepairseq176718* Data;
NI Counter;
NI First;
NI Last;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
struct  dataentry149005  {
NimStringDesc* K;
NI V;
};
struct  rect149007  {
NI X;
NI Y;
NI W;
NI H;
TY149020* D;
};
struct  assetHEX3Aobjecttype149027  {
assetHEX3Aobjecttype149027* P;
NI I;
assetgroupHEX3Aobjecttype149022* G;
TY149048* R;
};
struct  assetgroupHEX3Aobjecttype149022  {
rect149007 Rect;
NimStringDesc* Name;
NI Counter;
NI Id;
};
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
struct orderedkeyvaluepairseq176688 {
  TGenericSeq Sup;
  orderedkeyvaluepair176691 data[SEQ_DECL_SIZE];
};
struct orderedkeyvaluepairseq176718 {
  TGenericSeq Sup;
  orderedkeyvaluepair176721 data[SEQ_DECL_SIZE];
};
struct TY149020 {
  TGenericSeq Sup;
  dataentry149005 data[SEQ_DECL_SIZE];
};
struct TY149048 {
  TGenericSeq Sup;
  rect149007 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_173302)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_86825)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_173410)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NIM_BOOL, ispoweroftwo_164318)(NI x);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP700)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, TMP702)(void* p, NI op);
N_NIMCALL(NI, rawget_177052)(orderedtable176685 t_177059, NI key_177062);
static N_INLINE(NI, hash_100804)(NI x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51025)(tcell44933* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c);
static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c);
N_NOINLINE(void, incl_45671)(tcellset44945* s, tcell44933* cell);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, decref_50604)(tcell44933* c);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, enlarge_177155)(orderedtable176685* t_177164);
N_NIMCALL(void, rawinsert_177214)(orderedtable176685* t_177223, orderedkeyvaluepairseq176688** data_177231, NI key_177235, assetHEX3Aobjecttype149027* val_177237);
N_NIMCALL(NI, rawget_177365)(orderedtable176715 t_177372, NI key_177375);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, enlarge_177530)(orderedtable176715* t_177539);
N_NIMCALL(void, rawinsert_177589)(orderedtable176715* t_177598, orderedkeyvaluepairseq176718** data_177606, NI key_177610, assetgroupHEX3Aobjecttype149022* val_177612);
static N_INLINE(NI, len_179448)(orderedtable176685 t_179455);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, HEX24_149470)(assetHEX3Aobjecttype149027* p);
STRING_LITERAL(TMP677, "length > counter ", 17);
STRING_LITERAL(TMP695, "isPowerOfTwo(initialSize) ", 26);
STRING_LITERAL(TMP725, "{:}", 3);
STRING_LITERAL(TMP726, "{", 1);
STRING_LITERAL(TMP727, ", ", 2);
STRING_LITERAL(TMP728, ": ", 2);
STRING_LITERAL(TMP729, "}", 1);
extern TFrame* frameptr_16242;
TNimType NTI176691; /* OrderedKeyValuePair */
TNimType NTI173023; /* SlotEnum */
extern TNimType NTI108; /* int */
extern TNimType NTI149011; /* Asset */
TNimType NTI176688; /* OrderedKeyValuePairSeq */
TNimType NTI176721; /* OrderedKeyValuePair */
extern TNimType NTI149009; /* AssetGroup */
TNimType NTI176718; /* OrderedKeyValuePairSeq */
extern tgcheap47016 gch_47044;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_173302)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP678;
	NI TMP679;
	NI TMP680;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(120, "tables.nim");
	{
		nimln(120, "tables.nim");
		nimln(120, "tables.nim");
		if (!!((counter < length))) goto LA3;
		nimln(120, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP677));
	}
	LA3: ;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	LOC5 = 0;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP678 = mulInt(length, 2);
	nimln(121, "tables.nim");
	TMP679 = mulInt(counter, 3);
	LOC5 = ((NI32)(TMP678) < (NI32)(TMP679));
	if (LOC5) goto LA6;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP680 = subInt(length, counter);
	LOC5 = ((NI32)(TMP680) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_173410)(NI h, NI maxhash) {
	NI result;
	NI TMP681;
	NI TMP682;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	TMP681 = mulInt(5, h);
	TMP682 = addInt((NI32)(TMP681), 1);
	result = (NI)((NI32)(TMP682) & maxhash);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP700)(void* p, NI op) {
	orderedkeyvaluepairseq176688* a;
	NI LOC1;
	a = (orderedkeyvaluepairseq176688*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field3, op);
	}
}

N_NIMCALL(void, initorderedtable_176751)(NI initialsize_176756, orderedtable176685* Result) {
	nimfr("initOrderedTable", "tables.nim")
	nimln(469, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(469, "tables.nim");
		nimln(469, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_164318(initialsize_176756);
		if (!!(LOC3)) goto LA4;
		nimln(469, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP695));
	}
	LA4: ;
	nimln(470, "tables.nim");
	(*Result).Counter = 0;
	nimln(471, "tables.nim");
	(*Result).First = -1;
	nimln(472, "tables.nim");
	(*Result).Last = -1;
	nimln(473, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (orderedkeyvaluepairseq176688*) newSeq((&NTI176688), initialsize_176756));
	popFrame();
}
N_NIMCALL(void, TMP702)(void* p, NI op) {
	orderedkeyvaluepairseq176718* a;
	NI LOC1;
	a = (orderedkeyvaluepairseq176718*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field3, op);
	}
}

N_NIMCALL(void, initorderedtable_176822)(NI initialsize_176827, orderedtable176715* Result) {
	nimfr("initOrderedTable", "tables.nim")
	nimln(469, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(469, "tables.nim");
		nimln(469, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_164318(initialsize_176827);
		if (!!(LOC3)) goto LA4;
		nimln(469, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP695));
	}
	LA4: ;
	nimln(470, "tables.nim");
	(*Result).Counter = 0;
	nimln(471, "tables.nim");
	(*Result).First = -1;
	nimln(472, "tables.nim");
	(*Result).Last = -1;
	nimln(473, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (orderedkeyvaluepairseq176718*) newSeq((&NTI176718), initialsize_176827));
	popFrame();
}

static N_INLINE(NI, hash_100804)(NI x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(107, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

N_NIMCALL(NI, rawget_177052)(orderedtable176685 t_177059, NI key_177062) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100804(key_177062);
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & (t_177059.Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)(t_177059.Data->Sup.len)) raiseIndexError();
			if (!!((t_177059.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_177059.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_177059.Data->data[h].Field2 == key_177062);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_177059.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_177059.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_173410(h, (t_177059.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, haskey_177038)(orderedtable176685 t_177045, NI key_177048) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	nimln(431, "tables.nim");
	nimln(431, "tables.nim");
	nimln(431, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_177052(t_177045, key_177048);
	result = (0 <= LOC1);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45671((&gch_47044.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51025)(tcell44933* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48667(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49429(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, decref_50604)(tcell44933* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48667(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49429(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell44933* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48646(src);
		incref_51025(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell44933* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48646((*dest));
		decref_50604(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, rawinsert_177214)(orderedtable176685* t_177223, orderedkeyvaluepairseq176688** data_177231, NI key_177235, assetHEX3Aobjecttype149027* val_177237) {
	NI h;
	NI LOC1;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100804(key_177235);
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_177231)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_177231)->Sup.len)) raiseIndexError();
			if (!((*data_177231)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_173410(h, ((*data_177231)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_177231)->Sup.len)) raiseIndexError();
	(*data_177231)->data[h].Field2 = key_177235;
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_177231)->Sup.len)) raiseIndexError();
	asgnRef((void**) (&(*data_177231)->data[h].Field3), val_177237);
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_177231)->Sup.len)) raiseIndexError();
	(*data_177231)->data[h].Field0 = ((NU8) 1);
	nimln(437, "tables.nim");
	if ((NU)(h) >= (NU)((*data_177231)->Sup.len)) raiseIndexError();
	(*data_177231)->data[h].Field1 = -1;
	nimln(438, "tables.nim");
	{
		nimln(438, "tables.nim");
		if (!((*t_177223).First < 0)) goto LA6;
		nimln(438, "tables.nim");
		(*t_177223).First = h;
	}
	LA6: ;
	nimln(439, "tables.nim");
	{
		nimln(439, "tables.nim");
		if (!(0 <= (*t_177223).Last)) goto LA10;
		nimln(439, "tables.nim");
		if ((NU)((*t_177223).Last) >= (NU)((*data_177231)->Sup.len)) raiseIndexError();
		(*data_177231)->data[(*t_177223).Last].Field1 = h;
	}
	LA10: ;
	nimln(440, "tables.nim");
	(*t_177223).Last = h;
	popFrame();
}

N_NIMCALL(void, enlarge_177155)(orderedtable176685* t_177164) {
	orderedkeyvaluepairseq176688* n;
	NI TMP703;
	NI h_177198;
	orderedkeyvaluepairseq176688* LOC7;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(444, "tables.nim");
	nimln(444, "tables.nim");
	nimln(444, "tables.nim");
	TMP703 = mulInt((*t_177164).Data->Sup.len, 2);
	n = (orderedkeyvaluepairseq176688*) newSeq((&NTI176688), (NI32)(TMP703));
	nimln(445, "tables.nim");
	h_177198 = (*t_177164).First;
	nimln(446, "tables.nim");
	(*t_177164).First = -1;
	nimln(447, "tables.nim");
	(*t_177164).Last = -1;
	{
		nimln(448, "tables.nim");
		while (1) {
			NI nxt;
			nimln(448, "tables.nim");
			if (!(0 <= h_177198)) goto LA2;
			nimln(449, "tables.nim");
			if ((NU)(h_177198) >= (NU)((*t_177164).Data->Sup.len)) raiseIndexError();
			nxt = (*t_177164).Data->data[h_177198].Field1;
			nimln(450, "tables.nim");
			{
				nimln(450, "tables.nim");
				if ((NU)(h_177198) >= (NU)((*t_177164).Data->Sup.len)) raiseIndexError();
				if (!((*t_177164).Data->data[h_177198].Field0 == ((NU8) 1))) goto LA5;
				nimln(451, "tables.nim");
				if ((NU)(h_177198) >= (NU)((*t_177164).Data->Sup.len)) raiseIndexError();
				if ((NU)(h_177198) >= (NU)((*t_177164).Data->Sup.len)) raiseIndexError();
				rawinsert_177214(t_177164, (&n), (*t_177164).Data->data[h_177198].Field2, (*t_177164).Data->data[h_177198].Field3);
			}
			LA5: ;
			nimln(452, "tables.nim");
			h_177198 = nxt;
		} LA2: ;
	}
	nimln(453, "tables.nim");
	LOC7 = 0;
	LOC7 = (*t_177164).Data;
	unsureAsgnRef((void**) (&(*t_177164).Data), n);
	n = LOC7;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_177110)(orderedtable176685* t_177119, NI key_177123, assetHEX3Aobjecttype149027* val_177125) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_177052((*t_177119), key_177123);
	nimln(190, "tables.nim");
	{
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_177119).Data->Sup.len)) raiseIndexError();
		asgnRef((void**) (&(*t_177119).Data->data[index].Field3), val_177125);
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_173302((*t_177119).Data->Sup.len, (*t_177119).Counter);
			if (!LOC8) goto LA9;
			nimln(184, "tables.nim");
			enlarge_177155(t_177119);
		}
		LA9: ;
		nimln(185, "tables.nim");
		rawinsert_177214(t_177119, (&(*t_177119).Data), key_177123, val_177125);
		nimln(186, "tables.nim");
		(*t_177119).Counter = addInt((*t_177119).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(NI, rawget_177365)(orderedtable176715 t_177372, NI key_177375) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100804(key_177375);
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & (t_177372.Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)(t_177372.Data->Sup.len)) raiseIndexError();
			if (!!((t_177372.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_177372.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_177372.Data->data[h].Field2 == key_177375);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_177372.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_177372.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_173410(h, (t_177372.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, haskey_177351)(orderedtable176715 t_177358, NI key_177361) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	nimln(431, "tables.nim");
	nimln(431, "tables.nim");
	nimln(431, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_177365(t_177358, key_177361);
	result = (0 <= LOC1);
	popFrame();
	return result;
}

N_NIMCALL(assetgroupHEX3Aobjecttype149022*, HEX5BHEX5D_177412)(orderedtable176715 t_177419, NI key_177422) {
	assetgroupHEX3Aobjecttype149022* result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(419, "tables.nim");
	index = rawget_177365(t_177419, key_177422);
	nimln(420, "tables.nim");
	{
		nimln(420, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(420, "tables.nim");
		if ((NU)(index) >= (NU)(t_177419.Data->Sup.len)) raiseIndexError();
		result = t_177419.Data->data[index].Field3;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, rawinsert_177589)(orderedtable176715* t_177598, orderedkeyvaluepairseq176718** data_177606, NI key_177610, assetgroupHEX3Aobjecttype149022* val_177612) {
	NI h;
	NI LOC1;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100804(key_177610);
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_177606)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_177606)->Sup.len)) raiseIndexError();
			if (!((*data_177606)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_173410(h, ((*data_177606)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_177606)->Sup.len)) raiseIndexError();
	(*data_177606)->data[h].Field2 = key_177610;
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_177606)->Sup.len)) raiseIndexError();
	asgnRefNoCycle((void**) (&(*data_177606)->data[h].Field3), val_177612);
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_177606)->Sup.len)) raiseIndexError();
	(*data_177606)->data[h].Field0 = ((NU8) 1);
	nimln(437, "tables.nim");
	if ((NU)(h) >= (NU)((*data_177606)->Sup.len)) raiseIndexError();
	(*data_177606)->data[h].Field1 = -1;
	nimln(438, "tables.nim");
	{
		nimln(438, "tables.nim");
		if (!((*t_177598).First < 0)) goto LA6;
		nimln(438, "tables.nim");
		(*t_177598).First = h;
	}
	LA6: ;
	nimln(439, "tables.nim");
	{
		nimln(439, "tables.nim");
		if (!(0 <= (*t_177598).Last)) goto LA10;
		nimln(439, "tables.nim");
		if ((NU)((*t_177598).Last) >= (NU)((*data_177606)->Sup.len)) raiseIndexError();
		(*data_177606)->data[(*t_177598).Last].Field1 = h;
	}
	LA10: ;
	nimln(440, "tables.nim");
	(*t_177598).Last = h;
	popFrame();
}

N_NIMCALL(void, enlarge_177530)(orderedtable176715* t_177539) {
	orderedkeyvaluepairseq176718* n;
	NI TMP704;
	NI h_177573;
	orderedkeyvaluepairseq176718* LOC7;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(444, "tables.nim");
	nimln(444, "tables.nim");
	nimln(444, "tables.nim");
	TMP704 = mulInt((*t_177539).Data->Sup.len, 2);
	n = (orderedkeyvaluepairseq176718*) newSeq((&NTI176718), (NI32)(TMP704));
	nimln(445, "tables.nim");
	h_177573 = (*t_177539).First;
	nimln(446, "tables.nim");
	(*t_177539).First = -1;
	nimln(447, "tables.nim");
	(*t_177539).Last = -1;
	{
		nimln(448, "tables.nim");
		while (1) {
			NI nxt;
			nimln(448, "tables.nim");
			if (!(0 <= h_177573)) goto LA2;
			nimln(449, "tables.nim");
			if ((NU)(h_177573) >= (NU)((*t_177539).Data->Sup.len)) raiseIndexError();
			nxt = (*t_177539).Data->data[h_177573].Field1;
			nimln(450, "tables.nim");
			{
				nimln(450, "tables.nim");
				if ((NU)(h_177573) >= (NU)((*t_177539).Data->Sup.len)) raiseIndexError();
				if (!((*t_177539).Data->data[h_177573].Field0 == ((NU8) 1))) goto LA5;
				nimln(451, "tables.nim");
				if ((NU)(h_177573) >= (NU)((*t_177539).Data->Sup.len)) raiseIndexError();
				if ((NU)(h_177573) >= (NU)((*t_177539).Data->Sup.len)) raiseIndexError();
				rawinsert_177589(t_177539, (&n), (*t_177539).Data->data[h_177573].Field2, (*t_177539).Data->data[h_177573].Field3);
			}
			LA5: ;
			nimln(452, "tables.nim");
			h_177573 = nxt;
		} LA2: ;
	}
	nimln(453, "tables.nim");
	LOC7 = 0;
	LOC7 = (*t_177539).Data;
	unsureAsgnRef((void**) (&(*t_177539).Data), n);
	n = LOC7;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_177485)(orderedtable176715* t_177494, NI key_177498, assetgroupHEX3Aobjecttype149022* val_177500) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_177365((*t_177494), key_177498);
	nimln(190, "tables.nim");
	{
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_177494).Data->Sup.len)) raiseIndexError();
		asgnRefNoCycle((void**) (&(*t_177494).Data->data[index].Field3), val_177500);
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_173302((*t_177494).Data->Sup.len, (*t_177494).Counter);
			if (!LOC8) goto LA9;
			nimln(184, "tables.nim");
			enlarge_177530(t_177494);
		}
		LA9: ;
		nimln(185, "tables.nim");
		rawinsert_177589(t_177494, (&(*t_177494).Data), key_177498, val_177500);
		nimln(186, "tables.nim");
		(*t_177494).Counter = addInt((*t_177494).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, add_177815)(orderedtable176715* t_177824, NI key_177828, assetgroupHEX3Aobjecttype149022* val_177830) {
	nimfr("add", "tables.nim")
	nimln(184, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(184, "tables.nim");
		nimln(184, "tables.nim");
		LOC3 = 0;
		LOC3 = mustrehash_173302((*t_177824).Data->Sup.len, (*t_177824).Counter);
		if (!LOC3) goto LA4;
		nimln(184, "tables.nim");
		enlarge_177530(t_177824);
	}
	LA4: ;
	nimln(185, "tables.nim");
	rawinsert_177589(t_177824, (&(*t_177824).Data), key_177828, val_177830);
	nimln(186, "tables.nim");
	(*t_177824).Counter = addInt((*t_177824).Counter, 1);
	popFrame();
}

static N_INLINE(NI, len_179448)(orderedtable176685 t_179455) {
	NI result;
	nimfr("len", "tables.nim")
	result = 0;
	nimln(374, "tables.nim");
	result = t_179455.Counter;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_179436)(orderedtable176685 t_179443) {
	NimStringDesc* result;
	nimfr("$", "tables.nim")
	result = 0;
	nimln(240, "tables.nim");
	{
		NI LOC3;
		nimln(240, "tables.nim");
		nimln(240, "tables.nim");
		LOC3 = 0;
		LOC3 = len_179448(t_179443);
		if (!(LOC3 == 0)) goto LA4;
		nimln(241, "tables.nim");
		result = copyString(((NimStringDesc*) &TMP725));
	}
	goto LA1;
	LA4: ;
	{
		nimln(243, "tables.nim");
		result = copyString(((NimStringDesc*) &TMP726));
		{
			NI key_179500;
			assetHEX3Aobjecttype149027* val_179501;
			NI h_179506;
			key_179500 = 0;
			val_179501 = 0;
			nimln(377, "tables.nim");
			h_179506 = t_179443.First;
			{
				nimln(378, "tables.nim");
				while (1) {
					NI nxt_179508;
					nimln(378, "tables.nim");
					if (!(0 <= h_179506)) goto LA9;
					nimln(379, "tables.nim");
					if ((NU)(h_179506) >= (NU)(t_179443.Data->Sup.len)) raiseIndexError();
					nxt_179508 = t_179443.Data->data[h_179506].Field1;
					nimln(380, "tables.nim");
					{
						NimStringDesc* LOC18;
						NimStringDesc* LOC19;
						nimln(380, "tables.nim");
						if ((NU)(h_179506) >= (NU)(t_179443.Data->Sup.len)) raiseIndexError();
						if (!(t_179443.Data->data[h_179506].Field0 == ((NU8) 1))) goto LA12;
						nimln(387, "tables.nim");
						if ((NU)(h_179506) >= (NU)(t_179443.Data->Sup.len)) raiseIndexError();
						key_179500 = t_179443.Data->data[h_179506].Field2;
						nimln(387, "tables.nim");
						if ((NU)(h_179506) >= (NU)(t_179443.Data->Sup.len)) raiseIndexError();
						val_179501 = t_179443.Data->data[h_179506].Field3;
						nimln(245, "tables.nim");
						{
							nimln(245, "tables.nim");
							nimln(245, "tables.nim");
							if (!(1 < result->Sup.len)) goto LA16;
							nimln(245, "tables.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP727));
						}
						LA16: ;
						nimln(246, "tables.nim");
						nimln(246, "tables.nim");
						LOC18 = 0;
						LOC18 = nimIntToStr(key_179500);
						result = resizeString(result, LOC18->Sup.len + 0);
appendString(result, LOC18);
						nimln(247, "tables.nim");
						result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP728));
						nimln(248, "tables.nim");
						nimln(248, "tables.nim");
						LOC19 = 0;
						LOC19 = HEX24_149470(val_179501);
						result = resizeString(result, LOC19->Sup.len + 0);
appendString(result, LOC19);
					}
					LA12: ;
					nimln(381, "tables.nim");
					h_179506 = nxt_179508;
				} LA9: ;
			}
		}
		nimln(249, "tables.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP729));
	}
	LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void) {
static TNimNode* TMP696[4];
static TNimNode* TMP697[3];
NI TMP699;
static char* NIM_CONST TMP698[3] = {
"seEmpty", 
"seFilled", 
"seDeleted"};
static TNimNode* TMP701[4];
static TNimNode TMP675[14];
NTI176691.size = sizeof(orderedkeyvaluepair176691);
NTI176691.kind = 18;
NTI176691.base = 0;
NTI176691.flags = 2;
TMP696[0] = &TMP675[1];
NTI173023.size = sizeof(NU8);
NTI173023.kind = 14;
NTI173023.base = 0;
NTI173023.flags = 3;
for (TMP699 = 0; TMP699 < 3; TMP699++) {
TMP675[TMP699+2].kind = 1;
TMP675[TMP699+2].offset = TMP699;
TMP675[TMP699+2].name = TMP698[TMP699];
TMP697[TMP699] = &TMP675[TMP699+2];
}
TMP675[5].len = 3; TMP675[5].kind = 2; TMP675[5].sons = &TMP697[0];
NTI173023.node = &TMP675[5];
TMP675[1].kind = 1;
TMP675[1].offset = offsetof(orderedkeyvaluepair176691, Field0);
TMP675[1].typ = (&NTI173023);
TMP675[1].name = "Field0";
TMP696[1] = &TMP675[6];
TMP675[6].kind = 1;
TMP675[6].offset = offsetof(orderedkeyvaluepair176691, Field1);
TMP675[6].typ = (&NTI108);
TMP675[6].name = "Field1";
TMP696[2] = &TMP675[7];
TMP675[7].kind = 1;
TMP675[7].offset = offsetof(orderedkeyvaluepair176691, Field2);
TMP675[7].typ = (&NTI108);
TMP675[7].name = "Field2";
TMP696[3] = &TMP675[8];
TMP675[8].kind = 1;
TMP675[8].offset = offsetof(orderedkeyvaluepair176691, Field3);
TMP675[8].typ = (&NTI149011);
TMP675[8].name = "Field3";
TMP675[0].len = 4; TMP675[0].kind = 2; TMP675[0].sons = &TMP696[0];
NTI176691.node = &TMP675[0];
NTI176688.size = sizeof(orderedkeyvaluepairseq176688*);
NTI176688.kind = 24;
NTI176688.base = (&NTI176691);
NTI176688.flags = 2;
NTI176688.marker = TMP700;
NTI176721.size = sizeof(orderedkeyvaluepair176721);
NTI176721.kind = 18;
NTI176721.base = 0;
NTI176721.flags = 2;
TMP701[0] = &TMP675[10];
TMP675[10].kind = 1;
TMP675[10].offset = offsetof(orderedkeyvaluepair176721, Field0);
TMP675[10].typ = (&NTI173023);
TMP675[10].name = "Field0";
TMP701[1] = &TMP675[11];
TMP675[11].kind = 1;
TMP675[11].offset = offsetof(orderedkeyvaluepair176721, Field1);
TMP675[11].typ = (&NTI108);
TMP675[11].name = "Field1";
TMP701[2] = &TMP675[12];
TMP675[12].kind = 1;
TMP675[12].offset = offsetof(orderedkeyvaluepair176721, Field2);
TMP675[12].typ = (&NTI108);
TMP675[12].name = "Field2";
TMP701[3] = &TMP675[13];
TMP675[13].kind = 1;
TMP675[13].offset = offsetof(orderedkeyvaluepair176721, Field3);
TMP675[13].typ = (&NTI149009);
TMP675[13].name = "Field3";
TMP675[9].len = 4; TMP675[9].kind = 2; TMP675[9].sons = &TMP701[0];
NTI176721.node = &TMP675[9];
NTI176718.size = sizeof(orderedkeyvaluepairseq176718*);
NTI176718.kind = 24;
NTI176718.base = (&NTI176721);
NTI176718.flags = 2;
NTI176718.marker = TMP702;
}

