/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_streams.o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_streams.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct ioerror3231 ioerror3231;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct systemerror3229 systemerror3229;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct streamobj103035 streamobj103035;
typedef struct stringstreamobj103587 stringstreamobj103587;
typedef struct filestreamobj103742 filestreamobj103742;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  systemerror3229  {
  Exception Sup;
};
struct  ioerror3231  {
  systemerror3229 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
typedef N_NIMCALL_PTR(void, TY103036) (streamobj103035* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY103040) (streamobj103035* s);
typedef N_NIMCALL_PTR(void, TY103044) (streamobj103035* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY103049) (streamobj103035* s);
typedef N_NIMCALL_PTR(NI, TY103053) (streamobj103035* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY103059) (streamobj103035* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY103065) (streamobj103035* s);
struct  streamobj103035  {
  TNimObject Sup;
TY103036 Closeimpl;
TY103040 Atendimpl;
TY103044 Setpositionimpl;
TY103049 Getpositionimpl;
TY103053 Readdataimpl;
TY103059 Writedataimpl;
TY103065 Flushimpl;
};
struct  stringstreamobj103587  {
  streamobj103035 Sup;
NimStringDesc* Data;
NI Pos;
};
struct  filestreamobj103742  {
  streamobj103035 Sup;
FILE* F;
};
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
N_NIMCALL(ioerror3231*, neweio_103005)(NimStringDesc* msg);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, flush_103077)(streamobj103035* s);
N_NIMCALL(void, close_103093)(streamobj103035* s);
N_NIMCALL(void, close_103109)(streamobj103035* s, streamobj103035* unused);
N_NIMCALL(NIM_BOOL, atend_103119)(streamobj103035* s);
N_NIMCALL(NIM_BOOL, atend_103129)(streamobj103035* s, streamobj103035* unused);
N_NIMCALL(void, setposition_103140)(streamobj103035* s, NI pos);
N_NIMCALL(void, setposition_103150)(streamobj103035* s, streamobj103035* unused, NI pos);
N_NIMCALL(NI, getposition_103161)(streamobj103035* s);
N_NIMCALL(NI, getposition_103171)(streamobj103035* s, streamobj103035* unused);
N_NIMCALL(NI, readdata_103182)(streamobj103035* s, void* buffer, NI buflen);
N_NIMCALL(NI, readdata_103194)(streamobj103035* s, streamobj103035* unused, void* buffer, NI buflen);
N_NIMCALL(void, writedata_103207)(streamobj103035* s, void* buffer, NI buflen);
N_NIMCALL(void, writedata_103218)(streamobj103035* s, streamobj103035* unused, void* buffer, NI buflen);
N_NIMCALL(void, write_103241)(streamobj103035* s, NimStringDesc* x);
N_NIMCALL(void, writeln_103251)(streamobj103035* s, NimStringDesc** args, NI argsLen0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NIM_CHAR, readchar_103298)(streamobj103035* s);
N_NIMCALL(void, read_103315)(streamobj103035* s_103319, NIM_BOOL* result_103323);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, readbool_103309)(streamobj103035* s);
N_NIMCALL(void, read_103346)(streamobj103035* s_103350, NI8* result_103354);
N_NIMCALL(NI8, readint8_103340)(streamobj103035* s);
N_NIMCALL(void, read_103377)(streamobj103035* s_103381, NI16* result_103385);
N_NIMCALL(NI16, readint16_103371)(streamobj103035* s);
N_NIMCALL(void, read_103408)(streamobj103035* s_103412, NI32* result_103416);
N_NIMCALL(NI32, readint32_103402)(streamobj103035* s);
N_NIMCALL(void, read_103439)(streamobj103035* s_103443, NI64* result_103447);
N_NIMCALL(NI64, readint64_103433)(streamobj103035* s);
N_NIMCALL(void, read_103470)(streamobj103035* s_103474, NF32* result_103478);
N_NIMCALL(NF32, readfloat32_103464)(streamobj103035* s);
N_NIMCALL(void, read_103501)(streamobj103035* s_103505, NF* result_103509);
N_NIMCALL(NF, readfloat64_103495)(streamobj103035* s);
N_NIMCALL(NimStringDesc*, readstr_103526)(streamobj103035* s, NI length);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NIM_BOOL, readline_103541)(streamobj103035* s, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, readline_103564)(streamobj103035* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NIM_BOOL, ssatend_103598)(streamobj103035* s_103600);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(NI, clamp_103615)(NI x_103619, NI a_103621, NI b_103623);
N_NIMCALL(void, sssetposition_103609)(streamobj103035* s_103611, NI pos);
N_NIMCALL(NI, ssgetposition_103636)(streamobj103035* s_103638);
N_NIMCALL(NI, ssreaddata_103647)(streamobj103035* s_103649, void* buffer, NI buflen);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, sswritedata_103677)(streamobj103035* s_103679, void* buffer, NI buflen);
N_NIMCALL(void, ssclose_103703)(streamobj103035* s_103705);
N_NIMCALL(stringstreamobj103587*, newstringstream_103713)(NimStringDesc* s);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP155)(void* p, NI op);
N_NIMCALL(void, fsclose_103746)(streamobj103035* s);
N_NIMCALL(void, fsflush_103769)(streamobj103035* s);
N_NIMCALL(NIM_BOOL, fsatend_103775)(streamobj103035* s);
N_NIMCALL(NIM_BOOL, endoffile_12830)(FILE* f);
N_NIMCALL(void, fssetposition_103782)(streamobj103035* s, NI pos);
N_NIMCALL(void, setfilepos_13051)(FILE* f, NI64 pos);
N_NIMCALL(NI, fsgetposition_103789)(streamobj103035* s);
N_NIMCALL(NI64, getfilepos_13055)(FILE* f);
N_NIMCALL(NI64, chckRange64)(NI64 i, NI64 a, NI64 b);
N_NIMCALL(NI, fsreaddata_103796)(streamobj103035* s, void* buffer, NI buflen);
N_NIMCALL(NI, readbuffer_13027)(FILE* f, void* buffer, NI len);
N_NIMCALL(void, fswritedata_103805)(streamobj103035* s, void* buffer, NI buflen);
N_NIMCALL(NI, writebuffer_13046)(FILE* f, void* buffer, NI len);
N_NIMCALL(filestreamobj103742*, newfilestream_103813)(FILE* f);
N_NIMCALL(void, TMP157)(void* p, NI op);
N_NIMCALL(filestreamobj103742*, newfilestream_103836)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(NIM_BOOL, open_12603)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void, TMP334)(void* p, NI op);
STRING_LITERAL(TMP148, "\015\012", 2);
STRING_LITERAL(TMP149, "cannot read from stream", 23);
STRING_LITERAL(TMP150, "", 0);
STRING_LITERAL(TMP156, "cannot write to stream", 22);
extern TNimType NTI12801; /* ref IOError */
extern TNimType NTI3231; /* IOError */
extern TFrame* frameptr_16242;
extern tgcheap47016 gch_47044;
extern TNimType NTI3211; /* RootObj */
TNimType NTI103035; /* StreamObj */
TNimType NTI103036; /* proc (Stream){.gcsafe.} */
TNimType NTI103040; /* proc (Stream): bool{.gcsafe.} */
TNimType NTI103044; /* proc (Stream, int){.gcsafe.} */
TNimType NTI103049; /* proc (Stream): int{.gcsafe.} */
TNimType NTI103053; /* proc (Stream, pointer, int): int{.gcsafe.} */
TNimType NTI103059; /* proc (Stream, pointer, int){.gcsafe.} */
TNimType NTI103065; /* proc (Stream){.gcsafe.} */
TNimType NTI103587; /* StringStreamObj */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
TNimType NTI103585; /* StringStream */
TNimType NTI103742; /* FileStreamObj */
extern TNimType NTI12404; /* File */
TNimType NTI103740; /* FileStream */
TNimType NTI103033; /* Stream */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell44933* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48646(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50204(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(ioerror3231*, neweio_103005)(NimStringDesc* msg) {
	ioerror3231* result;
	NimStringDesc* LOC1;
	nimfr("newEIO", "streams.nim")
	result = 0;
	nimln(18, "streams.nim");
	result = (ioerror3231*) newObj((&NTI12801), sizeof(ioerror3231));
	(*result).Sup.Sup.Sup.m_type = (&NTI3231);
	nimln(19, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).Sup.Sup.message; (*result).Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, flush_103077)(streamobj103035* s) {
	nimfr("flush", "streams.nim")
	nimln(42, "streams.nim");
	{
		nimln(42, "streams.nim");
		nimln(42, "streams.nim");
		if (!!((*s).Flushimpl == 0)) goto LA3;
		nimln(42, "streams.nim");
		(*s).Flushimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_103093)(streamobj103035* s) {
	nimfr("close", "streams.nim")
	nimln(46, "streams.nim");
	{
		nimln(46, "streams.nim");
		nimln(46, "streams.nim");
		if (!!((*s).Closeimpl == 0)) goto LA3;
		nimln(46, "streams.nim");
		(*s).Closeimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_103109)(streamobj103035* s, streamobj103035* unused) {
	nimfr("close", "streams.nim")
	nimln(50, "streams.nim");
	(*s).Closeimpl(s);
	popFrame();
}

N_NIMCALL(NIM_BOOL, atend_103119)(streamobj103035* s) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(55, "streams.nim");
	result = (*s).Atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, atend_103129)(streamobj103035* s, streamobj103035* unused) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(60, "streams.nim");
	result = (*s).Atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(void, setposition_103140)(streamobj103035* s, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(64, "streams.nim");
	(*s).Setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(void, setposition_103150)(streamobj103035* s, streamobj103035* unused, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(68, "streams.nim");
	(*s).Setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(NI, getposition_103161)(streamobj103035* s) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(72, "streams.nim");
	result = (*s).Getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, getposition_103171)(streamobj103035* s, streamobj103035* unused) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(76, "streams.nim");
	result = (*s).Getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_103182)(streamobj103035* s, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(80, "streams.nim");
	result = (*s).Readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_103194)(streamobj103035* s, streamobj103035* unused, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(85, "streams.nim");
	result = (*s).Readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(void, writedata_103207)(streamobj103035* s, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(90, "streams.nim");
	(*s).Writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, writedata_103218)(streamobj103035* s, streamobj103035* unused, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(96, "streams.nim");
	(*s).Writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, write_103241)(streamobj103035* s, NimStringDesc* x) {
	nimfr("write", "streams.nim")
	nimln(111, "streams.nim");
	nimln(111, "streams.nim");
	writedata_103207(s, ((void*) (x->data)), x->Sup.len);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, writeln_103251)(streamobj103035* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeln", "streams.nim")
	{
		NimStringDesc* str_103267;
		NI i_103271;
		str_103267 = 0;
		nimln(1649, "system.nim");
		i_103271 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_103271 < argsLen0)) goto LA3;
				nimln(1651, "system.nim");
				if ((NU)(i_103271) >= (NU)(argsLen0)) raiseIndexError();
				str_103267 = args[i_103271];
				nimln(116, "streams.nim");
				write_103241(s, str_103267);
				nimln(1652, "system.nim");
				i_103271 = addInt(i_103271, 1);
			} LA3: ;
		}
	}
	nimln(117, "streams.nim");
	write_103241(s, ((NimStringDesc*) &TMP148));
	popFrame();
}

N_NIMCALL(NIM_CHAR, readchar_103298)(streamobj103035* s) {
	NIM_CHAR result;
	nimfr("readChar", "streams.nim")
	result = 0;
	nimln(127, "streams.nim");
	{
		NI LOC3;
		nimln(127, "streams.nim");
		nimln(127, "streams.nim");
		nimln(127, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_103182(s, ((void*) ((&result))), 1);
		if (!!((LOC3 == 1))) goto LA4;
		nimln(127, "streams.nim");
		result = 0;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(void, read_103315)(streamobj103035* s_103319, NIM_BOOL* result_103323) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		ioerror3231* LOC6;
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_103182(s_103319, ((void*) (result_103323)), 1);
		if (!!((LOC3 == 1))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_103005(((NimStringDesc*) &TMP149));
		nimln(122, "streams.nim");
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, readbool_103309)(streamobj103035* s) {
	NIM_BOOL result;
	nimfr("readBool", "streams.nim")
	result = 0;
	nimln(131, "streams.nim");
	read_103315(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_103346)(streamobj103035* s_103350, NI8* result_103354) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		ioerror3231* LOC6;
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_103182(s_103350, ((void*) (result_103354)), 1);
		if (!!((LOC3 == 1))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_103005(((NimStringDesc*) &TMP149));
		nimln(122, "streams.nim");
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, readint8_103340)(streamobj103035* s) {
	NI8 result;
	nimfr("readInt8", "streams.nim")
	result = 0;
	nimln(135, "streams.nim");
	read_103346(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_103377)(streamobj103035* s_103381, NI16* result_103385) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		ioerror3231* LOC6;
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_103182(s_103381, ((void*) (result_103385)), 2);
		if (!!((LOC3 == 2))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_103005(((NimStringDesc*) &TMP149));
		nimln(122, "streams.nim");
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, readint16_103371)(streamobj103035* s) {
	NI16 result;
	nimfr("readInt16", "streams.nim")
	result = 0;
	nimln(139, "streams.nim");
	read_103377(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_103408)(streamobj103035* s_103412, NI32* result_103416) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		ioerror3231* LOC6;
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_103182(s_103412, ((void*) (result_103416)), 4);
		if (!!((LOC3 == 4))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_103005(((NimStringDesc*) &TMP149));
		nimln(122, "streams.nim");
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, readint32_103402)(streamobj103035* s) {
	NI32 result;
	nimfr("readInt32", "streams.nim")
	result = 0;
	nimln(143, "streams.nim");
	read_103408(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_103439)(streamobj103035* s_103443, NI64* result_103447) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		ioerror3231* LOC6;
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_103182(s_103443, ((void*) (result_103447)), 8);
		if (!!((LOC3 == 8))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_103005(((NimStringDesc*) &TMP149));
		nimln(122, "streams.nim");
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, readint64_103433)(streamobj103035* s) {
	NI64 result;
	nimfr("readInt64", "streams.nim")
	result = 0;
	nimln(147, "streams.nim");
	read_103439(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_103470)(streamobj103035* s_103474, NF32* result_103478) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		ioerror3231* LOC6;
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_103182(s_103474, ((void*) (result_103478)), 4);
		if (!!((LOC3 == 4))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_103005(((NimStringDesc*) &TMP149));
		nimln(122, "streams.nim");
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, readfloat32_103464)(streamobj103035* s) {
	NF32 result;
	nimfr("readFloat32", "streams.nim")
	result = 0;
	nimln(151, "streams.nim");
	read_103470(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_103501)(streamobj103035* s_103505, NF* result_103509) {
	nimfr("read", "streams.nim")
	nimln(121, "streams.nim");
	{
		NI LOC3;
		ioerror3231* LOC6;
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		nimln(121, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_103182(s_103505, ((void*) (result_103509)), 8);
		if (!!((LOC3 == 8))) goto LA4;
		nimln(122, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_103005(((NimStringDesc*) &TMP149));
		nimln(122, "streams.nim");
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, readfloat64_103495)(streamobj103035* s) {
	NF result;
	nimfr("readFloat64", "streams.nim")
	result = 0;
	nimln(155, "streams.nim");
	read_103501(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readstr_103526)(streamobj103035* s, NI length) {
	NimStringDesc* result;
	NI l;
	nimfr("readStr", "streams.nim")
	result = 0;
	nimln(160, "streams.nim");
	nimln(160, "streams.nim");
	result = mnewString(length);
	nimln(161, "streams.nim");
	if ((NU)(0) > (NU)(result->Sup.len)) raiseIndexError();
	l = readdata_103182(s, ((void*) ((&result->data[0]))), length);
	nimln(162, "streams.nim");
	{
		nimln(162, "streams.nim");
		nimln(162, "streams.nim");
		if (!!((l == length))) goto LA3;
		nimln(162, "streams.nim");
		result = setLengthStr(result, l);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, readline_103541)(streamobj103035* s, NimStringDesc** line) {
	NIM_BOOL result;
	nimfr("readLine", "streams.nim")
	result = 0;
	nimln(171, "streams.nim");
	(*line) = setLengthStr((*line), 0);
	{
		nimln(172, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(173, "streams.nim");
			c = readchar_103298(s);
			nimln(174, "streams.nim");
			{
				nimln(174, "streams.nim");
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(175, "streams.nim");
				c = readchar_103298(s);
				nimln(176, "streams.nim");
				goto LA1;
			}
			goto LA3;
			LA5: ;
			{
				nimln(177, "streams.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA8;
				nimln(177, "streams.nim");
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
				nimln(178, "streams.nim");
				if (!((NU8)(c) == (NU8)(0))) goto LA11;
				nimln(179, "streams.nim");
				{
					nimln(179, "streams.nim");
					nimln(179, "streams.nim");
					if (!(0 < (*line)->Sup.len)) goto LA15;
					nimln(179, "streams.nim");
					goto LA1;
				}
				goto LA13;
				LA15: ;
				{
					nimln(180, "streams.nim");
					nimln(180, "streams.nim");
					result = NIM_FALSE;
					goto BeforeRet;
				}
				LA13: ;
			}
			goto LA3;
			LA11: ;
			LA3: ;
			nimln(181, "streams.nim");
			(*line) = addChar((*line), c);
		}
	} LA1: ;
	nimln(182, "streams.nim");
	result = NIM_TRUE;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readline_103564)(streamobj103035* s) {
	NimStringDesc* result;
	nimfr("readLine", "streams.nim")
	result = 0;
	nimln(187, "streams.nim");
	result = copyString(((NimStringDesc*) &TMP150));
	{
		nimln(188, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(189, "streams.nim");
			c = readchar_103298(s);
			nimln(190, "streams.nim");
			{
				nimln(190, "streams.nim");
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(191, "streams.nim");
				c = readchar_103298(s);
				nimln(192, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(193, "streams.nim");
			{
				NIM_BOOL LOC9;
				nimln(193, "streams.nim");
				LOC9 = 0;
				nimln(193, "streams.nim");
				LOC9 = ((NU8)(c) == (NU8)(10));
				if (LOC9) goto LA10;
				nimln(193, "streams.nim");
				LOC9 = ((NU8)(c) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				nimln(194, "streams.nim");
				goto LA1;
			}
			goto LA7;
			LA11: ;
			{
				nimln(196, "streams.nim");
				result = addChar(result, c);
			}
			LA7: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ssatend_103598)(streamobj103035* s_103600) {
	NIM_BOOL result;
	stringstreamobj103587* s;
	nimfr("ssAtEnd", "streams.nim")
	result = 0;
	nimln(207, "streams.nim");
	if (s_103600) chckObj((*s_103600).Sup.m_type, (&NTI103587));
	s = ((stringstreamobj103587*) (s_103600));
	nimln(208, "streams.nim");
	nimln(208, "streams.nim");
	nimln(208, "streams.nim");
	nimln(208, "streams.nim");
	result = ((*s).Data->Sup.len <= (*s).Pos);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sssetposition_103609)(streamobj103035* s_103611, NI pos) {
	stringstreamobj103587* s;
	nimfr("ssSetPosition", "streams.nim")
	nimln(211, "streams.nim");
	if (s_103611) chckObj((*s_103611).Sup.m_type, (&NTI103587));
	s = ((stringstreamobj103587*) (s_103611));
	nimln(212, "streams.nim");
	nimln(212, "streams.nim");
	(*s).Pos = clamp_103615(pos, 0, ((*s).Data->Sup.len-1));
	popFrame();
}

N_NIMCALL(NI, ssgetposition_103636)(streamobj103035* s_103638) {
	NI result;
	stringstreamobj103587* s;
	nimfr("ssGetPosition", "streams.nim")
	result = 0;
	nimln(215, "streams.nim");
	if (s_103638) chckObj((*s_103638).Sup.m_type, (&NTI103587));
	s = ((stringstreamobj103587*) (s_103638));
	nimln(216, "streams.nim");
	nimln(216, "streams.nim");
	result = (*s).Pos;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, ssreaddata_103647)(streamobj103035* s_103649, void* buffer, NI buflen) {
	NI result;
	stringstreamobj103587* s;
	NI TMP153;
	nimfr("ssReadData", "streams.nim")
	result = 0;
	nimln(219, "streams.nim");
	if (s_103649) chckObj((*s_103649).Sup.m_type, (&NTI103587));
	s = ((stringstreamobj103587*) (s_103649));
	nimln(220, "streams.nim");
	nimln(220, "streams.nim");
	nimln(220, "streams.nim");
	nimln(220, "streams.nim");
	TMP153 = subInt((*s).Data->Sup.len, (*s).Pos);
	result = ((buflen <= (NI32)(TMP153)) ? buflen : (NI32)(TMP153));
	nimln(221, "streams.nim");
	{
		nimln(221, "streams.nim");
		if (!(0 < result)) goto LA3;
		nimln(222, "streams.nim");
		if ((NU)((*s).Pos) > (NU)((*s).Data->Sup.len)) raiseIndexError();
		memcpy(buffer, ((void*) ((&(*s).Data->data[(*s).Pos]))), result);
		nimln(223, "streams.nim");
		(*s).Pos = addInt((*s).Pos, result);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sswritedata_103677)(streamobj103035* s_103679, void* buffer, NI buflen) {
	stringstreamobj103587* s;
	nimfr("ssWriteData", "streams.nim")
	nimln(226, "streams.nim");
	if (s_103679) chckObj((*s_103679).Sup.m_type, (&NTI103587));
	s = ((stringstreamobj103587*) (s_103679));
	nimln(227, "streams.nim");
	{
		NI TMP154;
		nimln(227, "streams.nim");
		if (!(0 < buflen)) goto LA3;
		nimln(228, "streams.nim");
		nimln(228, "streams.nim");
		nimln(228, "streams.nim");
		TMP154 = addInt((*s).Data->Sup.len, buflen);
		(*s).Data = setLengthStr((*s).Data, (NI32)(TMP154));
		nimln(229, "streams.nim");
		if ((NU)((*s).Pos) > (NU)((*s).Data->Sup.len)) raiseIndexError();
		memcpy(((void*) ((&(*s).Data->data[(*s).Pos]))), buffer, buflen);
		nimln(230, "streams.nim");
		(*s).Pos = addInt((*s).Pos, buflen);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, ssclose_103703)(streamobj103035* s_103705) {
	stringstreamobj103587* s;
	NimStringDesc* LOC1;
	nimfr("ssClose", "streams.nim")
	nimln(233, "streams.nim");
	if (s_103705) chckObj((*s_103705).Sup.m_type, (&NTI103587));
	s = ((stringstreamobj103587*) (s_103705));
	nimln(234, "streams.nim");
	LOC1 = 0;
	LOC1 = (*s).Data; (*s).Data = copyStringRC1(NIM_NIL);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP155)(void* p, NI op) {
	stringstreamobj103587* a;
	a = (stringstreamobj103587*)p;
	nimGCvisit((void*)(*a).Data, op);
}

N_NIMCALL(stringstreamobj103587*, newstringstream_103713)(NimStringDesc* s) {
	stringstreamobj103587* result;
	NimStringDesc* LOC1;
	nimfr("newStringStream", "streams.nim")
	result = 0;
	nimln(238, "streams.nim");
	result = (stringstreamobj103587*) newObj((&NTI103585), sizeof(stringstreamobj103587));
	(*result).Sup.Sup.m_type = (&NTI103587);
	nimln(239, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).Data; (*result).Data = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(240, "streams.nim");
	(*result).Pos = 0;
	nimln(241, "streams.nim");
	(*result).Sup.Closeimpl = ssclose_103703;
	nimln(242, "streams.nim");
	(*result).Sup.Atendimpl = ssatend_103598;
	nimln(243, "streams.nim");
	(*result).Sup.Setpositionimpl = sssetposition_103609;
	nimln(244, "streams.nim");
	(*result).Sup.Getpositionimpl = ssgetposition_103636;
	nimln(245, "streams.nim");
	(*result).Sup.Readdataimpl = ssreaddata_103647;
	nimln(246, "streams.nim");
	(*result).Sup.Writedataimpl = sswritedata_103677;
	popFrame();
	return result;
}

N_NIMCALL(void, fsclose_103746)(streamobj103035* s) {
	nimfr("fsClose", "streams.nim")
	nimln(257, "streams.nim");
	{
		nimln(257, "streams.nim");
		nimln(257, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI103742));
		if (!!(((*((filestreamobj103742*) (s))).F == NIM_NIL))) goto LA3;
		nimln(258, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI103742));
		fclose((*((filestreamobj103742*) (s))).F);
		nimln(259, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI103742));
		(*((filestreamobj103742*) (s))).F = NIM_NIL;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, fsflush_103769)(streamobj103035* s) {
	nimfr("fsFlush", "streams.nim")
	nimln(260, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI103742));
	fflush((*((filestreamobj103742*) (s))).F);
	popFrame();
}

N_NIMCALL(NIM_BOOL, fsatend_103775)(streamobj103035* s) {
	NIM_BOOL result;
	nimfr("fsAtEnd", "streams.nim")
	result = 0;
	nimln(261, "streams.nim");
	nimln(261, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI103742));
	result = endoffile_12830((*((filestreamobj103742*) (s))).F);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, fssetposition_103782)(streamobj103035* s, NI pos) {
	nimfr("fsSetPosition", "streams.nim")
	nimln(262, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI103742));
	setfilepos_13051((*((filestreamobj103742*) (s))).F, ((NI64) (pos)));
	popFrame();
}

N_NIMCALL(NI, fsgetposition_103789)(streamobj103035* s) {
	NI result;
	NI64 LOC1;
	nimfr("fsGetPosition", "streams.nim")
	result = 0;
	nimln(263, "streams.nim");
	nimln(263, "streams.nim");
	nimln(263, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI103742));
	LOC1 = 0;
	LOC1 = getfilepos_13055((*((filestreamobj103742*) (s))).F);
	result = ((NI)chckRange64(LOC1, (-2147483647 -1), 2147483647));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, fsreaddata_103796)(streamobj103035* s, void* buffer, NI buflen) {
	NI result;
	nimfr("fsReadData", "streams.nim")
	result = 0;
	nimln(266, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI103742));
	result = readbuffer_13027((*((filestreamobj103742*) (s))).F, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(void, fswritedata_103805)(streamobj103035* s, void* buffer, NI buflen) {
	nimfr("fsWriteData", "streams.nim")
	nimln(269, "streams.nim");
	{
		NI LOC3;
		ioerror3231* LOC6;
		nimln(269, "streams.nim");
		nimln(269, "streams.nim");
		nimln(269, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI103742));
		LOC3 = 0;
		LOC3 = writebuffer_13046((*((filestreamobj103742*) (s))).F, buffer, buflen);
		if (!!((LOC3 == buflen))) goto LA4;
		nimln(270, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_103005(((NimStringDesc*) &TMP156));
		nimln(270, "streams.nim");
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}
N_NIMCALL(void, TMP157)(void* p, NI op) {
	filestreamobj103742* a;
	a = (filestreamobj103742*)p;
}

N_NIMCALL(filestreamobj103742*, newfilestream_103813)(FILE* f) {
	filestreamobj103742* result;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	nimln(274, "streams.nim");
	result = (filestreamobj103742*) newObj((&NTI103740), sizeof(filestreamobj103742));
	(*result).Sup.Sup.m_type = (&NTI103742);
	nimln(275, "streams.nim");
	(*result).F = f;
	nimln(276, "streams.nim");
	(*result).Sup.Closeimpl = fsclose_103746;
	nimln(277, "streams.nim");
	(*result).Sup.Atendimpl = fsatend_103775;
	nimln(278, "streams.nim");
	(*result).Sup.Setpositionimpl = fssetposition_103782;
	nimln(279, "streams.nim");
	(*result).Sup.Getpositionimpl = fsgetposition_103789;
	nimln(280, "streams.nim");
	(*result).Sup.Readdataimpl = fsreaddata_103796;
	nimln(281, "streams.nim");
	(*result).Sup.Writedataimpl = fswritedata_103805;
	nimln(282, "streams.nim");
	(*result).Sup.Flushimpl = fsflush_103769;
	popFrame();
	return result;
}

N_NIMCALL(filestreamobj103742*, newfilestream_103836)(NimStringDesc* filename, NU8 mode) {
	filestreamobj103742* result;
	FILE* f;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	f = 0;
	nimln(289, "streams.nim");
	{
		NIM_BOOL LOC3;
		nimln(289, "streams.nim");
		LOC3 = 0;
		LOC3 = open_12603(&f, filename, mode, -1);
		if (!LOC3) goto LA4;
		nimln(289, "streams.nim");
		result = newfilestream_103813(f);
	}
	LA4: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP334)(void* p, NI op) {
	streamobj103035* a;
	a = (streamobj103035*)p;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit)(void) {
	nimfr("streams", "streams.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit)(void) {
static TNimNode* TMP151[7];
static TNimNode* TMP152[2];
static TNimNode TMP146[12];
NTI103035.size = sizeof(streamobj103035);
NTI103035.kind = 17;
NTI103035.base = (&NTI3211);
NTI103035.flags = 1;
TMP151[0] = &TMP146[1];
NTI103036.size = sizeof(TY103036);
NTI103036.kind = 25;
NTI103036.base = 0;
NTI103036.flags = 3;
TMP146[1].kind = 1;
TMP146[1].offset = offsetof(streamobj103035, Closeimpl);
TMP146[1].typ = (&NTI103036);
TMP146[1].name = "closeImpl";
TMP151[1] = &TMP146[2];
NTI103040.size = sizeof(TY103040);
NTI103040.kind = 25;
NTI103040.base = 0;
NTI103040.flags = 3;
TMP146[2].kind = 1;
TMP146[2].offset = offsetof(streamobj103035, Atendimpl);
TMP146[2].typ = (&NTI103040);
TMP146[2].name = "atEndImpl";
TMP151[2] = &TMP146[3];
NTI103044.size = sizeof(TY103044);
NTI103044.kind = 25;
NTI103044.base = 0;
NTI103044.flags = 3;
TMP146[3].kind = 1;
TMP146[3].offset = offsetof(streamobj103035, Setpositionimpl);
TMP146[3].typ = (&NTI103044);
TMP146[3].name = "setPositionImpl";
TMP151[3] = &TMP146[4];
NTI103049.size = sizeof(TY103049);
NTI103049.kind = 25;
NTI103049.base = 0;
NTI103049.flags = 3;
TMP146[4].kind = 1;
TMP146[4].offset = offsetof(streamobj103035, Getpositionimpl);
TMP146[4].typ = (&NTI103049);
TMP146[4].name = "getPositionImpl";
TMP151[4] = &TMP146[5];
NTI103053.size = sizeof(TY103053);
NTI103053.kind = 25;
NTI103053.base = 0;
NTI103053.flags = 3;
TMP146[5].kind = 1;
TMP146[5].offset = offsetof(streamobj103035, Readdataimpl);
TMP146[5].typ = (&NTI103053);
TMP146[5].name = "readDataImpl";
TMP151[5] = &TMP146[6];
NTI103059.size = sizeof(TY103059);
NTI103059.kind = 25;
NTI103059.base = 0;
NTI103059.flags = 3;
TMP146[6].kind = 1;
TMP146[6].offset = offsetof(streamobj103035, Writedataimpl);
TMP146[6].typ = (&NTI103059);
TMP146[6].name = "writeDataImpl";
TMP151[6] = &TMP146[7];
NTI103065.size = sizeof(TY103065);
NTI103065.kind = 25;
NTI103065.base = 0;
NTI103065.flags = 3;
TMP146[7].kind = 1;
TMP146[7].offset = offsetof(streamobj103035, Flushimpl);
TMP146[7].typ = (&NTI103065);
TMP146[7].name = "flushImpl";
TMP146[0].len = 7; TMP146[0].kind = 2; TMP146[0].sons = &TMP151[0];
NTI103035.node = &TMP146[0];
NTI103587.size = sizeof(stringstreamobj103587);
NTI103587.kind = 17;
NTI103587.base = (&NTI103035);
TMP152[0] = &TMP146[9];
TMP146[9].kind = 1;
TMP146[9].offset = offsetof(stringstreamobj103587, Data);
TMP146[9].typ = (&NTI149);
TMP146[9].name = "data";
TMP152[1] = &TMP146[10];
TMP146[10].kind = 1;
TMP146[10].offset = offsetof(stringstreamobj103587, Pos);
TMP146[10].typ = (&NTI108);
TMP146[10].name = "pos";
TMP146[8].len = 2; TMP146[8].kind = 2; TMP146[8].sons = &TMP152[0];
NTI103587.node = &TMP146[8];
NTI103585.size = sizeof(stringstreamobj103587*);
NTI103585.kind = 22;
NTI103585.base = (&NTI103587);
NTI103585.marker = TMP155;
NTI103742.size = sizeof(filestreamobj103742);
NTI103742.kind = 17;
NTI103742.base = (&NTI103035);
NTI103742.flags = 1;
TMP146[11].kind = 1;
TMP146[11].offset = offsetof(filestreamobj103742, F);
TMP146[11].typ = (&NTI12404);
TMP146[11].name = "f";
NTI103742.node = &TMP146[11];
NTI103740.size = sizeof(filestreamobj103742*);
NTI103740.kind = 22;
NTI103740.base = (&NTI103742);
NTI103740.marker = TMP157;
NTI103033.size = sizeof(streamobj103035*);
NTI103033.kind = 22;
NTI103033.base = (&NTI103035);
NTI103033.marker = TMP334;
}

