/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_lexbase.o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_lexbase.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct baselexer105011 baselexer105011;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct streamobj103035 streamobj103035;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 TY75869[32];
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  baselexer105011  {
  TNimObject Sup;
NI Bufpos;
NCSTRING Buf;
NI Buflen;
streamobj103035* Input;
NI Linenumber;
NI Sentinel;
NI Linestart;
NIM_BOOL Fileopened;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY103036) (streamobj103035* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY103040) (streamobj103035* s);
typedef N_NIMCALL_PTR(void, TY103044) (streamobj103035* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY103049) (streamobj103035* s);
typedef N_NIMCALL_PTR(NI, TY103053) (streamobj103035* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY103059) (streamobj103035* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY103065) (streamobj103035* s);
struct  streamobj103035  {
  TNimObject Sup;
TY103036 Closeimpl;
TY103040 Atendimpl;
TY103044 Setpositionimpl;
TY103049 Getpositionimpl;
TY103053 Readdataimpl;
TY103059 Writedataimpl;
TY103065 Flushimpl;
};
N_NIMCALL(void, close_105037)(baselexer105011* l);
N_NOCONV(void, dealloc_5848)(void* p);
N_NIMCALL(void, close_103093)(streamobj103035* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, fillbuffer_105089)(baselexer105011* l);
N_NIMCALL(void, failedassertimpl_86825)(NimStringDesc* msg);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NI, readdata_103182)(streamobj103035* s, void* buffer, NI buflen);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOCONV(void*, realloc_5833)(void* p, NI newsize);
N_NIMCALL(NI, fillbaselexer_105828)(baselexer105011* l, NI pos);
N_NIMCALL(NI, handlecr_105058)(baselexer105011* l, NI pos);
N_NIMCALL(NI, handlelf_105066)(baselexer105011* l, NI pos);
N_NIMCALL(void, skiputf8bom_106419)(baselexer105011* l);
N_NIMCALL(void, open_105027)(baselexer105011* l, streamobj103035* input, NI buflen);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NOCONV(void*, alloc_5801)(NI size);
N_NIMCALL(NI, getcolnumber_105051)(baselexer105011* l, NI pos);
N_NIMCALL(NimStringDesc*, getcurrentline_105044)(baselexer105011* l, NIM_BOOL marker);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
NIM_CONST TY75869 newlines_105005 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP158, "L.sentinel < L.bufLen ", 22);
STRING_LITERAL(TMP161, "toCopy >= 0 ", 12);
STRING_LITERAL(TMP169, "s < L.bufLen ", 13);
STRING_LITERAL(TMP173, "L.bufLen - oldBufLen == oldBufLen ", 34);
STRING_LITERAL(TMP179, "pos <= L.sentinel ", 18);
STRING_LITERAL(TMP181, "L.buf[pos] == \'\\x0D\' ", 21);
STRING_LITERAL(TMP182, "L.buf[pos] == \'\\x0A\' ", 21);
STRING_LITERAL(TMP183, "bufLen > 0 ", 11);
STRING_LITERAL(TMP184, "input != nil ", 13);
STRING_LITERAL(TMP188, "", 0);
STRING_LITERAL(TMP189, "\015\012", 2);
STRING_LITERAL(TMP191, "^\015\012", 3);
extern TFrame* frameptr_16242;
extern TNimType NTI3211; /* RootObj */
TNimType NTI105011; /* BaseLexer */
extern TNimType NTI108; /* int */
extern TNimType NTI151; /* cstring */
extern TNimType NTI103033; /* Stream */
extern TNimType NTI138; /* bool */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(void, close_105037)(baselexer105011* l) {
	nimfr("close", "lexbase.nim")
	nimln(68, "lexbase.nim");
	dealloc_5848(((void*) ((*l).Buf)));
	nimln(69, "lexbase.nim");
	close_103093((*l).Input);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (-2147483647 -1));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI32)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, fillbuffer_105089)(baselexer105011* l) {
	NI charsread;
	NI tocopy;
	NI s;
	NI oldbuflen;
	NI TMP159;
	NI TMP160;
	NI TMP164;
	NI TMP165;
	NI LOC13;
	NI TMP166;
	NI TMP167;
	nimfr("fillBuffer", "lexbase.nim")
	charsread = 0;
	tocopy = 0;
	s = 0;
	oldbuflen = 0;
	nimln(79, "lexbase.nim");
	{
		nimln(79, "lexbase.nim");
		nimln(79, "lexbase.nim");
		if (!!(((*l).Sentinel < (*l).Buflen))) goto LA3;
		nimln(79, "lexbase.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP158));
	}
	LA3: ;
	nimln(80, "lexbase.nim");
	nimln(80, "lexbase.nim");
	nimln(80, "lexbase.nim");
	TMP159 = subInt((*l).Buflen, (*l).Sentinel);
	TMP160 = subInt((NI32)(TMP159), 1);
	tocopy = (NI32)(TMP160);
	nimln(81, "lexbase.nim");
	{
		nimln(81, "lexbase.nim");
		nimln(81, "lexbase.nim");
		if (!!((0 <= tocopy))) goto LA7;
		nimln(81, "lexbase.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP161));
	}
	LA7: ;
	nimln(82, "lexbase.nim");
	{
		NI TMP162;
		NI TMP163;
		nimln(82, "lexbase.nim");
		if (!(0 < tocopy)) goto LA11;
		nimln(83, "lexbase.nim");
		nimln(83, "lexbase.nim");
		TMP162 = addInt((*l).Sentinel, 1);
		nimln(83, "lexbase.nim");
		TMP163 = mulInt(tocopy, 1);
		memmove(((void*) ((*l).Buf)), ((void*) ((&(*l).Buf[(NI32)(TMP162)]))), (NI32)(TMP163));
	}
	LA11: ;
	nimln(85, "lexbase.nim");
	nimln(86, "lexbase.nim");
	nimln(85, "lexbase.nim");
	nimln(86, "lexbase.nim");
	nimln(86, "lexbase.nim");
	TMP164 = addInt((*l).Sentinel, 1);
	TMP165 = mulInt((NI32)(TMP164), 1);
	LOC13 = 0;
	LOC13 = readdata_103182((*l).Input, ((void*) ((&(*l).Buf[tocopy]))), (NI32)(TMP165));
	TMP166 = divInt(LOC13, 1);
	charsread = (NI32)(TMP166);
	nimln(87, "lexbase.nim");
	nimln(87, "lexbase.nim");
	TMP167 = addInt(tocopy, charsread);
	s = (NI32)(TMP167);
	nimln(88, "lexbase.nim");
	{
		NI TMP168;
		nimln(88, "lexbase.nim");
		nimln(88, "lexbase.nim");
		TMP168 = addInt((*l).Sentinel, 1);
		if (!(charsread < (NI32)(TMP168))) goto LA16;
		nimln(89, "lexbase.nim");
		(*l).Buf[s] = 0;
		nimln(90, "lexbase.nim");
		(*l).Sentinel = s;
	}
	goto LA14;
	LA16: ;
	{
		nimln(93, "lexbase.nim");
		s = subInt(s, 1);
		{
			nimln(94, "lexbase.nim");
			while (1) {
				nimln(95, "lexbase.nim");
				{
					nimln(95, "lexbase.nim");
					nimln(95, "lexbase.nim");
					if (!!((s < (*l).Buflen))) goto LA23;
					nimln(95, "lexbase.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP169));
				}
				LA23: ;
				{
					nimln(96, "lexbase.nim");
					while (1) {
						NIM_BOOL LOC27;
						nimln(96, "lexbase.nim");
						LOC27 = 0;
						nimln(96, "lexbase.nim");
						LOC27 = (0 <= s);
						if (!(LOC27)) goto LA28;
						nimln(96, "lexbase.nim");
						nimln(96, "lexbase.nim");
						LOC27 = !((((NU8)((*l).Buf[s])) == ((NU8)(13)) || ((NU8)((*l).Buf[s])) == ((NU8)(10))));
						LA28: ;
						if (!LOC27) goto LA26;
						nimln(96, "lexbase.nim");
						s = subInt(s, 1);
					} LA26: ;
				}
				nimln(97, "lexbase.nim");
				{
					nimln(97, "lexbase.nim");
					if (!(0 <= s)) goto LA31;
					nimln(99, "lexbase.nim");
					(*l).Sentinel = s;
					nimln(100, "lexbase.nim");
					goto LA19;
				}
				goto LA29;
				LA31: ;
				{
					NI TMP170;
					NI TMP171;
					void* LOC34;
					NI TMP174;
					NI LOC39;
					NI TMP175;
					NI TMP178;
					nimln(104, "lexbase.nim");
					oldbuflen = (*l).Buflen;
					nimln(105, "lexbase.nim");
					nimln(105, "lexbase.nim");
					TMP170 = mulInt((*l).Buflen, 2);
					(*l).Buflen = (NI32)(TMP170);
					nimln(106, "lexbase.nim");
					nimln(106, "lexbase.nim");
					nimln(106, "lexbase.nim");
					TMP171 = mulInt((*l).Buflen, 1);
					LOC34 = 0;
					LOC34 = realloc_5833(((void*) ((*l).Buf)), (NI32)(TMP171));
					(*l).Buf = ((NCSTRING) (LOC34));
					nimln(107, "lexbase.nim");
					{
						NI TMP172;
						nimln(107, "lexbase.nim");
						nimln(107, "lexbase.nim");
						nimln(107, "lexbase.nim");
						TMP172 = subInt((*l).Buflen, oldbuflen);
						if (!!(((NI32)(TMP172) == oldbuflen))) goto LA37;
						nimln(107, "lexbase.nim");
						failedassertimpl_86825(((NimStringDesc*) &TMP173));
					}
					LA37: ;
					nimln(108, "lexbase.nim");
					nimln(109, "lexbase.nim");
					nimln(108, "lexbase.nim");
					nimln(109, "lexbase.nim");
					TMP174 = mulInt(oldbuflen, 1);
					LOC39 = 0;
					LOC39 = readdata_103182((*l).Input, ((void*) ((&(*l).Buf[oldbuflen]))), (NI32)(TMP174));
					TMP175 = divInt(LOC39, 1);
					charsread = (NI32)(TMP175);
					nimln(110, "lexbase.nim");
					{
						NI TMP176;
						NI TMP177;
						nimln(110, "lexbase.nim");
						if (!(charsread < oldbuflen)) goto LA42;
						nimln(111, "lexbase.nim");
						nimln(111, "lexbase.nim");
						TMP176 = addInt(oldbuflen, charsread);
						(*l).Buf[(NI32)(TMP176)] = 0;
						nimln(112, "lexbase.nim");
						nimln(112, "lexbase.nim");
						TMP177 = addInt(oldbuflen, charsread);
						(*l).Sentinel = (NI32)(TMP177);
						nimln(113, "lexbase.nim");
						goto LA19;
					}
					LA42: ;
					nimln(114, "lexbase.nim");
					nimln(114, "lexbase.nim");
					TMP178 = subInt((*l).Buflen, 1);
					s = (NI32)(TMP178);
				}
				LA29: ;
			}
		} LA19: ;
	}
	LA14: ;
	popFrame();
}

N_NIMCALL(NI, fillbaselexer_105828)(baselexer105011* l, NI pos) {
	NI result;
	nimfr("fillBaseLexer", "lexbase.nim")
	result = 0;
	nimln(117, "lexbase.nim");
	{
		nimln(117, "lexbase.nim");
		nimln(117, "lexbase.nim");
		if (!!((pos <= (*l).Sentinel))) goto LA3;
		nimln(117, "lexbase.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP179));
	}
	LA3: ;
	nimln(118, "lexbase.nim");
	{
		NI TMP180;
		nimln(118, "lexbase.nim");
		if (!(pos < (*l).Sentinel)) goto LA7;
		nimln(119, "lexbase.nim");
		nimln(119, "lexbase.nim");
		TMP180 = addInt(pos, 1);
		result = (NI32)(TMP180);
	}
	goto LA5;
	LA7: ;
	{
		nimln(121, "lexbase.nim");
		fillbuffer_105089(l);
		nimln(122, "lexbase.nim");
		(*l).Bufpos = 0;
		nimln(123, "lexbase.nim");
		result = 0;
	}
	LA5: ;
	nimln(124, "lexbase.nim");
	(*l).Linestart = result;
	popFrame();
	return result;
}

N_NIMCALL(NI, handlecr_105058)(baselexer105011* l, NI pos) {
	NI result;
	nimfr("handleCR", "lexbase.nim")
	result = 0;
	nimln(127, "lexbase.nim");
	{
		nimln(127, "lexbase.nim");
		nimln(127, "lexbase.nim");
		if (!!(((NU8)((*l).Buf[pos]) == (NU8)(13)))) goto LA3;
		nimln(127, "lexbase.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP181));
	}
	LA3: ;
	nimln(128, "lexbase.nim");
	(*l).Linenumber = addInt((*l).Linenumber, 1);
	nimln(129, "lexbase.nim");
	result = fillbaselexer_105828(l, pos);
	nimln(130, "lexbase.nim");
	{
		nimln(130, "lexbase.nim");
		if (!((NU8)((*l).Buf[result]) == (NU8)(10))) goto LA7;
		nimln(131, "lexbase.nim");
		result = fillbaselexer_105828(l, result);
	}
	LA7: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, handlelf_105066)(baselexer105011* l, NI pos) {
	NI result;
	nimfr("handleLF", "lexbase.nim")
	result = 0;
	nimln(134, "lexbase.nim");
	{
		nimln(134, "lexbase.nim");
		nimln(134, "lexbase.nim");
		if (!!(((NU8)((*l).Buf[pos]) == (NU8)(10)))) goto LA3;
		nimln(134, "lexbase.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP182));
	}
	LA3: ;
	nimln(135, "lexbase.nim");
	(*l).Linenumber = addInt((*l).Linenumber, 1);
	nimln(136, "lexbase.nim");
	result = fillbaselexer_105828(l, pos);
	popFrame();
	return result;
}

N_NIMCALL(void, skiputf8bom_106419)(baselexer105011* l) {
	nimfr("skipUtf8Bom", "lexbase.nim")
	nimln(139, "lexbase.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		nimln(139, "lexbase.nim");
		LOC3 = 0;
		nimln(139, "lexbase.nim");
		LOC4 = 0;
		nimln(139, "lexbase.nim");
		LOC4 = ((NU8)((*l).Buf[0]) == (NU8)(239));
		if (!(LOC4)) goto LA5;
		nimln(139, "lexbase.nim");
		LOC4 = ((NU8)((*l).Buf[1]) == (NU8)(187));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		nimln(139, "lexbase.nim");
		LOC3 = ((NU8)((*l).Buf[2]) == (NU8)(191));
		LA6: ;
		if (!LOC3) goto LA7;
		nimln(140, "lexbase.nim");
		(*l).Bufpos = addInt((*l).Bufpos, 3);
		nimln(141, "lexbase.nim");
		(*l).Linestart = addInt((*l).Linestart, 3);
	}
	LA7: ;
	popFrame();
}

N_NIMCALL(void, open_105027)(baselexer105011* l, streamobj103035* input, NI buflen) {
	NI TMP185;
	void* LOC9;
	NI TMP186;
	nimfr("open", "lexbase.nim")
	nimln(144, "lexbase.nim");
	{
		nimln(144, "lexbase.nim");
		nimln(144, "lexbase.nim");
		if (!!((0 < buflen))) goto LA3;
		nimln(144, "lexbase.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP183));
	}
	LA3: ;
	nimln(145, "lexbase.nim");
	{
		nimln(145, "lexbase.nim");
		nimln(145, "lexbase.nim");
		nimln(145, "lexbase.nim");
		if (!!(!((input == NIM_NIL)))) goto LA7;
		nimln(145, "lexbase.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP184));
	}
	LA7: ;
	nimln(146, "lexbase.nim");
	unsureAsgnRef((void**) (&(*l).Input), input);
	nimln(147, "lexbase.nim");
	(*l).Bufpos = 0;
	nimln(148, "lexbase.nim");
	(*l).Buflen = buflen;
	nimln(149, "lexbase.nim");
	nimln(149, "lexbase.nim");
	nimln(149, "lexbase.nim");
	TMP185 = mulInt(buflen, 1);
	LOC9 = 0;
	LOC9 = alloc_5801((NI32)(TMP185));
	(*l).Buf = ((NCSTRING) (LOC9));
	nimln(150, "lexbase.nim");
	nimln(150, "lexbase.nim");
	TMP186 = subInt(buflen, 1);
	(*l).Sentinel = (NI32)(TMP186);
	nimln(151, "lexbase.nim");
	(*l).Linestart = 0;
	nimln(152, "lexbase.nim");
	(*l).Linenumber = 1;
	nimln(153, "lexbase.nim");
	fillbuffer_105089(l);
	nimln(154, "lexbase.nim");
	skiputf8bom_106419(l);
	popFrame();
}

N_NIMCALL(NI, getcolnumber_105051)(baselexer105011* l, NI pos) {
	NI result;
	NI TMP187;
	nimfr("getColNumber", "lexbase.nim")
	result = 0;
	nimln(157, "lexbase.nim");
	nimln(157, "lexbase.nim");
	nimln(157, "lexbase.nim");
	TMP187 = subInt(pos, (*l).Linestart);
	if ((NI32)(TMP187) == (-2147483647 -1)) raiseOverflow();
	result = ((NI32)(TMP187) > 0? ((NI32)(TMP187)) : -((NI32)(TMP187)));
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, getcurrentline_105044)(baselexer105011* l, NIM_BOOL marker) {
	NimStringDesc* result;
	NI i;
	nimfr("getCurrentLine", "lexbase.nim")
	result = 0;
	i = 0;
	nimln(161, "lexbase.nim");
	result = copyString(((NimStringDesc*) &TMP188));
	nimln(162, "lexbase.nim");
	i = (*l).Linestart;
	{
		nimln(163, "lexbase.nim");
		while (1) {
			nimln(163, "lexbase.nim");
			nimln(163, "lexbase.nim");
			if (!!((((NU8)((*l).Buf[i])) == ((NU8)(13)) || ((NU8)((*l).Buf[i])) == ((NU8)(10)) || ((NU8)((*l).Buf[i])) == ((NU8)(0))))) goto LA2;
			nimln(164, "lexbase.nim");
			result = addChar(result, (*l).Buf[i]);
			nimln(165, "lexbase.nim");
			i = addInt(i, 1);
		} LA2: ;
	}
	nimln(166, "lexbase.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP189));
	nimln(167, "lexbase.nim");
	{
		NimStringDesc* LOC7;
		NI LOC8;
		NimStringDesc* LOC9;
		if (!marker) goto LA5;
		nimln(168, "lexbase.nim");
		nimln(168, "lexbase.nim");
		LOC7 = 0;
		nimln(168, "lexbase.nim");
		nimln(168, "lexbase.nim");
		LOC8 = 0;
		LOC8 = getcolnumber_105051(l, (*l).Bufpos);
		LOC9 = 0;
		LOC9 = nsuRepeatChar(LOC8, 32);
		LOC7 = rawNewString(LOC9->Sup.len + 3);
appendString(LOC7, LOC9);
appendString(LOC7, ((NimStringDesc*) &TMP191));
		result = resizeString(result, LOC7->Sup.len + 0);
appendString(result, LOC7);
	}
	LA5: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit)(void) {
	nimfr("lexbase", "lexbase.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit)(void) {
static TNimNode* TMP333[8];
static TNimNode TMP144[9];
NTI105011.size = sizeof(baselexer105011);
NTI105011.kind = 17;
NTI105011.base = (&NTI3211);
TMP333[0] = &TMP144[1];
TMP144[1].kind = 1;
TMP144[1].offset = offsetof(baselexer105011, Bufpos);
TMP144[1].typ = (&NTI108);
TMP144[1].name = "bufpos";
TMP333[1] = &TMP144[2];
TMP144[2].kind = 1;
TMP144[2].offset = offsetof(baselexer105011, Buf);
TMP144[2].typ = (&NTI151);
TMP144[2].name = "buf";
TMP333[2] = &TMP144[3];
TMP144[3].kind = 1;
TMP144[3].offset = offsetof(baselexer105011, Buflen);
TMP144[3].typ = (&NTI108);
TMP144[3].name = "bufLen";
TMP333[3] = &TMP144[4];
TMP144[4].kind = 1;
TMP144[4].offset = offsetof(baselexer105011, Input);
TMP144[4].typ = (&NTI103033);
TMP144[4].name = "input";
TMP333[4] = &TMP144[5];
TMP144[5].kind = 1;
TMP144[5].offset = offsetof(baselexer105011, Linenumber);
TMP144[5].typ = (&NTI108);
TMP144[5].name = "lineNumber";
TMP333[5] = &TMP144[6];
TMP144[6].kind = 1;
TMP144[6].offset = offsetof(baselexer105011, Sentinel);
TMP144[6].typ = (&NTI108);
TMP144[6].name = "sentinel";
TMP333[6] = &TMP144[7];
TMP144[7].kind = 1;
TMP144[7].offset = offsetof(baselexer105011, Linestart);
TMP144[7].typ = (&NTI108);
TMP144[7].name = "lineStart";
TMP333[7] = &TMP144[8];
TMP144[8].kind = 1;
TMP144[8].offset = offsetof(baselexer105011, Fileopened);
TMP144[8].typ = (&NTI138);
TMP144[8].name = "fileOpened";
TMP144[0].len = 8; TMP144[0].kind = 2; TMP144[0].sons = &TMP333[0];
NTI105011.node = &TMP144[0];
}

