/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_winlean.o c:\dropbox\2015\nim\packer\example\nimcache\stdlib_winlean.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include "Winsock2.h"

#include <string.h>

#include "winsock2.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tsecurityattributes158270 tsecurityattributes158270;
typedef struct tstartupinfo158272 tstartupinfo158272;
typedef struct tprocessinformation158274 tprocessinformation158274;
typedef struct twin32finddata159219 twin32finddata159219;
typedef struct tfiletime158276 tfiletime158276;
typedef struct tbyhandlefileinformation158278 tbyhandlefileinformation158278;
typedef struct servent159860 servent159860;
typedef struct hostent159862 hostent159862;
typedef struct tfdset159864 tfdset159864;
typedef struct timeval159866 timeval159866;
typedef struct addrinfo159868 addrinfo159868;
typedef struct toverlapped160608 toverlapped160608;
typedef struct tguid160614 tguid160614;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, TY158425) (NI hobject);
typedef N_STDCALL_PTR(NI32, TY158431) (NI hfile, void* buffer, NI32 nnumberofbytestoread, NI32* lpnumberofbytesread, void* lpoverlapped);
typedef N_STDCALL_PTR(NI32, TY158442) (NI hfile, void* buffer, NI32 nnumberofbytestowrite, NI32* lpnumberofbyteswritten, void* lpoverlapped);
typedef N_STDCALL_PTR(NI32, TY158453) (NI* hreadpipe, NI* hwritepipe, tsecurityattributes158270* lppipeattributes, NI32 nsize);
typedef N_STDCALL_PTR(NI32, TY158464) (NI16* lpapplicationname, NI16* lpcommandline, tsecurityattributes158270* lpprocessattributes, tsecurityattributes158270* lpthreadattributes, NI32 binherithandles, NI32 dwcreationflags, NI16* lpenvironment, NI16* lpcurrentdirectory, tstartupinfo158272* lpstartupinfo, tprocessinformation158274* lpprocessinformation);
typedef N_STDCALL_PTR(NI32, TY158605) (NI hthread);
typedef N_STDCALL_PTR(NI32, TY158611) (NI hthread);
typedef N_STDCALL_PTR(NI32, TY158617) (NI hhandle, NI32 dwmilliseconds);
typedef N_STDCALL_PTR(NI32, TY158624) (NI hprocess, NI uexitcode);
typedef N_STDCALL_PTR(NI32, TY158631) (NI hprocess, NI32* lpexitcode);
typedef N_STDCALL_PTR(NI, TY158639) (NI32 nstdhandle);
typedef N_STDCALL_PTR(NI32, TY158645) (NI32 nstdhandle, NI hhandle);
typedef N_STDCALL_PTR(NI32, TY158652) (NI hfile);
typedef N_STDCALL_PTR(NI32, TY158658) (void);
typedef N_STDCALL_PTR(NI32, TY158663) (NI32 dwflags, void* lpsource, NI32 dwmessageid, NI32 dwlanguageid, void* lpbuffer, NI32 nsize, void* arguments);
typedef N_STDCALL_PTR(void, TY158805) (void* p);
typedef N_STDCALL_PTR(NI32, TY158811) (NI32 nbufferlength, NI16* lpbuffer);
typedef N_STDCALL_PTR(NI32, TY158815) (NI16* lppathname);
typedef N_STDCALL_PTR(NI32, TY158818) (NI16* pathname, void* security);
typedef N_STDCALL_PTR(NI32, TY158822) (NI16* lppathname);
typedef N_STDCALL_PTR(NI32, TY158825) (NI16* lpname, NI16* lpvalue);
typedef N_STDCALL_PTR(NI32, TY158829) (NI handle, NI16* buf, NI32 size);
typedef N_STDCALL_PTR(NI32, TY159005) (NI16* lpsymlinkfilename, NI16* lptargetfilename, NI32 flags);
typedef N_STDCALL_PTR(NI32, TY159010) (NI16* lpfilename, NI16* lpexistingfilename, void* security);
typedef N_STDCALL_PTR(NI, TY159239) (NI16* lpfilename, twin32finddata159219* lpfindfiledata);
typedef N_STDCALL_PTR(NI32, TY159244) (NI hfindfile, twin32finddata159219* lpfindfiledata);
typedef N_STDCALL_PTR(void, TY159405) (NI hfindfile);
typedef N_STDCALL_PTR(NI32, TY159411) (NI16* lpfilename, NI32 nbufferlength, NI16* lpbuffer, NI16** lpfilepart);
typedef N_STDCALL_PTR(NI32, TY159418) (NI16* lpfilename);
typedef N_STDCALL_PTR(NI32, TY159421) (NI16* lpfilename, NI32 dwfileattributes);
typedef N_STDCALL_PTR(int, TY159425) (NI16* lpexistingfilename, NI16* lpnewfilename, int bfailifexists);
typedef N_STDCALL_PTR(NI16*, TY159430) (void);
typedef N_STDCALL_PTR(NI32, TY159432) (NI16* para1);
typedef N_STDCALL_PTR(NI16*, TY159435) (void);
struct  tfiletime158276  {
NI32 Dwlowdatetime;
NI32 Dwhighdatetime;
};
typedef NI16 TY159228[260];
typedef NI16 TY159232[14];
struct  twin32finddata159219  {
NI32 Dwfileattributes;
tfiletime158276 Ftcreationtime;
tfiletime158276 Ftlastaccesstime;
tfiletime158276 Ftlastwritetime;
NI32 Nfilesizehigh;
NI32 Nfilesizelow;
NI32 Dwreserved0;
NI32 Dwreserved1;
TY159228 Cfilename;
TY159232 Calternatefilename;
};
typedef N_STDCALL_PTR(void, TY159625) (tfiletime158276* lpsystemtimeasfiletime);
typedef N_STDCALL_PTR(void, TY159632) (NI32 dwmilliseconds);
typedef N_STDCALL_PTR(NI, TY159638) (NI hwnd, NI16* lpoperation, NI16* lpfile, NI16* lpparameters, NI16* lpdirectory, NI32 nshowcmd);
typedef N_STDCALL_PTR(NI32, TY159805) (NI hfile, tbyhandlefileinformation158278* lpfileinformation);
typedef N_CDECL_PTR(int, TY159832) (void);
typedef N_STDCALL_PTR(servent159860*, TY159991) (NCSTRING name, NCSTRING proto);
typedef N_STDCALL_PTR(servent159860*, TY159999) (int port, NCSTRING proto);
typedef N_STDCALL_PTR(hostent159862*, TY160007) (IN_ADDR* ip, int len, int thetype);
typedef N_STDCALL_PTR(hostent159862*, TY160017) (NCSTRING name);
typedef N_STDCALL_PTR(NI, TY160024) (int af, int typ, int protocol);
typedef N_STDCALL_PTR(int, TY160032) (NI s);
typedef N_STDCALL_PTR(NI, TY160038) (NI s, SOCKADDR* a, int* addrlen);
typedef N_STDCALL_PTR(int, TY160048) (NI s, SOCKADDR* name, int namelen);
typedef N_STDCALL_PTR(int, TY160057) (NI s, SOCKADDR* name, int namelen);
typedef N_STDCALL_PTR(int, TY160066) (NI s, SOCKADDR* name, int* namelen);
typedef N_STDCALL_PTR(int, TY160076) (NI s, int level, int optname, void* optval, int* optlen);
typedef N_STDCALL_PTR(int, TY160087) (NI s, int level, int optname, void* optval, int optlen);
typedef N_STDCALL_PTR(int, TY160097) (NI s, int backlog);
typedef N_STDCALL_PTR(int, TY160104) (NI s, void* buf, int len, int flags);
typedef N_STDCALL_PTR(int, TY160113) (NI s, NCSTRING buf, int len, int flags, SOCKADDR* fromm, int* fromlen);
typedef N_STDCALL_PTR(int, TY160126) (int nfds, tfdset159864* readfds, tfdset159864* writefds, tfdset159864* exceptfds, timeval159866* timeout);
typedef N_STDCALL_PTR(int, TY160138) (NI s, void* buf, int len, int flags);
typedef N_STDCALL_PTR(int, TY160147) (NI s, void* buf, int len, int flags, SOCKADDR* to, int tolen);
typedef N_STDCALL_PTR(int, TY160159) (NI s, int how);
typedef N_STDCALL_PTR(int, TY160166) (SOCKADDR* a1, int a2, NCSTRING a3, int a4, NCSTRING a5, int a6, int a7);
typedef N_STDCALL_PTR(NI32, TY160179) (NCSTRING cp);
typedef N_STDCALL_PTR(NIM_BOOL, TY160185) (NI s, tfdset159864* set);
typedef NI TY159915[64];
struct  tfdset159864  {
int Fdcount;
TY159915 Fdarray;
};
typedef N_STDCALL_PTR(int, TY160241) (NI16 wversionrequired, WSADATA* wsdata);
typedef N_STDCALL_PTR(int, TY160249) (NCSTRING nodename, NCSTRING servname, addrinfo159868* hints, addrinfo159868** res);
typedef N_STDCALL_PTR(void, TY160261) (addrinfo159868* ai);
typedef N_STDCALL_PTR(NCSTRING, TY160268) (IN_ADDR i);
typedef N_STDCALL_PTR(NI32, TY160286) (NI32 ncount, NI* lphandles, NI32 bwaitall, NI32 dwmilliseconds);
typedef N_STDCALL_PTR(NI, TY160322) (NI16* lpfilename, NI32 dwdesiredaccess, NI32 dwsharemode, void* lpsecurityattributes, NI32 dwcreationdisposition, NI32 dwflagsandattributes, NI htemplatefile);
typedef N_STDCALL_PTR(NI32, TY160331) (NI16* pathname);
typedef N_STDCALL_PTR(NI32, TY160405) (NI hfile);
typedef N_STDCALL_PTR(NI32, TY160411) (NI hfile, NI32 ldistancetomove, NI32* lpdistancetomovehigh, NI32 dwmovemethod);
typedef N_STDCALL_PTR(NI32, TY160421) (NI hfile, NI32* lpfilesizehigh);
typedef N_STDCALL_PTR(void*, TY160429) (NI hfilemappingobject, NI32 dwdesiredaccess, NI32 dwfileoffsethigh, NI32 dwfileoffsetlow, NI32 dwnumberofbytestomap, void* lpbaseaddress);
typedef N_STDCALL_PTR(NI, TY160440) (NI hfile, void* lpfilemappingattributes, NI32 flprotect, NI32 dwmaximumsizehigh, NI32 dwmaximumsizelow, void* lpname);
typedef N_STDCALL_PTR(NI32, TY160602) (void* lpbaseaddress);
typedef N_STDCALL_PTR(NI, TY160652) (NI filehandle, NI existingcompletionport, NI32 completionkey, NI32 numberofconcurrentthreads);
typedef N_STDCALL_PTR(NI32, TY160661) (NI completionport, NI32* lpnumberofbytestransferred, NI* lpcompletionkey, toverlapped160608** lpoverlapped, NI32 dwmilliseconds);
struct  toverlapped160608  {
NI* Internal;
NI* Internalhigh;
NI32 Offset;
NI32 Offsethigh;
NI Hevent;
};
typedef N_STDCALL_PTR(NI32, TY160672) (NI hfile, toverlapped160608* lpoverlapped, NI32* lpnumberofbytestransferred, NI32 bwait);
typedef NI8 TY160627[8];
struct  tguid160614  {
NI32 D1;
NI16 D2;
NI16 D3;
TY160627 D4;
};
typedef NI8 TY160708[8];
typedef N_STDCALL_PTR(void, poverlappedcompletionroutine160612) (NI32 para1, NI32 para2, toverlapped160608* para3);
typedef N_STDCALL_PTR(int, TY160729) (NI s, NI32 dwiocontrolcode, void* lpvinbuffer, NI32 cbinbuffer, void* lpvoutbuffer, NI32 cboutbuffer, NI32* lpcbbytesreturned, toverlapped160608* lpoverlapped, poverlappedcompletionroutine160612 lpcompletionroutine);
typedef N_STDCALL_PTR(int, TY160750) (NI s, WSABUF* buf, NI32 bufcount, NI32* bytesreceived, NI32* flags, toverlapped160608* lpoverlapped, poverlappedcompletionroutine160612 completionproc);
typedef N_STDCALL_PTR(int, TY160763) (NI s, WSABUF* buf, NI32 bufcount, NI32* bytessent, NI32 flags, toverlapped160608* lpoverlapped, poverlappedcompletionroutine160612 completionproc);
typedef N_STDCALL_PTR(NI32, TY160782) (tfiletime158276* lpidletime, tfiletime158276* lpkerneltime, tfiletime158276* lpusertime);
typedef N_STDCALL_PTR(NI32, TY160791) (NI hprocess, tfiletime158276* lpcreationtime, tfiletime158276* lpexittime, tfiletime158276* lpkerneltime, tfiletime158276* lpusertime);
struct  tsecurityattributes158270  {
NI32 Nlength;
void* Lpsecuritydescriptor;
NI32 Binherithandle;
};
struct  tstartupinfo158272  {
NI32 Cb;
NCSTRING Lpreserved;
NCSTRING Lpdesktop;
NCSTRING Lptitle;
NI32 Dwx;
NI32 Dwy;
NI32 Dwxsize;
NI32 Dwysize;
NI32 Dwxcountchars;
NI32 Dwycountchars;
NI32 Dwfillattribute;
NI32 Dwflags;
NI16 Wshowwindow;
NI16 Cbreserved2;
void* Lpreserved2;
NI Hstdinput;
NI Hstdoutput;
NI Hstderror;
};
struct  tprocessinformation158274  {
NI Hprocess;
NI Hthread;
NI32 Dwprocessid;
NI32 Dwthreadid;
};
struct  tbyhandlefileinformation158278  {
NI32 Dwfileattributes;
tfiletime158276 Ftcreationtime;
tfiletime158276 Ftlastaccesstime;
tfiletime158276 Ftlastwritetime;
NI32 Dwvolumeserialnumber;
NI32 Nfilesizehigh;
NI32 Nfilesizelow;
NI32 Nnumberoflinks;
NI32 Nfileindexhigh;
NI32 Nfileindexlow;
};
struct  servent159860  {
NCSTRING Sname;
NCSTRING* Saliases;
NI16 Sport;
NCSTRING Sproto;
};
struct  hostent159862  {
NCSTRING Hname;
NCSTRING* Haliases;
NI16 Haddrtype;
NI16 Hlength;
NCSTRING* Haddrlist;
};
typedef NIM_CHAR TY159883[14];
struct  timeval159866  {
NI32 Tvsec;
NI32 Tvusec;
};
typedef NIM_CHAR TY159873[257];
typedef NIM_CHAR TY159876[129];
struct  addrinfo159868  {
int Aiflags;
int Aifamily;
int Aisocktype;
int Aiprotocol;
NI Aiaddrlen;
NCSTRING Aicanonname;
SOCKADDR* Aiaddr;
addrinfo159868* Ainext;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(NI64, rdfiletime_159604)(tfiletime158276 f);
N_NIMCALL(NI64, rdfilesize_159614)(twin32finddata159219* f);
N_NIMCALL(int, fdisset_160192)(NI socket, tfdset159864* set);
N_NIMCALL(void, fdset_160204)(NI socket, tfdset159864* s);
N_NIMCALL(void, fdzero_160230)(tfdset159864* s);
STRING_LITERAL(TMP536, "kernel32", 8);
STRING_LITERAL(TMP537, "kernel32", 8);
STRING_LITERAL(TMP539, "shell32.dll", 11);
STRING_LITERAL(TMP540, "shell32.dll", 11);
STRING_LITERAL(TMP542, "Ws2_32.dll", 10);
STRING_LITERAL(TMP543, "Ws2_32.dll", 10);
NIM_CONST TY160708 TMP544 = {((NI8) -114),
((NI8) -23),
((NI8) 118),
((NI8) -27),
((NI8) -116),
((NI8) 116),
((NI8) 6),
((NI8) 62)}
;
NIM_CONST TY160708 TMP545 = {((NI8) -107),
((NI8) -54),
((NI8) 0),
((NI8) -128),
((NI8) 95),
((NI8) 72),
((NI8) -95),
((NI8) -110)}
;
static void* TMP535;
TY158425 Dl_158424;
TY158431 Dl_158430;
TY158442 Dl_158441;
TY158453 Dl_158452;
TY158464 Dl_158463;
TY158605 Dl_158604;
TY158611 Dl_158610;
TY158617 Dl_158616;
TY158624 Dl_158623;
TY158631 Dl_158630;
TY158639 Dl_158638;
TY158645 Dl_158644;
TY158652 Dl_158651;
TY158658 Dl_158657;
TY158663 Dl_158662;
TY158805 Dl_158804;
TY158811 Dl_158810;
TY158815 Dl_158814;
TY158818 Dl_158817;
TY158822 Dl_158821;
TY158825 Dl_158824;
TY158829 Dl_158828;
TY159005 Dl_159004;
TY159010 Dl_159009;
TY159239 Dl_159238;
TY159244 Dl_159243;
TY159405 Dl_159404;
TY159411 Dl_159410;
TY159418 Dl_159417;
TY159421 Dl_159420;
TY159425 Dl_159424;
TY159430 Dl_159429;
TY159432 Dl_159431;
TY159435 Dl_159434;
TY159625 Dl_159624;
TY159632 Dl_159631;
static void* TMP538;
TY159638 Dl_159637;
TY159805 Dl_159804;
static void* TMP541;
TY159832 Dl_159831;
TY159991 Dl_159990;
TY159999 Dl_159998;
TY160007 Dl_160006;
TY160017 Dl_160016;
TY160024 Dl_160023;
TY160032 Dl_160031;
TY160038 Dl_160037;
TY160048 Dl_160047;
TY160057 Dl_160056;
TY160066 Dl_160065;
TY160076 Dl_160075;
TY160087 Dl_160086;
TY160097 Dl_160096;
TY160104 Dl_160103;
TY160113 Dl_160112;
TY160126 Dl_160125;
TY160138 Dl_160137;
TY160147 Dl_160146;
TY160159 Dl_160158;
TY160166 Dl_160165;
TY160179 Dl_160178;
TY160185 Dl_160184;
TY160241 Dl_160240;
TY160249 Dl_160248;
TY160261 Dl_160260;
TY160268 Dl_160267;
TY160286 Dl_160285;
TY160322 Dl_160321;
TY160331 Dl_160330;
TY160405 Dl_160404;
TY160411 Dl_160410;
TY160421 Dl_160420;
TY160429 Dl_160428;
TY160440 Dl_160439;
TY160602 Dl_160601;
TY160652 Dl_160651;
TY160661 Dl_160660;
TY160672 Dl_160671;
tguid160614 wsaidconnectex_160710;
tguid160614 wsaidacceptex_160714;
tguid160614 wsaidgetacceptexsockaddrs_160718;
TY160729 Dl_160728;
TY160750 Dl_160749;
TY160763 Dl_160762;
TY160782 Dl_160781;
TY160791 Dl_160790;

N_NIMCALL(NI64, rdfiletime_159604)(tfiletime158276 f) {
	NI64 result;
	result = 0;
	result = (NI64)(((NI64)(NU64)(NU32)(f.Dwlowdatetime)) | (NI64)((NU64)(((NI64)(NU64)(NU32)(f.Dwhighdatetime))) << (NU64)(IL64(32))));
	return result;
}

N_NIMCALL(NI64, rdfilesize_159614)(twin32finddata159219* f) {
	NI64 result;
	result = 0;
	result = (NI64)(((NI64)(NU64)(NU32)((*f).Nfilesizelow)) | (NI64)((NU64)(((NI64)(NU64)(NU32)((*f).Nfilesizehigh))) << (NU64)(IL64(32))));
	return result;
}

N_NIMCALL(int, fdisset_160192)(NI socket, tfdset159864* set) {
	int result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = Dl_160184(socket, set);
		if (!LOC3) goto LA4;
		result = ((NI32) 1);
	}
	goto LA1;
	LA4: ;
	{
		result = ((NI32) 0);
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, fdset_160204)(NI socket, tfdset159864* s) {
	{
		if (!((*s).Fdcount < ((NI32) 64))) goto LA3;
		(*s).Fdarray[(((NI) ((*s).Fdcount)))- 0] = socket;
		(*s).Fdcount += 1;
	}
	LA3: ;
}

N_NIMCALL(void, fdzero_160230)(tfdset159864* s) {
	(*s).Fdcount = ((int) 0);
}
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void) {
	tguid160614 LOC1;
	tguid160614 LOC2;
	tguid160614 LOC3;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.D1 = ((NI32) 631375801);
	LOC1.D2 = ((NI16) -8717);
	LOC1.D3 = ((NI16) 18016);
	memcpy((void*)LOC1.D4, (NIM_CONST void*)TMP544, sizeof(LOC1.D4));
	wsaidconnectex_160710 = LOC1;
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.D1 = ((NI32) -1254720015);
	LOC2.D2 = ((NI16) -13396);
	LOC2.D3 = ((NI16) 4559);
	memcpy((void*)LOC2.D4, (NIM_CONST void*)TMP545, sizeof(LOC2.D4));
	wsaidacceptex_160714 = LOC2;
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	LOC3.D1 = ((NI32) -1254720014);
	LOC3.D2 = ((NI16) -13396);
	LOC3.D3 = ((NI16) 4559);
	memcpy((void*)LOC3.D4, (NIM_CONST void*)TMP545, sizeof(LOC3.D4));
	wsaidgetacceptexsockaddrs_160718 = LOC3;
}

NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void) {
if (!((TMP535 = nimLoadLibrary((NimStringDesc*) &TMP536))
)) nimLoadLibraryError((NimStringDesc*) &TMP537);
	Dl_158424 = (TY158425) nimGetProcAddr(TMP535, "CloseHandle");
	Dl_158430 = (TY158431) nimGetProcAddr(TMP535, "ReadFile");
	Dl_158441 = (TY158442) nimGetProcAddr(TMP535, "WriteFile");
	Dl_158452 = (TY158453) nimGetProcAddr(TMP535, "CreatePipe");
	Dl_158463 = (TY158464) nimGetProcAddr(TMP535, "CreateProcessW");
	Dl_158604 = (TY158605) nimGetProcAddr(TMP535, "SuspendThread");
	Dl_158610 = (TY158611) nimGetProcAddr(TMP535, "ResumeThread");
	Dl_158616 = (TY158617) nimGetProcAddr(TMP535, "WaitForSingleObject");
	Dl_158623 = (TY158624) nimGetProcAddr(TMP535, "TerminateProcess");
	Dl_158630 = (TY158631) nimGetProcAddr(TMP535, "GetExitCodeProcess");
	Dl_158638 = (TY158639) nimGetProcAddr(TMP535, "GetStdHandle");
	Dl_158644 = (TY158645) nimGetProcAddr(TMP535, "SetStdHandle");
	Dl_158651 = (TY158652) nimGetProcAddr(TMP535, "FlushFileBuffers");
	Dl_158657 = (TY158658) nimGetProcAddr(TMP535, "GetLastError");
	Dl_158662 = (TY158663) nimGetProcAddr(TMP535, "FormatMessageW");
	Dl_158804 = (TY158805) nimGetProcAddr(TMP535, "LocalFree");
	Dl_158810 = (TY158811) nimGetProcAddr(TMP535, "GetCurrentDirectoryW");
	Dl_158814 = (TY158815) nimGetProcAddr(TMP535, "SetCurrentDirectoryW");
	Dl_158817 = (TY158818) nimGetProcAddr(TMP535, "CreateDirectoryW");
	Dl_158821 = (TY158822) nimGetProcAddr(TMP535, "RemoveDirectoryW");
	Dl_158824 = (TY158825) nimGetProcAddr(TMP535, "SetEnvironmentVariableW");
	Dl_158828 = (TY158829) nimGetProcAddr(TMP535, "GetModuleFileNameW");
	Dl_159004 = (TY159005) nimGetProcAddr(TMP535, "CreateSymbolicLinkW");
	Dl_159009 = (TY159010) nimGetProcAddr(TMP535, "CreateHardLinkW");
	Dl_159238 = (TY159239) nimGetProcAddr(TMP535, "FindFirstFileW");
	Dl_159243 = (TY159244) nimGetProcAddr(TMP535, "FindNextFileW");
	Dl_159404 = (TY159405) nimGetProcAddr(TMP535, "FindClose");
	Dl_159410 = (TY159411) nimGetProcAddr(TMP535, "GetFullPathNameW");
	Dl_159417 = (TY159418) nimGetProcAddr(TMP535, "GetFileAttributesW");
	Dl_159420 = (TY159421) nimGetProcAddr(TMP535, "SetFileAttributesW");
	Dl_159424 = (TY159425) nimGetProcAddr(TMP535, "CopyFileW");
	Dl_159429 = (TY159430) nimGetProcAddr(TMP535, "GetEnvironmentStringsW");
	Dl_159431 = (TY159432) nimGetProcAddr(TMP535, "FreeEnvironmentStringsW");
	Dl_159434 = (TY159435) nimGetProcAddr(TMP535, "GetCommandLineW");
	Dl_159624 = (TY159625) nimGetProcAddr(TMP535, "GetSystemTimeAsFileTime");
	Dl_159631 = (TY159632) nimGetProcAddr(TMP535, "Sleep");
if (!((TMP538 = nimLoadLibrary((NimStringDesc*) &TMP539))
)) nimLoadLibraryError((NimStringDesc*) &TMP540);
	Dl_159637 = (TY159638) nimGetProcAddr(TMP538, "ShellExecuteW");
	Dl_159804 = (TY159805) nimGetProcAddr(TMP535, "GetFileInformationByHandle");
if (!((TMP541 = nimLoadLibrary((NimStringDesc*) &TMP542))
)) nimLoadLibraryError((NimStringDesc*) &TMP543);
	Dl_159831 = (TY159832) nimGetProcAddr(TMP541, "WSAGetLastError");
	Dl_159990 = (TY159991) nimGetProcAddr(TMP541, "getservbyname");
	Dl_159998 = (TY159999) nimGetProcAddr(TMP541, "getservbyport");
	Dl_160006 = (TY160007) nimGetProcAddr(TMP541, "gethostbyaddr");
	Dl_160016 = (TY160017) nimGetProcAddr(TMP541, "gethostbyname");
	Dl_160023 = (TY160024) nimGetProcAddr(TMP541, "socket");
	Dl_160031 = (TY160032) nimGetProcAddr(TMP541, "closesocket");
	Dl_160037 = (TY160038) nimGetProcAddr(TMP541, "accept");
	Dl_160047 = (TY160048) nimGetProcAddr(TMP541, "bind");
	Dl_160056 = (TY160057) nimGetProcAddr(TMP541, "connect");
	Dl_160065 = (TY160066) nimGetProcAddr(TMP541, "getsockname");
	Dl_160075 = (TY160076) nimGetProcAddr(TMP541, "getsockopt");
	Dl_160086 = (TY160087) nimGetProcAddr(TMP541, "setsockopt");
	Dl_160096 = (TY160097) nimGetProcAddr(TMP541, "listen");
	Dl_160103 = (TY160104) nimGetProcAddr(TMP541, "recv");
	Dl_160112 = (TY160113) nimGetProcAddr(TMP541, "recvfrom");
	Dl_160125 = (TY160126) nimGetProcAddr(TMP541, "select");
	Dl_160137 = (TY160138) nimGetProcAddr(TMP541, "send");
	Dl_160146 = (TY160147) nimGetProcAddr(TMP541, "sendto");
	Dl_160158 = (TY160159) nimGetProcAddr(TMP541, "shutdown");
	Dl_160165 = (TY160166) nimGetProcAddr(TMP541, "getnameinfo");
	Dl_160178 = (TY160179) nimGetProcAddr(TMP541, "inet_addr");
	Dl_160184 = (TY160185) nimGetProcAddr(TMP541, "__WSAFDIsSet");
	Dl_160240 = (TY160241) nimGetProcAddr(TMP541, "WSAStartup");
	Dl_160248 = (TY160249) nimGetProcAddr(TMP541, "getaddrinfo");
	Dl_160260 = (TY160261) nimGetProcAddr(TMP541, "freeaddrinfo");
	Dl_160267 = (TY160268) nimGetProcAddr(TMP541, "inet_ntoa");
	Dl_160285 = (TY160286) nimGetProcAddr(TMP535, "WaitForMultipleObjects");
	Dl_160321 = (TY160322) nimGetProcAddr(TMP535, "CreateFileW");
	Dl_160330 = (TY160331) nimGetProcAddr(TMP535, "DeleteFileW");
	Dl_160404 = (TY160405) nimGetProcAddr(TMP535, "SetEndOfFile");
	Dl_160410 = (TY160411) nimGetProcAddr(TMP535, "SetFilePointer");
	Dl_160420 = (TY160421) nimGetProcAddr(TMP535, "GetFileSize");
	Dl_160428 = (TY160429) nimGetProcAddr(TMP535, "MapViewOfFileEx");
	Dl_160439 = (TY160440) nimGetProcAddr(TMP535, "CreateFileMappingW");
	Dl_160601 = (TY160602) nimGetProcAddr(TMP535, "UnmapViewOfFile");
	Dl_160651 = (TY160652) nimGetProcAddr(TMP535, "CreateIoCompletionPort");
	Dl_160660 = (TY160661) nimGetProcAddr(TMP535, "GetQueuedCompletionStatus");
	Dl_160671 = (TY160672) nimGetProcAddr(TMP535, "GetOverlappedResult");
	Dl_160728 = (TY160729) nimGetProcAddr(TMP541, "WSAIoctl");
	Dl_160749 = (TY160750) nimGetProcAddr(TMP541, "WSARecv");
	Dl_160762 = (TY160763) nimGetProcAddr(TMP541, "WSASend");
	Dl_160781 = (TY160782) nimGetProcAddr(TMP535, "GetSystemTimes");
	Dl_160790 = (TY160791) nimGetProcAddr(TMP535, "GetProcessTimes");
}

